Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs
=> #128 : fixing exception on undefined index in IndexDescriptor

Jint/Native/Function/ScriptFunctionInstance.cs, Jint/Runtime/Completion.cs, Jint/Runtime/JavaScriptException.cs, Jint/Runtime/StatementInterpreter.cs
Add line and column location of error returning JavaScriptException.
=> Return error location with JavaScriptException.

Jint.Tests/Jint.Tests.csproj, Jint.Tests/Runtime/JsValueConversionTests.cs, Jint/Native/JsValue.cs
As discussed in my previous PR, here is the changes on JsValue only to be more consistent, and enable newtonsoft.json (or other ?) conversion.
=> added as/is date

Jint/Jint.csproj, Jint/Runtime/Interop/ObjectWrapper.cs
=> Case resolve

Jint.Tests/Runtime/EngineTests.cs, Jint/Runtime/Debugger/DebugHandler.cs, Jint/Runtime/Debugger/StepMode.cs
In the previous commit, I have mixed the Step Over and Step Out concepts.
There was a Step Over mode that in reality was behaving like a Step Out.
Now I have added the Step Out in the StepMode enum, and provided the correct implementation for the Step Over.
=> Debug - Support for Step Over

Jint/Engine.cs, Jint/Runtime/StatementInterpreter.cs
Added the Location of the throw statement to the resulting JavaScriptException.
=> Add the location of throw statement to the JavaScriptException

Jint.Tests/Runtime/EngineTests.cs, Jint/Runtime/Interop/ClrFunctionInstance.cs
=> Making ClrFunctionInstance extensible

Jint.Tests/Runtime/EngineTests.cs, Jint/Native/Array/ArrayInstance.cs
=> Fixing array index detection

Jint.Tests/Runtime/EngineTests.cs, Jint/Native/Date/DateConstructor.cs, Jint/Native/Date/DatePrototype.cs, Jint/Native/Number/NumberConstructor.cs, Jint/Native/Number/NumberPrototype.cs
=> Using local timezone and formats for `toLocale` functions

Jint/Runtime/Interop/DefaultTypeConverter.cs
fix: https://github.com/sebastienros/jint/issues/249
=> boxing before calling JsValue.FromObject

Jint.Tests/Runtime/EngineTests.cs, Jint/Native/Date/DatePrototype.cs
fix issue #285. All tests passing
=> fix Date ToISOString pre 1970

Jint/Parser/JavascriptParser.cs
58 is not ; but :. The char code for ; is 59
=> Change char code

Jint.Tests/Jint.Tests.csproj, Jint.Tests/Runtime/ErrorTests.cs, Jint/Engine.cs, Jint/Native/Function/EvalFunctionInstance.cs, Jint/Native/Function/ScriptFunctionInstance.cs, Jint/Runtime/CallStack/JintCallStack.cs, Jint/Runtime/ExpressionIntepreter.cs, Jint/Runtime/JavaScriptException.cs, Jint/Runtime/TypeConverter.cs
- Will track the identifier that cause an undefined / null access
- Will report the call stack of the error to the user
=> Better error from scripts.

Jint.Tests/Runtime/NullPropagation.cs
=> Fix class name typo

Jint.Tests/Jint.Tests.csproj, Jint.Tests/Parser/JavascriptParserTests.cs, Jint.Tests/Runtime/EngineTests.cs, Jint/Native/Date/DateConstructor.cs, Jint/Native/Date/DatePrototype.cs
=> Fixing Date.getHours

Jint.Tests/Parser/JavascriptParserTests.cs, Jint/Parser/JavascriptParser.cs
=> Supporting big hex literal

Jint.Benchmark/ArrayStressBenchmark.cs, Jint.Benchmark/DromaeoBenchmark.cs, Jint.Benchmark/Jint.Benchmark.csproj, Jint.Benchmark/StopwatchBenchmark.cs, Jint.Benchmark/SunSpiderBenchmark.cs, Jint/Jint.csproj
* add StopwatchBenchmark
* make benchmarks more reliable with longer run counts
=> Upgrade Esprima and BenchmarkDotNet

Jint.Tests/Runtime/EngineTests.cs, Jint/Native/Json/JsonInstance.cs
modified JSON.parse according to spec.
=> fixed bug #436

Jint.Tests/Runtime/EngineTests.cs, Jint/Native/Date/DatePrototype.cs
=> Fixing TimeWithinDay for negative values

Jint.Benchmark/Jint.Benchmark.csproj, Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj, Jint.Tests.Ecma/Jint.Tests.Ecma.csproj, Jint.Tests.Test262/Jint.Tests.Test262.csproj, Jint.Tests.Test262/test/skipped.json, Jint.Tests/Jint.Tests.csproj, Jint/EsprimaExtensions.cs, Jint/Jint.csproj, Jint/Native/JsValue.cs, Jint/Native/Map/MapConstructor.cs, Jint/Native/Set/SetConstructor.cs, Jint/Runtime/JavaScriptException.cs
Now that Esprima was fixed to understand the object syntax, I could include the test and tweak it to pass.
=> Upgrade Esprima and other libs, and include iterator test

README.md
I believe the intention of the sample was to show that the CLR object is changed
=> Highlighting that `Person.Name` is changed from JS

Jint.Tests.Ecma/EcmaTest.cs, Jint.Tests.Test262/Test262Test.cs, appveyor.yml
Allows VS.NET to list all resolved unit tests
=> Implemented IXunitSerializable

Jint.Benchmark/Jint.Benchmark.csproj, Jint.Tests.Ecma/TestCases/alltests.json, Jint.Tests.Test262/LanguageTests.cs, Jint.Tests.Test262/Test262Test.cs, Jint.Tests.Test262/test/skipped.json, Jint/Engine.cs, Jint/EsprimaExtensions.cs, Jint/Jint.csproj, Jint/Native/Function/ArrowFunctionInstance.cs, Jint/Native/Function/FunctionInstance.cs, Jint/Native/Function/FunctionPrototype.cs, Jint/Native/Function/ScriptFunctionInstance.cs, Jint/Native/JsString.cs, Jint/Native/JsValue.cs, Jint/Runtime/ExceptionHelper.cs, Jint/Runtime/Interpreter/Expressions/JintExpression.cs, Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs, Jint/Runtime/Interpreter/JintFunctionDefinition.cs, Jint/Runtime/Interpreter/Statements/JintStatement.cs, Jint/Runtime/JavaScriptException.cs, README.md
* enabling tests
* adding some missing bits
* changing engine to use parser in tolerant mode by default, seems to be how other runtimes work too
=> ES6 Object Literals

Jint/Runtime/Interop/DefaultTypeConverter.cs
Fixes #619 by switching from a `Dictionary<sting, bool>` with manual locking to a `ConcurrentDictionary<string, bool>` in `DefaultTypeConverter`.
=> Fix for NullReferenceException reported in #619

Jint.Tests/Runtime/RegExpTests.cs, Jint/Engine.cs, Jint/JsValueExtensions.cs, Jint/Native/RegExp/RegExpConstructor.cs, Jint/Options.cs, Jint/Runtime/Interpreter/Expressions/JintLiteralExpression.cs
=> Timeout for regex.

Jint.Tests/Parser/JavascriptParserTests.cs, Jint/Runtime/Interpreter/Expressions/JintUpdateExpression.cs
Relates to https://github.com/sebastienros/jint/issues/571 (InvalidCastException)
=> Improve JintUpdateExpression error handling

Jint.Tests/Runtime/NumberTests.cs, Jint/Native/Number/NumberPrototype.cs
=> Number.toPrecision throws between 26 & 100

Jint/Directory.Build.props
-fixes Error MSB4057 The target "SetEmbeddedFilesFromSourceControlManagerUntrackedFiles" during build
=> Update SourceLink.GitHub in Directory.Build.props

Jint.Tests/Runtime/EngineTests.cs, Jint/Native/String/StringInstance.cs, Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs, Jint/Runtime/TypeConverter.cs
=> Fix string indexing detecting string starting with $ as NaN and thus 0

Jint.Benchmark/EngineConstructionBenchmark.cs, Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj, Jint.Tests.Ecma/Jint.Tests.Ecma.csproj, Jint.Tests.Test262/Jint.Tests.Test262.csproj, Jint.Tests.Test262/test/skipped.json, Jint.Tests/Jint.Tests.csproj, Jint.Tests/Parser/JavascriptParserTests.cs, Jint.Tests/Runtime/EngineTests.cs, Jint/Engine.cs, Jint/Jint.csproj, Jint/Native/Function/EvalFunctionInstance.cs, Jint/Native/Function/FunctionConstructor.cs, Jint/Native/Json/JsonParser.cs, Jint/Native/Object/ObjectInstance.cs, Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs, Jint/Runtime/Interpreter/Expressions/BindingPatternAssignmentExpression.cs, Jint/Runtime/Interpreter/Expressions/JintLiteralExpression.cs, Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs, Jint/Runtime/Interpreter/JintFunctionDefinition.cs, Jint/Runtime/Interpreter/Statements/JintScript.cs, Jint/Runtime/Interpreter/Statements/JintStatement.cs, appveyor.yml
* tweak code to comply with new interfaces
* implement object rest
* use net461;netstandard2.0;netstandard2.1 as library target
* update test projects to target net461;netcoreapp3.1
=> Upgrade to Esprima 1.0.1270

Jint.Benchmark/Jint.Benchmark.csproj, Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj, Jint.Tests.Ecma/Jint.Tests.Ecma.csproj, Jint.Tests.Ecma/TestCases/alltests.json, Jint.Tests.Test262/Jint.Tests.Test262.csproj, Jint.Tests.Test262/Language/Statements/ForOfTests.cs, Jint.Tests.Test262/Test262Test.cs, Jint.Tests.Test262/test/skipped.json, Jint.Tests/Jint.Tests.csproj, Jint/Native/Argument/ArgumentsInstance.cs, Jint/Native/Array/ArrayPrototype.cs, Jint/Native/Iterator/IteratorInstance.cs, Jint/Native/Iterator/IteratorProtocol.cs, Jint/Options.cs, Jint/Runtime/Interpreter/Expressions/BindingPatternAssignmentExpression.cs, Jint/Runtime/Interpreter/Statements/JintForOfStatement.cs, Jint/Runtime/Interpreter/Statements/JintForStatement.cs, Jint/Runtime/Interpreter/Statements/JintStatement.cs
* implemented for-of
* some tweaks to destructuring logic and string iteration (astral symbols)
=> ES6 for-of

Jint.Tests/Runtime/ConstTests.cs, Jint/Runtime/Interpreter/JintStatementList.cs
=> Follow the BoundNames spec in BlockDeclarationInstantiation

Jint.Repl/Program.cs, Jint.Tests.Test262/Test262Test.cs, Jint.Tests/Parser/JavascriptParserTests.cs, Jint.Tests/Runtime/Debugger/BreakPointTests.cs, Jint.Tests/Runtime/ErrorTests.cs, Jint/Engine.cs, Jint/Jint.csproj
=> Upgrade Esprima to 2.0.0-beta-1338

Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Interop/ObjectWrapper.cs
=> Support ExpandoObject in EnumerateOwnPropertyKeys

Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Interop/TypeReference.cs
=> Fix exception propagation from .NET constructors

Jint.Tests/Runtime/ExtensionMethods/CustomStringExtensions.cs, Jint.Tests/Runtime/ExtensionMethods/ExtensionMethodsTest.cs, Jint.Tests/Runtime/ExtensionMethods/OverrideStringPrototypeExtensions.cs, Jint/Options.cs, Jint/Runtime/Interop/MethodInfoFunctionInstance.cs
fixes #871 
I dont' know why there a few newlines and removed spaces in the pull request, sorry...
I'll try to find the reason and remove that.
=> Override Protoype Functions

Jint.Tests/Runtime/Domain/Person.cs, Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Interop/ObjectWrapper.cs
=> Implement Equals and GetHashCode for ObjectWrapper

Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Interop/ObjectWrapper.cs
=> Don't match explicit indexer properties when finding accessor

Jint.Tests.Test262/test/built-ins/Map/is-a-constructor.js, Jint.Tests.Test262/test/built-ins/Map/iterator-close-failure-after-set-failure.js, Jint.Tests.Test262/test/built-ins/Map/prototype/Symbol.iterator/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Map/prototype/clear/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Map/prototype/delete/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Map/prototype/entries/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Map/prototype/forEach/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Map/prototype/get/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Map/prototype/has/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Map/prototype/keys/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Map/prototype/set/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Map/prototype/values/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Set/is-a-constructor.js, Jint.Tests.Test262/test/built-ins/Set/prototype/Symbol.iterator/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Set/prototype/add/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Set/prototype/clear/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Set/prototype/delete/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Set/prototype/entries/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Set/prototype/forEach/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Set/prototype/has/not-a-constructor.js, Jint.Tests.Test262/test/built-ins/Set/prototype/values/not-a-constructor.js, Jint.Tests/Runtime/MapTests.cs, Jint.Tests/Runtime/SetTests.cs, Jint/Native/Map/MapConstructor.cs, Jint/Native/Set/SetConstructor.cs
* update Map/Set tests to latest
* manual test case to cover
fixes #894
=> Fix Map and Set call validation

Jint.Tests.Test262/Language/ArgumentsObjectTests.cs, Jint.Tests.Test262/Language/ComputedPropertyNamesTests.cs, Jint.Tests.Test262/Language/Expressions/SuperTests.cs, Jint.Tests.Test262/test/skipped.json, Jint/EsprimaExtensions.cs, Jint/Jint.csproj, Jint/Native/Array/ArrayInstance.cs, Jint/Native/Function/EvalFunctionInstance.cs, Jint/Native/Function/FunctionInstance.cs, Jint/Native/Function/ScriptFunctionInstance.cs, Jint/Native/Object/ObjectInstance.cs, Jint/Native/Proxy/ProxyInstance.cs, Jint/Runtime/Environments/FunctionEnvironmentRecord.cs, Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs
* small tweaks and fixes to make tests pass
=> Enable more tests

Jint.Tests/Runtime/OperatorOverloadingTests.cs, Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs, Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs
=> Allow overloading assignment operators

Jint.Tests/Jint.Tests.csproj, Jint/Runtime/Interop/TypeResolver.cs
=> Ensure consuming works from C# language version 8

Jint.Tests/Runtime/RegExpTests.cs, Jint/Native/RegExp/RegExpPrototype.cs
=> Fix NullReferenceException in RegExp.prototype.source

Jint.Tests/Runtime/FunctionTests.cs, Jint/Native/Function/FunctionInstance.cs, Jint/Runtime/Interpreter/Expressions/JintArrowFunctionExpression.cs
=> Anonymous lambda should have empty function name

Jint.Tests.CommonScripts/SunSpiderTests.cs
=> Run SunSpiderTests("controlflow-recursive.js") only in release mode

Jint.Tests/Runtime/ArrayTests.cs, Jint/Native/Array/ArrayPrototype.cs
=> Array.sort should obey execution constraints

Jint/Native/Array/ArrayInstance.cs, Jint/Native/Array/ArrayPrototype.cs, Jint/Native/Object/ObjectInstance.cs, Jint/Native/TypedArray/IntrinsicTypedArrayPrototype.cs
Pretty much no-brainer as just loops from end instead of start. Passes 202 tests in test262 refresh branch.
https://github.com/tc39/proposal-array-find-from-last
=> Implement array find from last

Jint.Tests.Ecma/TestCases/alltests.json, Jint/Engine.cs, Jint/Native/Argument/ArgumentsInstance.cs, Jint/Native/Error/ErrorConstructor.cs, Jint/Native/Function/EvalFunctionInstance.cs, Jint/Native/Function/FunctionInstance.cs, Jint/Native/Function/FunctionPrototype.cs, Jint/Native/Function/ScriptFunctionInstance.cs, Jint/Native/Function/ThrowTypeError.cs, Jint/Runtime/Descriptors/GetSetPropertyDescriptor.cs, Jint/Runtime/Intrinsics.cs
Fixes validated against test262 branch.
=> Fix some error related issues

Jint/Native/Array/ArrayIteratorPrototype.cs, Jint/Native/Iterator/IteratorPrototype.cs, Jint/Native/Map/MapIteratorPrototype.cs, Jint/Native/Object/ObjectPrototype.cs, Jint/Native/Proxy/ProxyInstance.cs, Jint/Native/RegExp/RegExpStringIteratorPrototype.cs, Jint/Native/RegExp/RegExpStringIteratorPrototypeObject.cs, Jint/Native/Set/SetIteratorPrototype.cs, Jint/Native/String/StringIteratorPrototype.cs, Jint/Native/TypedArray/IntrinsicTypedArrayPrototype.cs, Jint/Runtime/Descriptors/PropertyDescriptor.cs, Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs, Jint/Runtime/Intrinsics.cs
Tests turning green on test262 branch.
=> Fix iterator prototype and Reflect/Proxy issues

Jint.Tests.Ecma/TestCases/alltests.json, Jint/Native/JsBigInt.cs, Jint/Native/RegExp/RegExpConstructor.cs
Latest test suite showed that couple cases were missed.
=> Fix BigInt loose equality

Jint.Tests/Runtime/EngineTests.cs, Jint/Native/JsNumber.cs, Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs
=> Fix integer addition/subtraction overflow

Jint.Benchmark/Jint.Benchmark.csproj, Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj, Jint.Tests.CommonScripts/SunSpiderTests.cs, Jint.Tests.Test262/Jint.Tests.Test262.csproj, Jint.Tests/Jint.Tests.csproj, Jint/Directory.Build.props, Jint/Jint.csproj
Parallelism for the win, runs faster now as all cores can be utilized. Also updating some packages.
=> Change Jint.Tests.CommonScripts run with NUnit

Jint.Tests/Runtime/InteropTests.cs, Jint/Native/Iterator/IteratorInstance.cs
=> Add default iterator prototype for IteratorInstance

Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Interop/ObjectWrapper.cs
=> Allow adding symbol properties to CLR objects

Jint.Tests/Runtime/InteropTests.cs, Jint/Native/Object/ObjectInstance.cs, Jint/Options.cs
=> Support custom CLR object creator for ObjectInstance.ToObject

Jint/Engine.cs
* no-op, but prepares consumers to do the dispose
* made Engine sealed, let's see if there's an outcry
fixes #423
=> Make Engine implement IDisposable

Jint.Tests/Runtime/EngineTests.cs, Jint/Native/Array/ArrayInstance.cs, Jint/Native/JsString.cs, Jint/Native/Object/ObjectInstance.cs
=> Fix GetOwnPropertyKeys canonical array index handling

Jint.Tests/Runtime/InteropTests.cs, Jint/Native/Array/ArrayOperations.cs, Jint/Native/Object/ObjectInstance.cs, Jint/Runtime/Interop/ObjectWrapper.cs
=> Fix smallest index handling against collection under interop

Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Interop/MethodInfoFunctionInstance.cs, Jint/Runtime/TypeConverter.cs
=> Improve null handling in generic parameter resolution logic

Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Interop/DelegateWrapper.cs
=> Fix params array type handling under interop

Jint.Tests/Runtime/EngineTests.cs, Jint/Native/Global/GlobalObject.cs, Jint/Native/WeakMap/WeakMapInstance.cs, Jint/Native/WeakSet/WeakSetInstance.cs, Jint/Runtime/Interop/TypeResolver.cs
* use span
* don't use recursion
* create fast case for regular number input
fixes #1221
=> Improve parseInt logic

Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Interop/TypeReference.cs
=> Add intermediary prototype for TypeReference

Jint.Tests/Runtime/InteropTests.Json.cs, Jint/Native/Json/JsonSerializer.cs, Jint/Options.cs
See discussion https://github.com/sebastienros/jint/discussions/1228
=> Direct C# interop replacing default serializing in JsonSerializer

Jint.Tests/Runtime/EngineLimitTests.cs, Jint.Tests/Runtime/ErrorTests.cs, Jint/Engine.Modules.cs, Jint/Runtime/ExceptionHelper.cs, Jint/Runtime/Interpreter/JintStatementList.cs, Jint/Runtime/Interpreter/Statements/JintSwitchBlock.cs, Jint/Runtime/JavaScriptException.cs
=> Improve error location reporting

Jint.Tests/Runtime/InteropTests.MemberAccess.cs, Jint/Runtime/Interop/TypeReference.cs
=> Include inherited static members in interop member search

Jint.Tests/Runtime/JsValueConversionTests.cs, Jint/Native/Date/DateConstructor.cs, Jint/Native/Date/DateInstance.cs
`new Date()` is probably the most common pattern to build a date, so let's not jump extra hoops for that main case.
=> Optimize new Date()

Jint.Tests.PublicInterface/JavaScriptExceptionTests.cs, Jint/Runtime/JavaScriptException.cs
This is the same as pull request #1259 with requested test added.
=> Restore public access to JavaScriptException ctor

Jint.Benchmark/Jint.Benchmark.csproj, Jint.Benchmark/README.md
* NiL.JS 2.5.1600
* YantraJS.Core 1.2.50
=> Update benchmark results

Jint.Tests.Test262/Test262Harness.settings.json, Jint/Jint.csproj, Jint/Native/Array/ArrayConstructor.cs, Jint/Native/Array/ArrayInstance.cs, Jint/Native/RegExp/RegExpInstance.cs, Jint/Native/RegExp/RegExpPrototype.cs
* https://github.com/tc39/proposal-regexp-match-indices
* new Esprima which handles `d` and `v` flags
=> Implement RegExp match indices

Jint.Tests/Runtime/ErrorTests.cs, Jint/Native/Error/ErrorConstructor.cs
=> Fix error stack handling when last syntax node is not present

Jint.Tests.Test262/Test262Harness.settings.json, Jint.Tests.Test262/Test262Test.cs, Jint.Tests/Runtime/EngineLimitTests.cs, Jint/Native/AsyncFunction/AsyncFunctionConstructor.cs, Jint/Native/AsyncFunction/AsyncFunctionPrototype.cs, Jint/Native/Error/ErrorConstructor.cs, Jint/Native/Function/FunctionConstructor.cs, Jint/Native/Function/FunctionInstance.Dynamic.cs, Jint/Native/Function/FunctionInstance.cs, Jint/Native/Function/ScriptFunctionInstance.cs, Jint/Native/Promise/PromiseConstructor.cs, Jint/Native/Promise/PromiseInstance.cs, Jint/Native/Promise/PromiseOperations.cs, Jint/Runtime/Interpreter/Expressions/JintAwaitExpression.cs, Jint/Runtime/Interpreter/Expressions/JintExpression.cs, Jint/Runtime/Interpreter/Expressions/JintFunctionExpression.cs, Jint/Runtime/Interpreter/Expressions/JintImportExpression.cs, Jint/Runtime/Interpreter/JintFunctionDefinition.cs, Jint/Runtime/Interpreter/JintStatementList.cs, Jint/Runtime/Interpreter/Statements/JintFunctionDeclarationStatement.cs, Jint/Runtime/Intrinsics.cs, Jint/Runtime/JavaScriptException.cs, Jint/Runtime/KnownKeys.cs, Jint/Runtime/PromiseRejectedException.cs
Contains a feature that some people have asked for, some kind of `async` and `await`. Fixed small issues in earlier Promise implementations too. 
**Before**
`Passed: 47738, Skipped: 13720, Total: 61458`
**After**
`Passed: 49859, Skipped: 12480, Total: 62339`
=> Implement async/await

Jint.Tests/Runtime/ArrayTests.cs, Jint/Native/Array/ArrayPrototype.cs, Jint/Runtime/Interpreter/Expressions/JintArrayExpression.cs, Jint/Runtime/Interpreter/Expressions/JintExpression.cs
* construct from array with holes
* subclassable handling for map
=> Fix array issues

Jint.Tests.Test262/Test262Harness.settings.json, Jint.Tests.Test262/Test262Test.cs, Jint/Native/FinalizationRegistry/FinalizationRegistryConstructor.cs, Jint/Native/FinalizationRegistry/FinalizationRegistryInstance.cs, Jint/Native/FinalizationRegistry/FinalizationRegistryPrototype.cs, Jint/Native/Global/GlobalObject.cs, Jint/Runtime/Host.cs, Jint/Runtime/Intrinsics.cs, Jint/Runtime/JavaScriptException.cs, README.md
This is basically the minimalistic implementation. Probably can be improved further if actual `Worker` kind of handling is needed - that would mean refining `Host` handling
=> Implement FinalizationRegistry

Jint.Tests/Runtime/ProxyTests.cs, Jint/Native/Array/ArrayConstructor.cs, Jint/Native/Array/ArrayPrototype.cs, Jint/Native/Object/ObjectConstructor.cs, Jint/Runtime/Descriptors/PropertyDescriptor.cs, Jint/Runtime/TypeConverter.cs
Still some other issues left, but let's do incrementally as this is quite tedious.
=> Fix ToPropertyDescriptor Proxy issues

Jint.Tests/Runtime/DateTests.cs, Jint/Native/Date/DateConstructor.cs, Jint/Native/Date/DateExtensions.cs, Jint/Native/Date/DateInstance.cs, Jint/Native/Date/DatePrototype.cs
=> Fix default date constructor to clip decimal part

Jint.Tests.PublicInterface/RavenApiUsageTests.cs, Jint.Tests/Runtime/InteropTests.cs, Jint/Engine.cs, Jint/Native/BigInt/BigIntPrototype.cs, Jint/Native/JsValue.cs, Jint/Native/Json/JsonSerializer.cs, Jint/Native/Object/ObjectInstance.cs, Jint/Runtime/Interop/ObjectWrapper.cs, Jint/Runtime/Interop/TypeDescriptor.cs
* fix surfaced BigInt ToString handling
fixes #1339
=> Allow deleting dictionary entries via interop

Jint.Tests/Runtime/InteropTests.NewtonsoftJson.cs, Jint/Native/JsNumber.cs
fixes https://github.com/OrchardCMS/OrchardCore/issues/12597
=> Add decimal support under type conversion

Jint.Tests.Test262/Test262Harness.settings.json, Jint.Tests/Runtime/DestructuringTests.cs, Jint.Tests/Runtime/FunctionTests.cs, Jint/HoistingScope.cs, Jint/Runtime/Environments/FunctionEnvironmentRecord.cs, Jint/Runtime/Interpreter/JintFunctionDefinition.cs
* move arguments detection separate AST helper
* fix function length counting
=> Fix some remaining function parameter destructuring issues

Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj, Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj, Jint.Tests.Test262/Jint.Tests.Test262.csproj, Jint.Tests/Jint.Tests.csproj, Jint.Tests/Runtime/InteropTests.TypeReference.cs, Jint.Tests/Runtime/InteropTests.cs, Jint/Options.cs, Jint/Runtime/Interop/TypeReference.cs
=> Allow configuring TypeReference target instance creator

Jint.Tests.PublicInterface/RavenApiUsageTests.cs, Jint/Native/Array/ArrayInstance.cs, Jint/Native/JsArray.cs, Jint/Native/JsDate.cs, Jint/Native/Json/JsonParser.cs, Jint/Native/Json/JsonSerializer.cs, Jint/Native/RegExp/RegExpInstance.cs, Jint/Native/Symbol/GlobalSymbolRegistry.cs, Jint/Runtime/Environments/FunctionEnvironmentRecord.cs, Jint/Runtime/Interop/DefaultObjectConverter.cs, Jint/Runtime/Interpreter/Expressions/JintArrayExpression.cs
* fix file names and missing sealed
* add setter for ArrayInstance
=> Fix JsArray(PropertyDescriptor[]) to initialize prototype

Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Interop/DefaultTypeConverter.cs
Allows using records with positional syntax as parameter.
=> Add support for constructors with default parameters

Jint.Benchmark/Jint.Benchmark.csproj, Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj, Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj, Jint.Tests.Test262/Jint.Tests.Test262.csproj, Jint.Tests.Test262/Test262Harness.settings.json, Jint.Tests/Jint.Tests.csproj, Jint/Jint.csproj
* upgrade testing related libraries
=> Upgrade to Esprima 3.0.0-beta-10

Jint.Tests/Runtime/StringTests.cs, Jint/Native/String/StringPrototype.cs
=> Fix string indexOf for empty string

Jint.Tests/Runtime/ArrayTests.cs, Jint/Native/Array/ArrayInstance.cs
=> Fix ArrayInstance.GetOwnProperties with typed dense array

Jint/Engine.cs, Jint/Native/Array/ArrayIteratorPrototype.cs, Jint/Native/Iterator/IteratorInstance.cs, Jint/Native/Iterator/IteratorResult.cs, Jint/Native/Map/MapIteratorPrototype.cs, Jint/Native/Object/ObjectInstance.cs, Jint/Runtime/Interpreter/Statements/JintForInForOfStatement.cs
* specific iterator for JsArray which is a common case
* generic IEnumerable handler
=> Improve and cleanup iterators a bit

Jint.Tests/Runtime/StringTests.cs, Jint/Runtime/Interpreter/Expressions/JintTaggedTemplateExpression.cs, Jint/Runtime/Interpreter/Expressions/JintTemplateLiteralExpression.cs
* cleanup and small optimization
fixes #1421
=> Fix template literal object to string handling

Jint.Tests/Runtime/InteropTests.MemberAccess.cs, Jint/Engine.cs, Jint/Runtime/Interop/TypeResolver.cs
=> Change TypeResolver cache to be bound to engine instance

.github/workflows/build.yml, .github/workflows/release.yml
https://github.com/dotnet/sdk/pull/29065
=> Use explicit project parameter in dotnet pack

Jint.Tests/Runtime/ArrayTests.cs, Jint/Native/Array/ArrayConstructor.cs
=> Fixes to Array.from behavior against primitive type

Jint.Tests.PublicInterface/ConstructorTests.cs, Jint.Tests/Runtime/AwaitTests.cs, Jint/Runtime/Interpreter/JintFunctionDefinition.cs
=> Fix await propagation against primitive value

Jint.Tests/Runtime/StringTests.cs, Jint/EsprimaExtensions.cs
=> Support template literals as keys

Jint.Tests/Runtime/RegExpTests.cs, Jint/Native/RegExp/RegExpPrototype.cs
=> Fix RegExp.prototype.source double-escape

Jint.Tests/Runtime/InteropTests.cs, Jint/Extensions/ReflectionExtensions.cs, Jint/Runtime/Interop/DefaultTypeConverter.cs
=> Disallow unsafe floating point conversion caching

Jint.Tests/Runtime/FunctionTests.cs, Jint/JsValueExtensions.cs
Add overloads for 1-3 arguments and utilize pooling.
=> Fix ambiguous JsValueExtensions.Call overload

Jint.Tests/Runtime/InteropTests.cs, Jint/Native/JsDate.cs, Jint/Options.cs
=> Support configuring kind of JsDate produced DateTime

Jint/Engine.cs, README.md
=> Add some API documentation and note about thread-safety

Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Interop/DefaultTypeConverter.cs
=> Remove floating point precision loss checks under interop

Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Interop/ClrFunctionInstance.cs
=> Don't call CatchClrExceptions for JavaScriptExceptions

Jint/Runtime/TypeConverter.cs
=> Optimize TypeConverter.ToNumber by using Try overloads

Jint/Engine.cs, Jint/Jint.csproj, Jint/Native/Global/GlobalObject.cs, Jint/Native/String/StringConstructor.cs, Jint/Native/WeakMap/WeakMapInstance.cs, Jint/Native/WeakSet/WeakSetInstance.cs, Jint/Runtime/Interop/TypeResolver.cs, Jint/Runtime/TypeConverter.cs
NET 6.0 build doesn't have all the optimizations as `NETSTANDARD2_1_OR_GREATER` isn't set.
=> Fix conditional compilation checks to account for NET 6.0

Jint.Tests/Jint.Tests.csproj, Jint.Tests/Runtime/InteropTests.SystemTextJson.cs
=> Create a sample for System.Text.Json interop

Jint.Benchmark/EngineComparisonBenchmark.cs, Jint/Engine.Ast.cs, Jint/Engine.cs, Jint/Native/Array/ArrayInstance.cs, Jint/Native/Function/FunctionInstance.cs, Jint/Native/Iterator/IteratorResult.cs, Jint/Native/JsString.cs, Jint/Native/Map/JsMap.cs, Jint/Native/Proxy/JsProxy.cs, Jint/Native/RegExp/JsRegExp.cs, Jint/Native/Set/JsSet.cs, Jint/Native/String/StringInstance.cs, Jint/Runtime/CommonProperties.cs, Jint/Runtime/Environments/EnvironmentRecord.cs, Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs, Jint/Runtime/Interpreter/Expressions/JintIdentifierExpression.cs, Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs, Jint/Runtime/References/Reference.cs
* use faster check when comparing for known properties
=> Support caching of string instances in script preparation

Jint.Tests/Runtime/InteropTests.cs, Jint/Runtime/Descriptors/Specialized/ReflectionDescriptor.cs, Jint/Runtime/Interop/ObjectWrapper.cs, Jint/Runtime/Interop/TypeResolver.cs
=> Refine interop member search with readable/writable requirement

Directory.Build.props, Jint.Tests/Runtime/InteropTests.cs, Jint.sln, Jint/Collections/DictionarySlim.cs, Jint/Collections/StringDictionarySlim.cs, Jint/Jint.csproj, Jint/Options.Extensions.cs, Jint/Options.cs, Jint/Runtime/Debugger/DebuggerStatementHandling.cs
* fix documentation and nullable issues
* enable UseArtifactsOutput
=> Package XML documentation

Jint/Native/Array/ArrayPrototype.cs, Jint/Native/BigInt/BigIntPrototype.cs, Jint/Native/Json/JsonParser.cs, Jint/Native/Json/JsonSerializer.cs, Jint/Native/Number/Dtoa/BignumDtoa.cs, Jint/Native/Number/Dtoa/DtoaBuilder.cs, Jint/Native/Number/Dtoa/DtoaNumberFormatter.cs, Jint/Native/Number/Dtoa/FastDtoa.cs, Jint/Native/Number/NumberPrototype.cs, Jint/Native/RegExp/RegExpPrototype.cs, Jint/Native/String/StringConstructor.cs, Jint/Pooling/ValueStringBuilder.cs, Jint/Runtime/CallStack/JintCallStack.cs, Jint/Runtime/TypeConverter.cs
* make DtoaBuilder ref struct
* simplify JsonSerializer
* tweak default stackalloc sizes
=> Further optimize Dtoa and string building

Jint.Tests.Test262/Test262Harness.settings.json, Jint/JsValueExtensions.cs, Jint/Native/ArrayBuffer/ArrayBufferPrototype.cs, Jint/Native/ArrayBuffer/JsArrayBuffer.cs, Jint/Native/Global/GlobalObject.Properties.cs, Jint/Native/SharedArrayBuffer/JsSharedArrayBuffer.cs, Jint/Native/SharedArrayBuffer/SharedArrayBufferConstructor.cs, Jint/Native/SharedArrayBuffer/SharedArrayBufferPrototype.cs, Jint/Native/String/StringPrototype.cs, Jint/Native/TypedArray/IntrinsicTypedArrayPrototype.cs, Jint/Native/TypedArray/JsTypedArray.cs, Jint/Runtime/Intrinsics.cs, README.md
Pretty much same behavior as with standard `ArrayBuffer` for now, can later decide if we want to utilize `ArrayPool` and how to return the objects then.
=> Implement SharedArrayBuffer

Jint.Tests.PublicInterface/CallStackTests.cs, Jint/Engine.Advanced.cs
=> Add Engine.Advanced.StackTrace to get current stack trace string

Jint.Tests/Runtime/ExtensionMethods/ExtensionMethodsTest.cs, Jint/Native/JsValue.Convertible.cs, Jint/Native/JsValue.cs, Jint/Native/Object/ObjectInstance.cs, Jint/Options.cs
* allow disabling ExpandoObject conversion
fixes #1703
=> Make JsValue implement IConvertible

Directory.Packages.props, Jint.Benchmark/README.md, Jint.Tests/Runtime/EngineLimitTests.cs, Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs, Jint/Runtime/Interpreter/JintStatementList.cs, Jint/Runtime/Interpreter/Statements/JintBlockStatement.cs
* improve assignment fast case checks
=> Add fast case for single statement in a block

Jint/Native/JsNumber.cs, Jint/Runtime/Interop/TypeReference.cs
I only tested dotnet8 and there should be no side effects.
=> Fix Aot use enum

Jint.Tests/Runtime/AsyncTests.cs, Jint/Native/Function/Function.cs, Jint/Native/Function/FunctionConstructor.cs, Jint/Native/Function/FunctionInstance.Dynamic.cs, Jint/Native/Generator/GeneratorKind.cs, Jint/Native/Global/GlobalObject.Properties.cs, Jint/Native/Iterator/IteratorInstance.cs, Jint/Runtime/Interpreter/EvaluationContext.cs, Jint/Runtime/Interpreter/Expressions/JintFunctionExpression.cs, Jint/Runtime/Interpreter/JintFunctionDefinition.cs, Jint/Runtime/Interpreter/JintStatementList.cs, Jint/Runtime/Interpreter/Statements/JintForInForOfStatement.cs
Still keeping `yield` unsupported.
=> Sync WIP generator structures to main

Directory.Packages.props, Jint.Tests.Test262/.config/dotnet-tools.json, Jint.Tests.Test262/Test262Harness.settings.json, Jint.Tests/Runtime/PromiseTests.cs
* use latest commit hash
* minor other package upgrades
=> Upgrade to Test262Harness 1.0.0

Jint.Tests/Runtime/ModuleTests.cs, Jint/Runtime/Modules/ModuleFactory.cs
fixes #1755 
Sorry it took so long to fix - a lot of work.
I hope you accept the pull request.
=> Ensure modules have always source specified

Jint.Tests/Runtime/InteropTests.MemberAccess.cs, Jint/Runtime/Interop/DefaultTypeConverter.cs, Jint/Runtime/Interop/TypeDescriptor.cs
=> Try to initialize interop object members with upper and lower first char

Jint.Tests/Runtime/AsyncTests.cs, Jint/Options.cs, Jint/Runtime/Interop/DefaultObjectConverter.cs
=> Make task to promise wrapping an opt-in experimental feature

Jint/AstExtensions.cs, Jint/Engine.Modules.cs, Jint/Runtime/CallStack/JintCallStack.cs, Jint/Runtime/Interpreter/Expressions/JintExpression.cs, Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs, Jint/Runtime/Interpreter/JintStatementList.cs
Another breaking change in preparation for #1820.
=> Rename EsprimaExtensions to AstExtensions

Jint.Tests.Test262/Test262Harness.settings.json, Jint.Tests/Runtime/TypedArrayInteropTests.cs, Jint/Jint.csproj, Jint/JsValueExtensions.cs, Jint/Native/DataView/DataViewPrototype.cs, Jint/Native/Global/GlobalObject.Properties.cs, Jint/Native/JsArrayBuffer.cs, Jint/Native/Math/MathInstance.cs, Jint/Native/TypedArray/TypedArrayConstructor.Types.cs, Jint/Native/TypedArray/TypedArrayConstructor.cs, Jint/Native/TypedArray/TypedArrayElementType.cs, Jint/Native/TypedArray/TypedArrayValue.cs, Jint/Runtime/Intrinsics.cs, README.md
Only supported on NET 6+ where `Half` is available
=> Add support for Float16Array

Jint.Tests.PublicInterface/InteropTests.SystemTextJson.cs, Jint/Runtime/Interop/DefaultObjectConverter.cs
=> Improve System.Text.Json numeric type conversion under interop

Jint/Runtime/Debugger/DebugScope.cs, Jint/Runtime/Descriptors/Specialized/ClrAccessDescriptor.cs, Jint/Runtime/Environments/DeclarativeEnvironment.cs, Jint/Runtime/Environments/Environment.cs, Jint/Runtime/Environments/GlobalEnvironment.cs, Jint/Runtime/Environments/JintEnvironment.cs, Jint/Runtime/Environments/ModuleEnvironment.cs, Jint/Runtime/Environments/ObjectEnvironment.cs, Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs, Jint/Runtime/Interpreter/Expressions/JintIdentifierExpression.cs, Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs, Jint/Runtime/Interpreter/Expressions/JintUpdateExpression.cs, Jint/Runtime/Interpreter/Statements/JintForStatement.cs
| **Diff**|Method|Prepared|Toolchain|FileName|Mean|Error|Allocated|
|------- |-------|-------|-------|-------|-------:|-------|-------:|
| Old |Run|False|Default|dromaeo-3d-cube|22.222 ms|0.2079 ms|6304.91 KB|
| **New** |	| **False** | **Default** |	| **19.953 ms (-10%)** | **0.2049 ms** | **6304.9 KB (0%)** |
| Old |Run|False|Default|dromaeo-core-eval|4.296 ms|0.0265 ms|327.85 KB|
| **New** |	| **False** | **Default** |	| **3.624 ms (-16%)** | **0.0306 ms** | **327.84 KB (0%)** |
| Old |Run|False|Default|dromaeo-object-array|42.425 ms|0.1915 ms|100367.72 KB|
| **New** |	| **False** | **Default** |	| **41.721 ms (-2%)** | **0.3537 ms** | **100367.76 KB (0%)** |
| Old |Run|False|Default|droma(...)egexp [21]|149.899 ms|1.0581 ms|151325.94 KB|
| **New** |	| **False** | **Default** |	| …
=> Improve environment handling performance and cleanup API

README.md
the demo I modify is not valid,I change this example for jint laset version
=> edit ReadMe.md sample

.github/workflows/build.yml, .github/workflows/pr.yml, .github/workflows/release.yml, Directory.Packages.props, Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj, Jint.Tests/Jint.Tests.csproj, Jint.sln
=> Use global env definitions for GitHub Actions

Jint.Tests/Runtime/BigIntTests.cs, Jint/Native/JsBigInt.cs, Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs, Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs
=> Fix BigInt arithmetic assignment

Jint.Tests/Runtime/Domain/Shape.cs, Jint.Tests/Runtime/InteropTests.cs, Jint/Options.cs, Jint/Runtime/Interop/NamespaceReference.cs
=> Support creating NamespaceReference against empty namespace

Jint.Tests/Jint.Tests.csproj, Jint.Tests/Runtime/ArrayTests.cs, Jint.Tests/Runtime/TypeDescriptorTests.cs, Jint/Native/Array/ArrayInstance.cs
=> Fix ArrayInstance.CopyValues to handle holes correctly

Jint.Tests/Runtime/ClassTests.cs, Jint/Runtime/Interpreter/Expressions/JintPrivateIdentifierExpression.cs
=> Improve invalid class private member access member errors

Jint.Tests.PublicInterface/RavenApiUsageTests.cs, Jint/Engine.cs
=> Fix custom reference resolver argument

Jint.Benchmark/Scripts/dromaeo-object-string-modern.js, Jint.Benchmark/Scripts/dromaeo-object-string.js, Jint/Engine.Ast.cs, Jint/Engine.cs, Jint/Runtime/Interpreter/Statements/JintBlockStatement.cs
* fix benchmark issues between modern and classic in dromaeo-object-string
=> Add support for block statement preparation

Jint.Benchmark/ObjectAccessBenchmark.cs
=> Fix ObjectAccessBenchmark test

Jint.Tests/Runtime/ArrayTests.cs, Jint/Runtime/Interop/ObjectWrapper.Specialized.cs
Fix #2110 
I did my best to build and test locally but please verify. I'm having some trouble running tests on my Ubuntu machine (with dotnet 9), a lot of tests are failing out of the box so it's a bit messy having to dig through pages of messages.
=> Fix calling pop on generic list of value types

Jint.Repl/Program.cs, Jint.Tests/Runtime/TypedArrayInteropTests.cs, Jint/Native/Disposable/AsyncDisposableStackConstructor.cs, Jint/Native/Disposable/AsyncDisposableStackPrototype.cs, Jint/Native/Disposable/DisposableStack.cs, Jint/Native/Disposable/DisposableStackConstructor.cs, Jint/Native/Disposable/DisposableStackPrototype.cs, Jint/Native/Disposable/DisposeCapability.cs, Jint/Native/Global/GlobalObject.Properties.cs, Jint/Native/Iterator/IteratorPrototype.cs, Jint/Native/Object/ObjectInstance.cs, Jint/Native/SuppressedError/SuppressedErrorConstructor.cs, Jint/Native/SuppressedError/SuppressedErrorPrototype.cs, Jint/Native/Symbol/GlobalSymbolRegistry.cs, Jint/Native/Symbol/SymbolConstructor.cs, Jint/Runtime/Intrinsics.cs
* AsyncDisposableStack
* DisposableStack
* SuppressedError
=> Add explicit resource management supporting types
