Jint/Native/JsValue.cs

Bugfix for #139: set +4 field offset to avoid overlapping

FieldOffset fix to avoid TypeLoad exception in partial trust IIS level

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs

**Bug**: Cannot pass single number to the .NET method as params object[] argument.
**Reason**: ArrayConstructor has JS behaviour for array construction: if there is only one argument and it's number, then it's length of array (not an array with one element)
**Solution**: Replace ArrayContructor with low level JS array creation in params resolution resolver method.
_Please update NuGet version with this fix._

bugfix: be able to pass single number as params array

---

Jint/Native/String/StringPrototype.cs

Bug: string.replace using regex and function as paramters #141

Bug: string.replace using regex and function as paramters

---

Jint.Tests/Jint.Tests.csproj
Jint.Tests/Runtime/Domain/ArrayConverterTestClass.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs

Usually i start using Jint with custom ArrayConverter derived from DefaultTypeConverter. What about to add it to the Jint core?
In current Jint this case works _(integer automatically converted to string)_:
public void Method(string args) { }
engine.Execute("a.Method(1)");
But this one doesn't _(array of integers cannot be converted to array of strings)_:
public void Method(string[] args) { }
engine.Execute("a.Method([1,2])");
My Pull Request adds an array converter for interop operations.

feature: CLR array converter

---

Jint/Native/JsValue.cs

Explicit struct layout field offsets removed. 
See #140 for discussion

Make Jint x86 and x64 compliant

---

.editorconfig
.gitignore
Jint/Parser/Ast/WithStatement.cs

All Ast node classes reside in Jint.Parser.Ast namespace, except of WithStatement node.

Changed namespace of WithStatement to Jint.Parser.Ast

---

Jint/Runtime/Interop/DefaultTypeConverter.cs

In DefaultTypeConverter.TryConvert I added an extra check before _knownConversions.TryGetValue to avoid unnecessary locking.

Added extra check before _knownConversions.TryGetValue to avoid lock

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Array/ArrayPrototype.cs

fix array sort method to allow floating point numbers to be returned from the compare function

fix array sort method

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Engine.cs
Jint/Jint.csproj
Jint/Options.cs
Jint/Runtime/Debugger/BreakPoint.cs
Jint/Runtime/Debugger/DebugHandler.cs
Jint/Runtime/Debugger/DebugInformation.cs
Jint/Runtime/Debugger/StepMode.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/EnvironmentRecord.cs
Jint/Runtime/Environments/ObjectEnvironmentRecord.cs
Jint/Runtime/ExpressionIntepreter.cs

As requested in Issue #25, I have implemented a first and basic support for debugging.
I started from fvaneijk implementation, found here:
https://github.com/fvaneijk/jint/tree/addDebugger
Debugging is enabled with a new parameter in Options, called DebugMode.
There are two new events, for being notified of step and breakpoint (Step and Break respectively).
Both events allow to return the behavior for following steps (Into, Over or None)
The events provide a DebugInformation instance, which contains the statement, a simple callstack and dictionaries of local and global variables.
I've written some unit tests for covering most of the use cases:
ShouldBreakWhenBreakpointIsReached
ShouldExecuteStepByStep
ShouldNotBreakTwiceIfSteppingOverBreakpoint
ShouldShowProperDebugInformation …

Add debug support

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/DelegateWrapper.cs

Allow nullable delegate parameters to be excluded from the JS function call

Allow nullable delegate parameters to be excluded

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/TypeReference.cs

When creating an instance of value type without parameters the following error occurs:
No public methods with the specified arguments were found.

Fix a error that occurs when creating an instance of value type without parameters

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Date/DatePrototype.cs

Currently jint isn't honoring timezone rules when converting dates to a string. For example if the local timezone is EST, but the date is in the past or future when daylight savings would be observed jint doesn't account for that.

Date should honor the timezone rules for daylight savings

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Json/JsonInstance.cs

According to [the spec](http://www.ecma-international.org/ecma-262/5.1/#sec-15.12.2), JSON.parse(text) should use ToString(text) to get the string value. The previous implementation would throw an error when JSON.parse was called with a non-string value.

Fix for JSON.parse handling non-string values

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs

System.Convert.ChangeType does not work with Nullable types, so special
handling must be added before the call in DefaultTypeCoverter.cs

Allow setting Nullable properties on POCO instances

---

Jint/Runtime/ExpressionIntepreter.cs

Assign `Cached = true` after caching the value to prevent race condition errors. This is a fix for issue #320

Fix race condition for cached literals

---

Jint/Runtime/Interop/DelegateWrapper.cs

Add the Engine.Function.PrototypeObject prototype to DelegateWrapper so it is populated with standard properties such as `call(...)`, `apply(...)`, and `bind(...)`. This allows for things such as currying of C# functions just as is possible with JS functions, or passing them as callbacks with the parameters already supplied.
My own tests did not reveal any breaking characteristics of this change but if necessary I can write unit tests

Add function prototype to DelegateWrapper

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Engine.cs

Suppose that you've executed the following script and you want to call `obj.getFoo` passing some POCOs.
```js
var obj = {
foo: 5,
getFoo: function (someDotNetObject, someOtherObject) {
var foo = this.foo;
// do something with foo, someDotNetObject and someOtherObject
var result = foo;
return result;
}
};
```
We want to call `getFoo`
```cs
var obj = Engine.GetValue("obj").AsObject();
var getFoo = obj.Get("getFoo");
```
If the type of the passed value was `int`, `double`, `string` or some `ObjectInstance`; we could've simply done this:
```cs
var arguments = new JsValue[] { 3, "bar" };
var result = getFoo.Invoke(obj, arguments);
```
But we want to pass some .NET objects so we have to do this:
```cs
var arguments = new object[] { someDotNetObject, someOtherObject };
var result = …
```

Call object instance methods directly from an object

---

Jint/project.json

`Jint.dll` in the Jint version 2.10 package not signed with strong name.

Sign an Jint version 2.10 with a Strong Name

---

Jint/project.json

Jint version 2.10.1 package is not compatible with older versions of the NuGet Package Manager (for example, version 2.12.0.817), i.e. cannot be used in the Visual Studio 2013. An error occurs when installing this version of Jint:
```
Attempting to resolve dependency 'System.Diagnostics.Contracts (? 4.0.0)'.
The 'System.Diagnostics.Contracts 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.12.0.817'.
```
To resolve this error need to replace `dependencies` section by `frameworkAssemblies` in `net45` target.

Replace `dependencies` section by `frameworkAssemblies` in `net45` target

---

Jint/Native/Json/JsonParser.cs
Jint/Native/Json/JsonSerializer.cs

@sebastienros Please take a look.
JSON.parse and JSON.stringify slow down a lot when handling long strings, #357 
Using StringBuilder.Append improves the performance a lot.
|String.Length|Before(ms) |  After(ms) |
|---|---|---|
|10|0 |0 |
|100|0 |0 |
|1,000|1 |0 |
|10,000|22 |1 |
|100,000|2166 |7 |
|1,000,000|(too long) |74 |
```
namespace ConsoleApp1
{
using Jint;
using System;
using System.Diagnostics;
using System.Linq;
public class Program
{
static void Main(string[] args)
{
var repeatCount = 1;
Parse(repeatCount);
if (args.Length > 0)
{
repeatCount = int.Parse(args[0]);
}
Stopwatch sw = new Stopwatch();
sw.Start();
Parse(repeatCount);
sw.Stop();
Console.WriteLine(repeatCount + " times stringify takes: " + sw.ElapsedMilliseconds + " milliseconds.");
}
private static void Stringify(int …
```

Using StringBuilder to improve perf when handling long strings

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Number/NumberPrototype.cs

If V8 FastDtoa cannot convert a number, the "old" DToA implementation can fail, if the system Jint is running on does not use "." (dot) as separator between integer and fractional part of the number.

Fix bug in number to string conversion.

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/String/StringInstance.cs
Jint/Runtime/StatementInterpreter.cs

The for-in statement on strings should return the list of keys of the string.
However the specification doesn't mention this. To be verified.
Fixes #371

Implementing StringInstance.GetOwnProperties()

---

Jint.Tests/Runtime/InteropTests.cs
Jint.Tests/xunit.runner.json
Jint/Options.cs
Jint/Runtime/Interop/DelegateWrapper.cs

Some users want more options to catch exceptions.
With this PR you need to call `options.CatchClrExceptions()` to trigger the conversion from CLR exceptions to JS errors.
You can also optionally pass a predicate to this method to decide when to catch them or not dynamically, like for instance to filter specific exception types.
/cc @mgentile @wslthree_twitter @danbopes

Catching exceptions optionally

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Global/GlobalObject.cs

ECMAScript specification:
http://www.ecma-international.org/ecma-262/5.1/#sec-B.2.1
escape function is deprecated but supported by browsers and hence, would be good to have Jint support the same.
https://github.com/sebastienros/jint/issues/380

Implemented escape function on global object. 

---

Jint.Tests/Runtime/Domain/Thrower.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Native/JsValue.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs

Enabled use of SetValue is nested Engine creation for Type references to simplify InteropTests.
Fix for issue 393: https://github.com/sebastienros/jint/issues/393

Fix for CLR exceptions inside TypeReference instances not being caught by JS code

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs

Hello,
Jint crashes if used in combination with a mixed type indexed class.
The bug is inside DefaultTypeConverter: it should not crash inside the "TryConvert" method.
Thank you

Fixes Multiple Indexer and DefaultTypeConverter TryConvert

---

Jint.Tests/Runtime/NullPropogation.cs
Jint/Engine.cs
Jint/Options.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/Interop/IReferenceResolver.cs
Jint/Runtime/TypeConverter.cs

See #409 
This handle null reference errors as well as methods calls.

Allow host to handle unknown references

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/TypeReference.cs

This patch introduces support for `instanceof` operator on engine symbols which are created from a `TypeReference`.  Instances constructed from a `TypeReference` should be an instance of that CLR type.
Traditionally, ObjectWrapper instances have no prototype, so FunctionInstance.HasInstance will always throw an error.
Tests included in InteropTests assembly. Fixes #421.

 Implement TypeReference.HasInstance

---

Jint/Directory.Build.props

Dependency on BuildNumber is not documented so we should set up some working defaults. Build on environment where BuildNumber variable is defined should work as before.

Fix build on clean environment

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/String/StringPrototype.cs

Thought I'd have a go at another issue on the list #429 
Let me know what you think :-)

padStart and padEnd #429

---

.gitignore
Jint.Benchmark/EvaluationBenchmark.cs
Jint.Benchmark/Jint.Benchmark.csproj
Jint.Benchmark/Program.cs

While discussing a [performance problem](http://issues.hibernatingrhinos.com/issue/RavenDB-9718) when using RavenDB I also checked some Jint code. There might be possibilities for performance optimizations but there should be solid numbers if changes are made. So I converted the current benchmark project to use [BenchmarkDotNet](http://benchmarkdotnet.org/).
Now we can get better numbers and memory allocations from running the Jurassic vs Jint performance test in GitHub pasteable format by running `dotnet run -c Release` in benchmark project directory: 
``` ini
BenchmarkDotNet=v0.10.11, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.98)
Processor=Intel Core i7-6820HQ CPU 2.70GHz (Skylake), ProcessorCount=8
Frequency=2648437 Hz, Resolution=377.5812 ns, Timer=TSC
.NET …
```

Convert Jint.Benchmark to use BenchmarkDotNet

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/String/StringPrototype.cs

To address the issue of startsWith not currently supported. This is to address #440 which is linked to #429

Missing support for String.prototype.startsWith

---

Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/Function/FunctionConstructor.cs
Jint/Native/Function/FunctionPrototype.cs
Jint/Native/JsValue.cs
Jint/Native/Json/JsonParser.cs
Jint/Native/Number/NumberPrototype.cs
Jint/Native/Object/ObjectConstructor.cs
Jint/Native/RegExp/RegExpPrototype.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs
Jint/Runtime/StatementInterpreter.cs
Jint/Runtime/TypeConverter.cs

Now a separate lookup that is used for integers. Memory usage drops by third when using latest array performance benchmark.
``` ini
BenchmarkDotNet=v0.10.11, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.125)
Processor=Intel Core i7-6820HQ CPU 2.70GHz (Skylake), ProcessorCount=8
Frequency=2648437 Hz, Resolution=377.5812 ns, Timer=TSC
.NET Core SDK=2.1.2
[Host]     : .NET Core 2.0.3 (Framework 4.6.25815.02), 64bit RyuJIT
Job-LPPWMI : .NET Core 2.0.3 (Framework 4.6.25815.02), 64bit RyuJIT
InvocationCount=4  LaunchCount=1  TargetCount=3  
UnrollFactor=4  WarmupCount=3  
```
| Method |  N | ReuseEngine |    Mean |   Error |   StdDev |       Gen 0 |      Gen 1 |      Gen 2 | Allocated |
|------- |--- |------------ |--------:|--------:|---------:|------------:|-----------:|-- …

Cache common int to string conversions

---

Jint/Native/Number/Dtoa/CachePowers.cs
Jint/Native/Number/Dtoa/DiyFp.cs
Jint/Native/Number/Dtoa/DoubleHelper.cs
Jint/Native/Number/Dtoa/FastDtoa.cs
Jint/Native/Number/Dtoa/FastDtoaBuilder.cs
Jint/Native/Number/Dtoa/NumberExtensions.cs

By converting DiyFp to struct we can lower memory traffic by  about 30% with small performance gain. I'm using the array test again here.
I have also internalized the Dtoa bits so that no poor soul takes dependency on them, I believe they are not something that library should offer as part of the API.
/cc @sebastienros @ayende 
| Method |  N | ReuseEngine |    Mean |   Error |   StdDev |       Gen 0 |      Gen 1 |      Gen 2 | Allocated |
|------- |--- |------------ |--------:|--------:|---------:|------------:|-----------:|-----------:|----------:|
|   **Jint** | **20** |       **False** | **4.169 s** | **2.139 s** | **0.1209 s** | **784750.0000** | **40500.0000** | **17500.0000** |   **3.18 GB** |
|   **Jint** | **20** |        **True** | **4.090 s** | **1.327 s** | **0.0750 s** | …

Use struct for DiyFp

---

Jint/Runtime/ExpressionIntepreter.cs

Member expression invocation is on hot path with static object properties and allocates a lot of literals, we can simplify it to work without literal expression evaluation.
|    Method |   N |    Mean |    Error |   StdDev |       Gen 0 |      Gen 1 | Allocated |
|---------- |---- |--------:|---------:|---------:|------------:|-----------:|----------:|
| Benchmark | 500 | 1.094 s | 0.0049 s | 0.0071 s | 243554.1667 | 15075.0000 | 997.15 MB |
|    Method |   N |    Mean |    Error |   StdDev |       Gen 0 |      Gen 1 | Allocated |
|---------- |---- |--------:|---------:|---------:|------------:|-----------:|----------:|
| Benchmark | 500 | 1.081 s | 0.0112 s | 0.0167 s | 202687.5000 | 55312.5000 |  903.2 MB |

Optimize EvaluateMemberExpression when targeting static member

---

Jint/Engine.cs
Jint/Native/Argument/ArgumentsInstance.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Native/JsValue.cs
Jint/Native/Json/JsonParser.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Runtime/Environments/ObjectEnvironmentRecord.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs

Here we get a really nice reduction of allocations and a speed boost by catching all sorts of implicit JsValue allocations. I generally don't like implicit operators but it was quite easy to redirect them to use caching. 
As JsValue is immutable and attached to certain object, we can easily pair them lazily and reuse. Also caching common int, double and char maps.
|    Method |   N |    Mean |    Error |   StdDev |       Gen 0 |      Gen 1 | Allocated |
|---------- |---- |--------:|---------:|---------:|------------:|-----------:|----------:|
| Benchmark | 500 | 1.214 s | 0.0755 s | 0.1083 s | 202687.5000 | 55312.5000 |  903.2 MB |
|    Method |   N |    Mean |    Error |   StdDev |       Gen 0 |      Gen 1 | Allocated |
|---------- |---- …

Cache common JsValue allocations

---

.gitignore
Jint/Engine.cs
Jint/Native/Function/FunctionPrototype.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Native/Number/NumberPrototype.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/Arguments.cs
Jint/Runtime/Completion.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/MruPropertyCache2.cs
Jint/Runtime/StatementInterpreter.cs
Jint/Runtime/TypeConverter.cs

This change add commonly accessed prototype and constructor fields directly to ObjectInstance. Dictionary is initialized if these two fields are not enough to describe the object. On top of memory usage changes so that PR needs to be addressed first.

Make ObjectInstance MruPropertyCache2 dictionary lazy

---

Jint/Engine.cs
Jint/Jint.csproj
Jint/Native/Function/FunctionConstructor.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Native/Json/JsonInstance.cs
Jint/Native/String/StringPrototype.cs
Jint/Native/Symbol/SymbolConstructor.cs
Jint/Native/Symbol/SymbolPrototype.cs
Jint/Options.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs

This time around again trying to reduce memory allocations to give virtual machine some breathing room. Most of the changes should have positive changes all around.
* remove LINQ from hot paths
* use List<T> where possible to get rid of memory allocations when using foreach
* cache empty completions
Next I'm going to tackle generally ObjectInstance and it's memory usage, trying to optimize MruPropertyCache2 etc.
|    Method |   N |    Mean |    Error |   StdDev |       Gen 0 |      Gen 1 | Allocated |
|---------- |---- |--------:|---------:|---------:|------------:|-----------:|----------:|
| Benchmark | 500 | 1.094 s | 0.0049 s | 0.0071 s | 243554.1667 | 15075.0000 | 997.15 MB |
|    Method |   N |    Mean |    Error |   StdDev |       Gen 0 |      Gen 1 | Allocated |
|---------- |---- …

Reduce memory allocations

---

Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj
Jint.Tests.Ecma/Jint.Tests.Ecma.csproj
Jint.Tests/Jint.Tests.csproj
Jint.Tests/Runtime/EngineTests.cs
Jint/Jint.csproj
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/Array/ArrayExecutionContext.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/Global/GlobalObject.cs
Jint/Native/JsValue.cs
Jint/Native/Json/JsonParser.cs
Jint/Native/Object/ObjectConstructor.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/RegExp/RegExpPrototype.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/Descriptors/PropertyDescriptor.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs
Jint/Runtime/MruPropertyCache.cs
Jint/Runtime/MruPropertyCache2.cs

* Made it possible to hint about wanted array size
* Support for dense arrays
* MruPropertyCache is lazy
|             Method |   N |       Mean |     Error |    StdDev |     Gen 0 | Allocated |
|------------------- |---- |-----------:|----------:|----------:|----------:|----------:|
|              Slice | 100 |   2.606 ms | 0.0555 ms | 0.0519 ms |  546.8750 |    2.2 MB |
|             Concat | 100 |   2.758 ms | 0.0231 ms | 0.0205 ms |  593.7500 |   2.38 MB |
|            Unshift | 100 | 107.151 ms | 0.3361 ms | 0.2807 ms | 8250.0000 |  33.16 MB |
|               Push | 100 |  33.993 ms | 0.6668 ms | 0.7134 ms | 4000.0000 |  16.13 MB |
|              Index | 100 |  26.968 ms | 0.0660 ms | 0.0585 ms | 2750.0000 |  11.07 MB |
|                Map | 100 |  12.291 ms | 0.0380 ms | 0.0356 ms …

Optimize array access and add ability to hint array size

---

Jint/Engine.cs
Jint/Native/Array/ArrayExecutionContext.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/JsValue.cs
Jint/Native/Json/JsonParser.cs
Jint/Native/Null.cs
Jint/Native/String/StringExecutionContext.cs
Jint/Native/String/StringInstance.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/TypeConverter.cs

I tracked unnecessary string->JsValue conversions and tried to minimize unneeded allocations. Also found couple shortcuts from hot paths. This time my baseline benchmark was SunSpider.
One particularly nasty surprise code was StringInstance.GetOwnProperty that called TypeConverter.ToInteger(propertyName), this did implicit JsValue conversion always for things like replace,split etc. I overloaded to create direct string support + shortcut when letter is detected at start, no need to trim etc.
I dropped char and string lookup array to first 128 ASCII characters as beyond that the chars are not.. so common.
| Method |                 FileName |       Mean |      Error |     StdDev |        Gen 0 |        Gen 1 |        Gen 2 |  Allocated |
|------- |------------------------- …

Reduce string operations memory allocations

---

Jint.Benchmark/UncacheableExpressionsBenchmark.cs
Jint/Native/JsValue.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/MruPropertyCache2.cs
Jint/Runtime/StatementInterpreter.cs

Now improving performance of my pet peeve UncacheableExpressionsBenchmark.
* use MruPropertyCache2 and common parameter "arguments" as stored field, now dictionary won't be created for common arguments + single extra parameter
* add missing implicit JsValue operators for uint and char, used sub-optimal double path
* simplify often called JsValue Is* As* methods that have unnecessary nesting and logic
UncacheableExpressionsBenchmark execution time went down 22%, Map time went down 37%. 10% reduction in UncacheableExpressionsBenchmark memory usage.
|             Method |   N |      Mean |     Error |    StdDev |     Gen 0 |   Allocated |
|------------------- |---- |----------:|----------:|----------:|----------:|------------:|
|              Slice | 100 |  1.199 ms | 0.0249 ms | 0.0233 ms | …

Optimize DeclarativeEnvironmentRecord

---

Jint.Benchmark/DromaeoBenchmark.cs
Jint.Benchmark/Jint.Benchmark.csproj
Jint.Benchmark/Scripts/dromaeo/dromaeo-3d-cube.js
Jint.Benchmark/Scripts/dromaeo/dromaeo-core-eval.js
Jint.Benchmark/Scripts/dromaeo/dromaeo-object-array.js
Jint.Benchmark/Scripts/dromaeo/dromaeo-object-regexp.js
Jint.Benchmark/Scripts/dromaeo/dromaeo-object-string.js
Jint.Benchmark/Scripts/dromaeo/dromaeo-string-base64.js
Jint/Native/Array/ArrayExecutionContext.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/String/StringPrototype.cs

Probably due to a bad rebase on my part one list allocation was left behind that basically rendered string.split cached list usage moot (last change in this PR). I added dromaeo tests that jsperf blog used and also fixed Array.Join to use StringBuilder instead of concat. 
* String.split should not create new list
* Array.join should use StringBuilder
* add dromaeo benchmarks
| Method |              FileName |        Mean |      Error |     StdDev |        Gen 0 |        Gen 1 |        Gen 2 |     Allocated |
|------- |---------------------- |------------:|-----------:|-----------:|-------------:|-------------:|-------------:|--------------:|
|    **Run** |       **dromaeo-3d-cube** |   **122.02 ms** |   **4.144 ms** |  **0.2342 ms** |    **7750.0000** |     **250.0000** |            **-** …

Fix string.split and array.join performance

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Date/DatePrototype.cs

Hi!
I found that the constructor of *Date* and the method *Date.prototype.setMonth* don't work properly with negative values of *month*.
In this pull request:
* Fixed bug with negative values of *month* in *DatePrototype.MakeDay*;
* Added tests for the constructor of *Date* with out-of-range (both positive and negative) values of *month*, *day*, *hour*, *minute* and *second*.

Fixing DatePrototype.MakeDay

---

Jint/Engine.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Function/FunctionConstructor.cs
Jint/Native/Function/FunctionInstance.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Native/Global/GlobalObject.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/String/StringInstance.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/MruPropertyCache2.cs

* change MruPropertyCache2 to have string key
* remove shared string property checks from ObjectInstance
* check length in array instance
* move prototype and constructor to ScriptFunctionInstance, specialize ObjectInstanceWithConstructor
| **Diff**|Method|FileName|Mean|Gen 0|Gen 1|Gen 2|Allocated|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------:|
| Old |Run|dromaeo-3d-cube|108.23 ms|7500.0000|250.0000|-|31.85 MB|
| **New** |	|	| **106.64 ms (-1%)** | **7375.0000 (-2%)** | **250.0000 (0%)** | **-** | **31.65 MB (-1%)** |
| Old |Run|dromaeo-core-eval|26.65 ms|1718.7500|-|-|6.9 MB|
| **New** |	|	| **25.88 ms (-3%)** | **1718.7500 (0%)** | **-** | **-** | **6.9 MB (0%)** |
| Old |Run|dromaeo-object-array|293.76 ms|45187.5000|2000.0000|1000.0000|186.78 MB|
| **New** |	| …

#451 string comparison related performance improvements

---

Jint/Native/Object/ObjectInstance.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/LexicalEnvironment.cs
Jint/Runtime/Environments/ObjectEnvironmentRecord.cs

* make DeclarativeEnvironmentRecord dictionary lazy
* explicit tail recursion to iteration so that don't need to rely on x64 JIT
| **Diff**|Method|FileName|Mean|Gen 0|Gen 1|Gen 2|Allocated|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------:|
| Old |Run|dromaeo-3d-cube|106.64 ms|7375.0000|250.0000|-|31.65 MB|
| **New** |	|	| **105.62 ms (-1%)** | **7375.0000 (0%)** | **250.0000 (0%)** | **-** | **31.65 MB (0%)** |
| Old |Run|dromaeo-core-eval|25.88 ms|1718.7500|-|-|6.9 MB|
| **New** |	|	| **26.67 ms (+3%)** | **1718.7500 (0%)** | **-** | **-** | **6.9 MB (0%)** |
| Old |Run|dromaeo-object-array|273.48 ms|45125.0000|2062.5000|1000.0000|186.35 MB|
| **New** |	|	| **262.58 ms (-4%)** | **45125.0000 (0%)** | **2062.5000 (0%)** | **1000.0000 (0%)** | **186.35 MB (0%)** |
| …

#451 remove tail recursion and faster environment records

---

Jint/Native/Array/ArrayExecutionContext.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/String/StringExecutionContext.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/MruPropertyCache2.cs

The optimization caused some condition that was hard to debug and find, with reverting back to _set logic we get a working version at least for now.

Revert back to MruPropertyCache2 with _set field

---

Jint.Benchmark/ArrayStressBenchmark.cs
Jint.Benchmark/DromaeoBenchmark.cs
Jint.Benchmark/Program.cs
Jint.Benchmark/StopwatchBenchmark.cs
Jint.Benchmark/SunSpiderBenchmark.cs
Jint/Engine.cs
Jint/Native/Argument/ArgumentsInstance.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/Function/EvalFunctionInstance.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Pooling/ArgumentsInstancePool.cs
Jint/Pooling/CompletionPool.cs
Jint/Pooling/ObjectPool.cs
Jint/Pooling/ReferencePool.cs
Jint/Runtime/Completion.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/EnvironmentRecord.cs
Jint/Runtime/Environments/LexicalEnvironment.cs
Jint/Runtime/Environments/ObjectEnvironmentRecord.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/References/Reference.cs
Jint/Runtime/StatementInterpreter.cs

This PR introduces object pooling for top memory pressure creators: 
* Reference
* Completion 
* ArgumentsInstance
With this change they practically disappear from performance report. The approach is opportunistic/best effort. When we are in code path that no longer needs the deep-acquire object we release it, unfortunately using pattern cannot be used.
| **Diff**|Method|FileName|Mean|Gen 0|Gen 1|Gen 2|Allocated|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------:|
| Old |Run|dromaeo-3d-cube|107.09 ms|7437.5000|250.0000|-|31.67 MB|
| **New** |	|	| **107.96 ms (+1%)** | **1312.5000 (-82%)** | **250.0000 (0%)** | **-** | **7107.59 KB (-78%)** |
| Old |Run|dromaeo-core-eval|25.92 ms|1718.7500|-|-|6.9 MB|
| **New** |	|	| **24.98 ms (-4%)** | **62.5000 (-96%)** | **-** | …

Introduce object pooling

---

Jint/Engine.cs
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/JsValue.cs
Jint/Native/String/StringPrototype.cs
Jint/Options.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/Interop/NamespaceReference.cs
Jint/Runtime/StatementInterpreter.cs

* As `for` is faster for `List`, now using it - `foreach` for normal array is the same speed as for
* RavenDB for one does a lot of conversions for arrays, so optimized array conversion array handling to go as near bare metal as possible, this will also reduce memory usage quite lot as `Arguments.From` was removed from inside the loop that always allocated new array - testing again RavenDB code base gave about roughly 4-5% improvement, memory usage reduction was harder to test

#451 prefer for over foreach when iterating Lists

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/JsString.cs

If you concatenate strings more than once JSString (ConcatenatedString) delivers a wrong value, just the first concatenation works, overwriting ToObject in ConcatenatedString resolves this issue

JsString multiple concatination fails

---

Jint.Benchmark/Jint.Benchmark.csproj
Jint/Engine.cs
Jint/Jint.csproj
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/Function/FunctionInstance.cs
Jint/Native/Function/FunctionPrototype.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Native/Object/ObjectConstructor.cs
Jint/Native/String/StringInstance.cs
Jint/Native/String/StringPrototype.cs
Jint/Pooling/JsValueArrayPool.cs
Jint/Runtime/Arguments.cs
Jint/Runtime/Debugger/DebugHandler.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs
Jint/StrictModeScope.cs

* make StrictModeScope a struct
* prioritize statement branching
* reuse JsValue array instances
* check string length before equality (can save some 20% if less likely to hit)
| **Diff**|Method|FileName|Mean|Gen 0|Gen 1|Gen 2|Allocated|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------:|
| Old |Run|dromaeo-3d-cube|103.35 ms|1312.5000|250.0000|-|7107.59 KB|
| **New** |	|	| **101.68 ms (-2%)** | **1250.0000 (-5%)** | **312.5000 (+25%)** | **-** | **6812.54 KB (-4%)** |
| Old |Run|dromaeo-core-eval|24.70 ms|62.5000|-|-|298.95 KB|
| **New** |	|	| **23.89 ms (-3%)** | **62.5000 (0%)** | **-** | **-** | **298.55 KB (0%)** |
| Old |Run|dromaeo-object-array|259.58 ms|39500.0000|2000.0000|1000.0000|166027.24 KB|
| **New** |	|	| **255.24 ms (-2%)** | **39125.0000 (-1%)** | …

#451 optimize evaluation performance

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Json/JsonInstance.cs
Jint/Native/Json/JsonSerializer.cs

fix for the following issue in JSON serialization.
when two properties of an object are referenced to same object(an empty array) error is thrown.

fix for issue #351

---

Jint/Native/JsString.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/StatementInterpreter.cs
Jint/Runtime/TypeConverter.cs

| **Diff**|Method|N|Mean|Gen 0|Allocated|
|------- |-------|-------|-------:|-------:|-------:|
| Old |Slice|100|512.2 us|161.1328|660.16 KB|
| **New** |	|	| **506.9 us (-1%)** | **161.1328 (0%)** | **660.16 KB (0%)** |
| Old |Concat|100|607.1 us|175.7813|720.31 KB|
| **New** |	|	| **584.0 us (-4%)** | **175.7813 (0%)** | **720.31 KB (0%)** |
| Old |Unshift|100|20,136.0 us|3562.5000|14672.66 KB|
| **New** |	|	| **20,528.9 us (+2%)** | **3562.5000 (0%)** | **14672.66 KB (0%)** |
| Old |Push|100|13,198.6 us|515.6250|2134.38 KB|
| **New** |	|	| **13,058.4 us (-1%)** | **515.6250 (0%)** | **2134.38 KB (0%)** |
| Old |Index|100|12,839.2 us|390.6250|1637.5 KB|
| **New** |	|	| **12,663.2 us (-1%)** | **390.6250 (0%)** | **1637.5 KB (0%)** |
| Old |Map|100|3,683.2 us|765.6250|3151.56 KB|
| …

Tweak hot paths

---

Jint/Native/Date/DateConstructor.cs
Jint/Native/Date/DatePrototype.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/StatementInterpreter.cs

Moved date parsing format array creation out of parsing, can be private static fields.

#451 don't allocate date formats each time dates are being parsed

---

Jint/Native/JsString.cs

Benchmark showed that for non-cacheable string the code path is now approximately 30% faster.

#451 faster code paths for JsString.Create

---

Jint.Benchmark/Properties/AssemblyInfo.cs
Jint/Engine.cs
Jint/Native/Argument/ArgumentsInstance.cs
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/Error/ErrorConstructor.cs
Jint/Native/Function/BindFunctionInstance.cs
Jint/Native/Function/EvalFunctionInstance.cs
Jint/Native/Function/FunctionInstance.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Native/JsString.cs
Jint/Native/JsValue.cs
Jint/Native/Number/NumberPrototype.cs
Jint/Native/Object/ObjectConstructor.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/String/StringPrototype.cs
Jint/Options.cs
Jint/Pooling/ObjectPool.cs
Jint/Runtime/Debugger/BreakPoint.cs
Jint/Runtime/Descriptors/PropertyDescriptor.cs
Jint/Runtime/Environments/Binding.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/ExpressionIntepreter.cs
Jint/Runtime/Interop/TypeReference.cs
Jint/Runtime/MruPropertyCache2.cs
Jint/Runtime/References/Reference.cs
Jint/Runtime/StatementInterpreter.cs
Jint/Runtime/TypeConverter.cs

All kinds of optimizations.
* inline when JIT doesn't do it
* ObjectInstance direct backing field of Dictionary works better,  DeclarativeExecutionContext still benefits from MPC2
* Mostly used net471 target to detect bad inlining, but probably benefits .NET Core and Full Framework better
| **Diff**|Method|N|Mean|Gen 0|Allocated|
|------- |-------|-------|-------:|-------:|-------:|
| Old |Slice|100|444.1 us|161.1328|660.16 KB|
| **New** |	|	| **419.5 us (-6%)** | **161.1328 (0%)** | **660.16 KB (0%)** |
| Old |Concat|100|478.3 us|175.7813|720.31 KB|
| **New** |	|	| **474.5 us (-1%)** | **175.7813 (0%)** | **720.31 KB (0%)** |
| Old |Unshift|100|17,875.9 us|3562.5000|14672.66 KB|
| **New** |	|	| **18,321.2 us (+2%)** | **3562.5000 (0%)** | **14672.66 KB (0%)** |
| Old |Push|100|10,700.9 …

Optimize declarative environment record handling for functions

---

Jint/Native/Boolean/BooleanConstructor.cs
Jint/Native/JsBoolean.cs
Jint/Native/JsString.cs
Jint/Native/Number/NumberConstructor.cs
Jint/Native/Number/NumberInstance.cs
Jint/Native/Number/NumberPrototype.cs
Jint/Native/Object/ObjectConstructor.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/String/StringConstructor.cs
Jint/Native/String/StringInstance.cs
Jint/Native/String/StringPrototype.cs
Jint/Native/Symbol/SymbolConstructor.cs
Jint/Runtime/ExpressionIntepreter.cs

* fast path for common object expression transformation from properties to new object
* some conversion tweaks for common cases
* constructors for JsValues that are aleady resolved, no need to create them again
| **Diff**|Method|N|Mean|Gen 0|Gen 1|Allocated|
|------- |-------|-------|-------:|-------:|-------:|-------:|
| Old |Benchmark|500|296.8 ms|36812.5000|125.0000|147.43 MB|
| **New** |	|	| **278.6 ms (-6%)** | **33750.0000 (-8%)** | **-** | **135.01 MB (-8%)** |

Optimize object expressions and type conversions

---

Jint.Tests.Ecma/EcmaTest.cs

By splitting to separate classes by chapter, the unit test runner can run each test class in parallel this helps when running tests to check against regressions when you have say, a 16 core machine.

Split EcmaTest by chapters to allow parallel execution

---

Jint.Tests/Runtime/EngineTests.cs

This matches the fact that JS date.toString uses CultureInfo.InvariantCulture.

Use invariant culture in date format tests

---

Jint/Directory.Build.props

Standard SourceLink support to allow stepping through code in Visual Studio.

Add SourceLink support

---

Jint/Engine.cs
Jint/Runtime/Environments/ObjectEnvironmentRecord.cs
Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintExpression.cs
Jint/Runtime/Interpreter/Expressions/JintIdentifierExpression.cs
Jint/Runtime/Interpreter/Expressions/JintLiteralExpression.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs
Jint/Runtime/Interpreter/Expressions/JintThisExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUpdateExpression.cs
Jint/Runtime/Interpreter/Statements/JintStatement.cs
Jint/Runtime/Interpreter/Statements/JintVariableDeclaration.cs
Jint/Runtime/TypeConverter.cs

Small cleanup and more smarts to variable statement handling. Gave a nice perf boost.
| **Diff**|Method|N|Mean|Gen 0/1k Op|Gen 1/1k Op|Gen 2/1k Op|Allocated Memory/Op|
|------- |-------|-------|-------:|-------:|-------:|-------:|-------|
| Old |Slice|100|367.6 us|172.3633|-|-|707.81 KB|
| **New** |	|	| **361.2 us (-2%)** | **172.8516 (0%)** | **-** | **-** | **709.38 KB (0%)** |
| Old |Concat|100|477.7 us|188.4766|-|-|773.44 KB|
| **New** |	|	| **486.3 us (+2%)** | **188.9648 (0%)** | **-** | **-** | **775 KB (0%)** |
| Old |Unshift|100|18,520.8 us|3593.7500|-|-|14829.69 KB|
| **New** |	|	| **17,421.3 us (-6%)** | **3593.7500 (0%)** | **-** | **-** | **14837.5 KB (0%)** |
| Old |Push|100|10,193.7 us|390.6250|-|-|1626.56 KB|
| **New** |	|	| **8,688.8 us (-15%)** | **390.6250 (0%)** | …

Variable statement optimization

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs

RavenDB folks found problem with caching logic, let's revert it and test coverage for the case. Maybe we can refine caching rule later on.
http://issues.hibernatingrhinos.com/issue/RavenDB-12333#focus=streamItem-67-32940-0-0

Revert too eager script expression based caching

---

Jint.Tests.Ecma/TestCases/alltests.json
Jint.Tests.Test262/StatementTests.cs
Jint.Tests.Test262/Test262Test.cs
Jint.Tests.Test262/test/skipped.json
Jint.Tests/Runtime/EngineTests.cs
Jint/Engine.cs
Jint/Native/Function/EvalFunctionInstance.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/ObjectEnvironmentRecord.cs
Jint/Runtime/ExceptionHelper.cs
Jint/Runtime/Interpreter/Statements/JintForInStatement.cs
Jint/Runtime/Interpreter/Statements/JintForStatement.cs

While investigating some RavenDB trouble found out:
* out reference error can be missing the actual name that was tried to be referenced
* some for semantics have changed in the latest compliance suite, namely what is returned on break
Added related tests from 262 suite.

Improve for loops, improve reported reference errors

---

Jint.Tests/Runtime/EngineTests.cs
Jint.Tests/Runtime/Scripts/dromaeo-string-base64.js
Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs

A regression sneaked in at one point, tracked it down and added the base64 encoding test to protect from reappearance.

Fix regression in StrictlyEqual

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs
Jint/Runtime/Interop/TypeReference.cs
Jint/Runtime/TypeConverter.cs

* fixes #244 
* now params handling is done per method, only if necessary, original arguments should be used when matching against non-params methods

More intelligent method resolution

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/DelegateWrapper.cs
appveyor.yml

Fixes bug where delegates generated from expressions contain a closure as their first argument, causing mapping of parameters to fail.

Fixes delegates created from expressions.

---

Jint.Tests/Runtime/Converters/EnumsToStringConverter.cs
Jint.Tests/Runtime/Converters/NegateBoolConverter.cs
Jint/Native/JsValue.cs
Jint/Runtime/Interop/IObjectConverter.cs

I had a need to create an ObjectConverter which called JsValue.FromObject inside it, but I had no reference to the current engine so I extended the TryConvert method to pass in the current engine.

Added engine parameter to IObjectConverter.TryConvert for context

---

Jint.Tests/Runtime/Domain/A.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs
Jint/Runtime/Interop/TypeReference.cs
Jint/Runtime/TypeConverter.cs

Hi jint devs,
as mentioned on gitter, I was looking for a way to interop with C# methods that make use of default values.  After some hints from @sebastienros, I implemented this behaviour myself: Default Values should now be fully supported, including a unit test.
Even if it works, I am not totally happy, especially with the `JsValue.FromObject()` part. What is the best way to convert/cast the default value? Or is this maybe not the best place for the code?

added full support for interop with methods that have default values

---

Jint/Native/Math/MathInstance.cs

System.Random isn't thread-safe. When multi-threaded sharing instance, Random.Next() will always returns zero.

make Random() thread safety

---

Jint/Options.cs
Jint/Runtime/Descriptors/Specialized/FieldInfoDescriptor.cs
Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs
Jint/Runtime/Descriptors/Specialized/PropertyInfoDescriptor.cs

I have a number of very complex objects which I'd like to make available to some design people so they can write various expressions (in JS, but they don't need to know that, it'll look like third-grade maths to them) to be used in our system's business logic. I don't want them accidentally using a = instead of == and messing up the entire system's state. I could create a read-only wrapper around the objects, but that'd take a whole lot of unnecessary effort to implement. Instead, I've added an option to disallow writing to CLR objects from JS code. I think this is likely to be something other people will also run into.

Add CLR write allowed option to engine

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Runtime/Descriptors/PropertyDescriptor.cs

This is basically same as changing runtime's string.Empty, hilarity ensues.

Don't allow changes to shared Undefined property descriptor

---

Jint.Repl/Program.cs

This PR adds and enables loading scripts in the REPL app via a new `load` function that takes a single argument that's the path of the script file to load and execute.

Add 'load(...)' for REPL

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Json/JsonParser.cs

Fixes https://github.com/sebastienros/jint/issues/614

Catch block doesn't catch error thrown by JSON.parse

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Extensions/JavascriptExtensions.cs
Jint/Extensions/ReflectionExtensions.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs

As I mentioned in https://github.com/sebastienros/jint/issues/635#issuecomment-512963364 I cannot assign an anonymous object `{}` to a typed object. This can be very annoying if you want to have 'friendly scripting support' and its more idiomatic in JS as well.
You can now assign an anonymous object to a typed property/field of a given object:
```cs
public void ShouldParseAnonymousToTypeObject(){
var obj = new Wrapper();
var engine = new Engine().SetValue("x", obj);
}
private class Wrapper
{
public Testificate Test { get; set; }
}
private class Testificate
{
public string Name { get; set; }
public Func<int, int, int> Init { get; set; }
}
```
```js
x.test = {
name: 'Testificate',
init (a, b) {
return a + b
}
}
```
See `EngineTests.ShouldParseAnonymousToTypeObject` for the full test.

[WIP] Added support for anonymous objects.

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Engine.cs

This pr fixes a regression of #625  which has made the clr type converter readonly.

allow overriding default clr type converter

---

Jint.Tests/Parser/JavascriptParserTests.cs
Jint/Jint.csproj

Jint had reference to esprima 1.0.0-beta-1186 which was causing IndexOutOfRangeException exception while parsing invalid code:
`new JavaScriptParser("....").ParseProgram();`
After updating reference to  1.0.0-beta-1202, it now throws ParserException which is expected.
I've also added tests for this case.
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Esprima.Scanner.ScanPunctuator() in C:\projects\esprima-dotnet\src\Esprima\Scanner.cs:line 696
>    at Esprima.Scanner.Lex() in C:\projects\esprima-dotnet\src\Esprima\Scanner.cs:line 1699
>    at Esprima.JavaScriptParser.NextToken() in C:\projects\esprima-dotnet\src\Esprima\JavascriptParser.cs:line 259
>    at Esprima.JavaScriptParser.ParsePrimaryExpression() in …

Updated esprima-dotnet reference

---

Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs

Don't use Esprima's AST to cache call expression data

---

Jint.Benchmark/Jint.Benchmark.csproj
Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj
Jint.Tests.Ecma/Jint.Tests.Ecma.csproj
Jint.Tests.Test262/Jint.Tests.Test262.csproj
Jint.Tests/Jint.Tests.csproj
Jint.Tests/Runtime/DateTests.cs
Jint/Native/Date/DateConstructor.cs
Jint/Native/Date/DateInstance.cs
Jint/Native/Date/DatePrototype.cs
Jint/Runtime/ExceptionHelper.cs
appveyor.yml

Running on .NET Core 3 also revealed and issue with date handling. When doubles were used to represent hours, minutes etc it could cause formatting to produce -0 for zero values (format string {0:00}). Fixed this by using int where logical, this has added benefit of guiding JsNumber creation to go to fast path of Create(int) which can do fast array lookups.

Switch to Visual Studio 2019 and .NET Core 3 test runner

---

Jint.Tests/Runtime/ObjectInstanceTests.cs
Jint/Collections/StringDictionarySlim.cs

This was fun to track down. StringDictionarySlim's enumerator was returning deleted items when item that was deleted had first bucket index. This was actually [fixed in CoreFX Labs version](https://github.com/dotnet/corefxlab/commit/f89ccaed1b1a3010517b1f6acb2eb6c273a950bd#diff-893b48d84bbc70491b37c328779f675e) some time ago, we just didn't have the fix incorporated.
Fixes #670

Fix StringDictionarySlim enumeration after first item delete

---

Jint.Tests.CommonScripts/SunSpiderTests.cs
Jint/Engine.cs
Jint/Extensions/JavascriptExtensions.cs
Jint/Jint.csproj
Jint/JsValueExtensions.cs
Jint/Key.cs
Jint/Native/Argument/ArgumentsInstance.cs
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/Boolean/BooleanPrototype.cs
Jint/Native/Date/DatePrototype.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Native/JsNumber.cs
Jint/Native/JsValue.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/LexicalEnvironment.cs
Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs
Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs
Jint/Runtime/Interpreter/Expressions/JintConstantExpression.cs
Jint/Runtime/Interpreter/Expressions/JintExpression.cs
Jint/Runtime/Interpreter/Expressions/JintLiteralExpression.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUnaryExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUpdateExpression.cs
Jint/Runtime/Interpreter/Statements/JintForInStatement.cs
Jint/Runtime/References/Reference.cs
Jint/Runtime/TypeConverter.cs

Here I'm trying out using separate known flag to safe integers. When we know it's a safe integer, we can skip both floating point arithmetic and use faster lookups for results. Consumers still see the exposed `Types` but internally we handle with `InternalTypes` which also has `Integer`.

Separate InternalTypes to allow integer operation optimizations

---

Jint/Runtime/JavaScriptException.cs
Jint/Runtime/JintException.cs
Jint/Runtime/MemoryLimitExceededException.cs
Jint/Runtime/RangeErrorException.cs
Jint/Runtime/RecursionDepthOverflowException.cs
Jint/Runtime/StatementsCountOverflowException.cs
Jint/Runtime/TypeErrorException.cs

Share common base class for exceptions

---

Jint.Tests/Runtime/StringTests.cs
Jint/Native/JsString.cs
Jint/Native/JsValue.cs
Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs
Jint/Runtime/Interpreter/Statements/JintVariableDeclaration.cs

When assigning ConcatenatedString to variable, we need to ensure a proper copy is being made.

Ensure string immutability on assignment

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Runtime/Environments/Binding.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/LexicalEnvironment.cs

- FunctionWasCalled is not used anymore but kept for future reference. It detects if a method is called to release an arguments array to the pull.
- The last binding memoization has been removed.

Removing some optimizations to prepare for refactoring

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Runtime/ExceptionHelper.cs
Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs

Fix possible NRE in CallStackElement construction

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Engine.cs
Jint/Runtime/Interpreter/Expressions/JintLiteralExpression.cs

When string was indexed with non-integer value, the logic incorrectly expected that the target would be the prototype member (like 'indexOf'). Now checking that indexing is done correctly. Also tweaked hex literals to be pre-calculated as integers.
fixes #710

Fix array indexing with hex literal

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs

Summary:
- added test for nullable enum and struct assignment
- fix nullable enum assignment
- microoptimizations in DefaultTypeConverter (I am not sure about its benefits)
Also #153 and #157 are not reproducible anymore.

Fix assigning to Nullable Enum 

---

Jint.Tests/Runtime/Domain/FloatIndexer.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/TypeConverter.cs

Don't throw when CLR indexer not found

---

Jint.Tests/Runtime/Domain/FloatIndexer.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/JsValue.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Options.cs
Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/TypeConverter.cs

* when we see object implementing ICollection or read-only like interface it should be safe to access as array like
* should not assign indexers which are invalid for usage (property is string and indexer uses int)
* assign Array.prototype to array-like objects allowing filter etc, only used when object doesn't have anything suitable itself

Ability to set Array.prototype as prototype for array-like object wrappers

---

Jint.Tests/Runtime/ErrorTests.cs
Jint/EsprimaExtensions.cs
Jint/Runtime/JavaScriptException.cs

The combination of CLR interop and call stack building could lead to infinite recursion. Now using a version that doesn't rely on engine when building the stack.
fixes #719

Fix infinite recursion possibility in call stack string building

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/ObjectWrapper.cs

We don't make missing Count of Length an error condition. It's best effort basis to make and ObjectWrapper array-like.
fixes #725

Only mark array-like if Count or Length present

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs

We should let inner exception of `TargetInvocationException `to flow through. Still we can check `ArgumentOutOfRangeException` to ensure undefined is returned from invalid indexing, like our beloved JS does.
fixes #652

Propagate interop exceptions from IndexDescriptor

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Extensions/ReflectionExtensions.cs

Currently it is only possible to pass a dictionary only directly as a method parameter, but not if it is wrapped in an object.

Support passing a dictionary inside an object

---

Jint/Collections/HybridDictionary.cs
Jint/JsValueExtensions.cs
Jint/Native/Global/GlobalObject.cs
Jint/Native/JsValue.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/String/StringInstance.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/EnvironmentRecord.cs
Jint/Runtime/Environments/FunctionEnvironmentRecord.cs
Jint/Runtime/Environments/GlobalEnvironmentRecord.cs
Jint/Runtime/Environments/LexicalEnvironment.cs
Jint/Runtime/Environments/ObjectEnvironmentRecord.cs
Jint/Runtime/Interpreter/Expressions/BindingPatternAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintArrayExpression.cs
Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs
Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs
Jint/Runtime/Interpreter/Expressions/JintExpression.cs
Jint/Runtime/Interpreter/Expressions/JintIdentifierExpression.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs
Jint/Runtime/Interpreter/Expressions/JintNewExpression.cs
Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUpdateExpression.cs
Jint/Runtime/Interpreter/Statements/JintForStatement.cs
Jint/Runtime/JavaScriptException.cs
Jint/Runtime/TypeConverter.cs

Paying some debt from let/const, let see what low-hanging fruit we can find.

Optimize global identifier access a bit and reduce allocations

---

Jint.Tests/Runtime/ArrayTests.cs
Jint/Native/Array/ArrayInstance.cs

EnsureCapacity can throw if called against sparse mode array

---

Jint.Tests.Ecma/TestCases/alltests.json
Jint.Tests.Test262/BuiltIns/FunctionTests.cs
Jint.Tests.Test262/Test262Test.cs
Jint.Tests.Test262/test/skipped.json
Jint.Tests/Runtime/ErrorTests.cs
Jint/Engine.cs
Jint/Native/Argument/ArgumentsInstance.cs
Jint/Native/Function/ArrowFunctionInstance.cs
Jint/Native/Function/BindFunctionInstance.cs
Jint/Native/Function/EvalFunctionInstance.cs
Jint/Native/Function/FunctionConstructor.cs
Jint/Native/Function/FunctionInstance.cs
Jint/Native/Function/FunctionPrototype.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Native/Function/ThrowTypeError.cs
Jint/Native/JsValue.cs
Jint/Native/Object/ObjectConstructor.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/Proxy/ProxyInstance.cs
Jint/Native/Reflect/ReflectInstance.cs
Jint/Runtime/Arguments.cs
Jint/Runtime/Descriptors/Specialized/GetSetPropertyDescriptor.cs
Jint/Runtime/Interop/ClrFunctionInstance.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs
Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUnaryExpression.cs
Jint/Runtime/TypeConverter.cs

Enable `built-ins\Function` tests and fix related issues found. This should also improve reported error messages to be more in line with V8 (and actually understandable).
Otherwise clean and tidy, but I spent way to many evenings without resolution trying to decipher what is happening with:
```
let g = { [ { a(){} }.a ](){ } }["a(){}"];
assertToStringOrNativeFunction(g, "[ { a(){} }.a ](){ }");
```
So built-ins/Function/prototype/toString/method-computed-property-name.js will be ignored until someone brighter will solve that one... I would argue that this might be somewhat an edge case for regular use.

Enable function tests

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Native/Iterator/IteratorInstance.cs
Jint/Native/JsValue.cs
Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs
Jint/Runtime/Descriptors/Specialized/PropertyInfoDescriptor.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs
Jint/Runtime/KnownKeys.cs

Object wrapper didn't support getting an iterator which is key part to some JS functionality. Added iterator with logic that for me at least makes sense - for dictionaries only get keys and for "standard" objects use public fields and properties.
fixes #748

Support object wrapper iterator

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/ObjectWrapper.cs

* refactored earlier PR's property traversal as helper method
* now using same property iteration for getOwnProperteis and getOwnPropertyKeys
* fixed possible issue of listing properties twice if they have been accessed via indexer before
* JSON.stringify now produces expected result
fixes #298
fixes #164

Harmonize property iteration for ObjectWrapper

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Engine.cs
Jint/Options.cs

* engine instance - options - pair  is provided as overload for engine construction
* added shorthand to add converter just with generic parameter
* remove options.DiscardGlobal, it doesn't make much sense and it isn't that expensive to create the global object, a lot of things rely on that anyway
fixes #310
fixes #655

Provide engine instance when customizing options

---

Jint.Tests/Runtime/Domain/HiddenMembers.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Engine.cs
Jint/Options.cs
Jint/Runtime/Interop/ClrPropertyDescriptorFactoriesKey.cs
Jint/Runtime/Interop/ObjectWrapper.cs

Open to discussion. It might be better to refactor the internal type and dictionary to expose them directly.

Provide a way to override interop members

---

Jint.Tests/Runtime/Domain/JsUuid.cs
Jint.Tests/Runtime/Domain/UuidConstructor.cs
Jint.Tests/Runtime/Domain/UuidConverter.cs
Jint.Tests/Runtime/Domain/UuidInstance.cs
Jint.Tests/Runtime/Domain/UuidPrototype.cs
Jint.Tests/Runtime/UuidTests.cs
Jint/Native/Function/FunctionInstance.cs

* add protected constructor to `FunctionInstance`
* add custom uuid type as test
closes: #753

Add protected function instance constructor

---

Jint.Tests/Runtime/ArrayTests.cs
Jint/Native/Array/ArrayInstance.cs

Check if length has been initialized in ArrayInstance.GetLength

---

Jint.Tests/Runtime/DateTests.cs
Jint/Native/Date/DatePrototype.cs

fixes #763
`IsFinite` in spec also considers `NaN`, which is not handled currently, event thought the spec for [Date.prototype.toJSON](https://tc39.es/ecma262/#sec-date.prototype.tojson) says so.

Fix Date's NaN JSON.stringify

---

Jint.Tests/Runtime/ConstTests.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Native/Function/ArrowFunctionInstance.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs

Don't use BlockStatement to model function body

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Engine.cs
Jint/Options.cs

Being able to reuse options instances, and also create custom extension methods on `Options` that can alter the engine state.

Adding constructor with existing options

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Constraints/CancellationConstraint.cs
Jint/Runtime/ExceptionHelper.cs
Jint/Runtime/ExecutionCanceledException.cs

Currently the `CancellationConstraint` is throwing an exception of type `StatementsCountOverflowException` (same as in the `MaxStatements` constraint). This implementation makes it more difficult to error handling and find their causes.
In this PR, I replaced a exception of type `StatementsCountOverflowException` by an exception of type `ExecutionCanceledException`.

Use a more specific exception in the `CancellationConstraint` class

---

Jint.Tests/Runtime/Domain/Company.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/ObjectWrapper.cs

Avoid choosing property `Item` when it's an indexer until really needed.
fixes #642

Prefer indexing and custom properties over indexer property

---

Jint.Benchmark/Jint.Benchmark.csproj
Jint.Repl/Jint.Repl.csproj
Jint/Directory.Build.props
appveyor.yml

Less size for published package, debug support for debuggers. Also set the license expression instead of the obsolete URL. Update netcoreapp3.0 to netcoreapp3.1.
Just noticed that Esprima is BSD-3 and Jint is BSD-2, intentional?

Publish symbol package

---

Jint.Tests/Runtime/Domain/IntegerIndexer.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs

Fix indexer value conversion

---

Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj
Jint.Tests.Ecma/Jint.Tests.Ecma.csproj
Jint.Tests.Test262/Jint.Tests.Test262.csproj
Jint.Tests/Jint.Tests.csproj
Jint.Tests/Runtime/InteropTests.cs
Jint/Jint.csproj
Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs
Jint/Runtime/Interop/ObjectWrapper.cs

* we can always ignore Symbol properties for CLR objects, they don't exist
* `InvalidOperationException` is something like the `ArgumentOutOfRangeException` and `IndexOutOfRangeException` which we already ignore
fixes #795

Improve error handling for JToken property access

---

Jint.Tests/Runtime/EngineTests.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Engine.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/JsValue.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Options.cs
Jint/Runtime/Descriptors/Specialized/FieldInfoDescriptor.cs
Jint/Runtime/Descriptors/Specialized/GetSetPropertyDescriptor.cs
Jint/Runtime/Descriptors/Specialized/IndexDescriptor.cs
Jint/Runtime/Descriptors/Specialized/PropertyInfoDescriptor.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs

* protect `ClrTypeConverter` from changing during engine lifetime, should set via options
* make specialized property handlers internal, they're already sealed so let's not expose too much
* improve `TryFindIndexer` to account directly for `IList` and short-circuit there for indexer when parameter is convertible to number
* improve performance by detecting integer array indexer access
fixes #797

Fix indexing JArray / faster IList indexing

---

appveyor.yml

The symbols didn't get published with the last release as the appveyor configuration was modified for the wrong branch 🤦

Publish symbols on rel/3.0-beta

---

Jint.Tests/Runtime/ArrayTests.cs
Jint/Native/Array/ArrayOperations.cs
Jint/Native/Array/ArrayPrototype.cs

Implementing stable sort

---

Jint.Tests/Runtime/ExtensionMethods/CustomStringExtensions.cs
Jint.Tests/Runtime/ExtensionMethods/ExtensionMethodsTest.cs
Jint/Runtime/Interop/MethodDescriptor.cs

As mentioned in #814 Generic Methods will now be last in order.
Prevents invoking the Generic Method instead of the Non-Generic Method of same name, if the Generic Method is declared before.
fixes #814

Prioritize Non-Generic methods

---

Jint.Tests.Test262/BuiltIns/JSONTests.cs
Jint/Native/Json/JsonInstance.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Native/Object/ObjectInstance.cs

Use same naming and logic flow as in spec.
fixes #818

Fix JSON serialization logic to adhere to latest specification

---

Jint.Tests/Runtime/FunctionTests.cs
Jint/Native/Function/ArrowFunctionInstance.cs
Jint/Native/Proxy/ProxyConstructor.cs

[immer](https://github.com/immerjs/immer) does not work without this fix.
As far as I understand from [the spec](https://tc39.es/ecma262/#sec-proxy.revocable), the revoke method should not depend on `this` value. 
Added a test which throws an exception without this fix.
Edit: I found another little bug which prevented defining properties on arrow functions. It was a small fix so adding it to this PR. I encountered this error while trying some packages with Webpack 5. 
For example, this works in browsers while it throws `Type Error: null` in Jint:
```
var a = () => null
Object.defineProperty(a, 'hello', { enumerable: true, get: () => 'world' })
console.assert(a.hello === 'world')
```

Allow calling Proxy revoke method without this context

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Json/JsonParser.cs

Initializing line number always to 1 as Esprima expects line numbers to start from 1.
fixes #823

Fix JSON parser line number initialization

---

Jint.Tests.Test262/BuiltIns/AnnexB/EscapeTests.cs
Jint.Tests.Test262/BuiltIns/AnnexB/UnescapeTests.cs
Jint.Tests/Runtime/GlobalTests.cs
Jint/Native/Global/GlobalObject.cs

Fix unescape at end of string

---

Jint.Tests.Test262/Test262Test.cs
Jint.Tests/Runtime/EngineTests.cs
Jint/Engine.cs
Jint/Runtime/CallStack/JintCallStack.cs

Recursive calls were not working when stack recording is active. Before this was not an issue when the test case was running without recursion limits and thus the stack collection was off. Now it's always on and surfaced the problem. Now only resetting state if we know that engine has exited cleanly from earlier call.
fixes #835

Gracefully handle recursive engine invocations

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/Reflection/DynamicObjectAccessor.cs
Jint/Runtime/Interop/Reflection/ReflectionAccessor.cs

Basic support for accessing DynamicObject. Basically expected to have string keys and JS primitive values are converted to CLR types, otherwise DynamicObject is responsible for the conversion. 
Fixes #838

Basic support for DynamicObject

---

Jint.Tests/Runtime/Domain/Person.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Engine.cs
Jint/Native/JsValue.cs

I couldn't find a reason why we would want to convert `Type` instances to `TypeReference` instances unless it's explicit need for type construction (`importNamespace`, explicit `TypeReference.Create`). With this change can now read values like `a.GetType().FullName`, earlier it was hidden as `TypeRefereence` which doesn't expose much. Old behavior can still be achieved by engine type mappers / object converters.
The README shows correct ways to achieve this:
```
and then to assign local namespaces the same way System does it for you, use importNamespace
jint> var Foo = importNamespace('Foo');
jint> var bar = new Foo.Bar();
jint> log(bar.ToString());
adding a specific CLR type reference can be done like this
engine.SetValue("TheType", TypeReference.CreateTypeReference(engine, …
```

Should not wrap Type instances as TypeReference by default

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs

Removed the void returning block in the delegate handling in function arguments.
This allows expressions like:
**list.Sum(x => x.cost)**
To be correctly passed through to .NET. Before the change it would say that no matching function found.

Allow delegates to return values from .NET

---

Jint.Tests/Runtime/CallStackTests.cs
Jint/Runtime/Interpreter/Statements/JintTryStatement.cs

As mentioned in #852, callstack fails to unwind after catching an exception. Not quite sure where this should be handled. Included two tests, one just showing (by way of nested calls) that it's the entire callstack that fails to unwind - it's not just off by 1.

Tests of CallStack unwinding after caught exception (and quick patch)

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/ObjectWrapper.cs

Fixes #856 
Just moved the part which checks for DynamicObject after checking for Declared Members.
Extended the Test "CanAccessDynamicObject" to also access Declared Members.
Hopefully this is helpfull and not just nonsense...

Allow access to declared Members on DynamicObject

---

Jint.Tests/Runtime/ExtensionMethods/CustomStringExtensions.cs
Jint.Tests/Runtime/ExtensionMethods/ExtensionMethodsTest.cs
Jint/Options.cs

Don't override existing prototype functions with extension methods

---

Jint.Tests.Test262/Jint.Tests.Test262.csproj
Jint.Tests/Runtime/CallStackTests.cs
Jint.Tests/Runtime/Debugger/DebugHandlerTests.cs
Jint.Tests/Runtime/FunctionTests.cs
Jint/Engine.cs
Jint/EsprimaExtensions.cs
Jint/HoistingScope.cs
Jint/Native/Function/FunctionConstructor.cs
Jint/Runtime/Debugger/DebugScope.cs
Jint/Runtime/Debugger/DebugScopes.cs
Jint/Runtime/Environments/LexicalEnvironment.cs
Jint/Runtime/Interpreter/JintStatementList.cs
Jint/Runtime/Interpreter/Statements/JintBlockStatement.cs
Jint/Runtime/Interpreter/Statements/JintSwitchBlock.cs

Fix block-scoped function registrations

---

Jint.Tests/Runtime/ExtensionMethods/ExtensionMethodsTest.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/Reflection/ExtensionMethodCache.cs

Fix detecting extension method when there are none

---

Jint/Runtime/Interop/DefaultTypeConverter.cs

1.Compared with the previous scheme, more delegate types are now supported.
2.Shorter implementation.
3.There are still some unforeseen errors unhandled, such as ChangeType may not supported, or ref struct type.

Support converting js function into any delegate.

---

Jint.Tests/Runtime/ErrorTests.cs
Jint.Tests/Runtime/ObjectInstanceTests.cs
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/Boolean/BooleanConstructor.cs
Jint/Native/Date/DateConstructor.cs
Jint/Native/Date/DatePrototype.cs
Jint/Native/Error/ErrorConstructor.cs
Jint/Native/Function/FunctionInstance.cs
Jint/Native/String/StringConstructor.cs
Jint/Native/Symbol/SymbolPrototype.cs

* fix `OrdinaryCreateFromConstructor` cases mentioned in spec
* fix error constructor names
fixes #873

Fix missing NewTarget handling for basic types

---

Jint.Tests/Runtime/FunctionTests.cs
Jint/Engine.cs
Jint/Native/JsValue.cs
Jint/Native/String/StringPrototype.cs

Had to move the spec's Invoke logic to Engine, as we need it's services for object conversion. There are quite a lot of public Invoke capabilities, need to remove some of them at some point I guess..
/cc @twop
fixes #882

Fix Invoke logic and object coercion

---

Jint.Tests.Test262/Language/Expressions/InstanceOfTests.cs
Jint.Tests/Runtime/ArrayTests.cs
Jint/Native/Function/BindFunctionInstance.cs
Jint/Native/Function/FunctionInstance.cs
Jint/Native/Function/FunctionPrototype.cs
Jint/Native/JsValue.cs
Jint/Runtime/Interop/TypeReference.cs
Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs

Added tests cases, went trough logic and aligned with spec. The original test case didn't fail in dev either though...
fixes #874

Fix instanceof logic to comply with specification

---

.gitignore
Jint.Tests/Runtime/MethodAmbiguityTests.cs
Jint.Tests/Runtime/OperatorOverloadingTests.cs
Jint/Extensions/ReflectionExtensions.cs
Jint/Options.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs
Jint/Runtime/Interop/MethodDescriptor.cs
Jint/Runtime/Interop/TypeReference.cs
Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUnaryExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUpdateExpression.cs
Jint/Runtime/TypeConverter.cs

Normally, Ecmascript does not allow operator overloading and [the specs](https://tc39.es/ecma262/#sec-addition-operator-plus) are pretty clear on how to handle operators. But since we are running on C#, we may as well use operators that are defined on the C# side. So I added an option for that. The option is off by default.
Binary operators will try to find a C# side overloaded operator first and use it. If it cannot find, will fall back to Ecmascript behavior. (I forgot to do it for unary so the PR is draft for now. Will do asap.)
Also, when this option is turned on, the default type converter will try to find implicit/explicit cast operator and use it as a last resort.

Implement Operator Overloading

---

Jint.Tests/Runtime/ExtensionMethods/ExtensionMethodsTest.cs
Jint/Runtime/Interop/Reflection/ExtensionMethodCache.cs

I tried to implement this in an effort to improve interop capabilities. I thought it would be easy since Jint supports extension methods now. But the problem is, Linq extension methods are generic, and they work with type inference. It is hard (often impossible) to infer types in Javascript, and there are many issues it creates with covariance, contravariance, generic type constraints, and some other stuff. So, a true Linq compatibility is hard. But I did some improvements that make Linq and other generic extension methods partially work.
Related issue #304

Improve generic extension methods and Linq interop

---

Jint.Benchmark/EngineConstructionBenchmark.cs
Jint.Repl/Program.cs
Jint.Tests.Test262/Test262Test.cs
Jint.Tests/Runtime/ArrayTests.cs
Jint.Tests/Runtime/DateTests.cs
Jint.Tests/Runtime/EngineTests.cs
Jint.Tests/Runtime/ErrorTests.cs
Jint.Tests/Runtime/ExtensionMethods/ExtensionMethodsTest.cs
Jint.Tests/Runtime/FunctionTests.cs
Jint.Tests/Runtime/GlobalTests.cs
Jint.Tests/Runtime/InteropTests.cs
Jint.Tests/Runtime/JsonTests.cs
Jint.Tests/Runtime/NumberTests.cs
Jint.Tests/Runtime/ObjectInstanceTests.cs
Jint.Tests/Runtime/PromiseTests.cs
Jint.Tests/Runtime/RegExpTests.cs
Jint.Tests/Runtime/SamplesTests.cs
Jint.Tests/Runtime/StringTests.cs
Jint.Tests/Runtime/UuidTests.cs
Jint/Engine.cs
Jint/Runtime/Debugger/BreakPointCollection.cs
README.md

Code gets more succinct as chaining is no longer needed to get result.  Keeping the GetCompletionValue with Obsolete attribute, maybe someone will yell.

Introduce Engine.Evaluate

---

Jint.Tests/Runtime/ErrorTests.cs
Jint/Native/Error/ErrorConstructor.cs

Some libraries can do things like `Error().stack` to get the current callstack. I did an implementation that is working but somewhat hacky maybe (using `engine.GetLastSyntaxNode()`). 
It does not give the exactly same string as in V8 or other engines but afaik there is no spec that says what string to return. Only WIP spec is this: https://github.com/tc39/proposal-error-stacks

Implement Error stack property

---

Jint.Tests.Ecma/EcmaTest.cs
Jint.Tests.Test262/SingleTest.cs
Jint.Tests.Test262/Test262Test.cs

We are parsing some scripts over and over again through thousands of test cases, let's parse them only once. From realms branch originally.

Parse scripts only once while testing

---

Jint.Tests/Runtime/InteropTests.cs
Jint.Tests/Runtime/PromiseTests.cs
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/Json/JsonParser.cs
Jint/Native/Object/ObjectConstructor.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/Promise/PromiseConstructor.cs
Jint/Native/Proxy/ProxyInstance.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/Interop/TypeDescriptor.cs

Using direct array create to bypass possible CLR conversion logic, fixes #908 .

Fix Promise.all behavior under interop

---

Jint.Tests.Test262/BuiltIns/ArrayTests.cs
Jint.Tests.Test262/BuiltIns/MapTests.cs
Jint.Tests.Test262/BuiltIns/RegExpTests.cs
Jint.Tests.Test262/BuiltIns/SetTests.cs
Jint.Tests.Test262/test/skipped.json
Jint/Native/Iterator/IteratorConstructor.cs
Jint/Native/Iterator/IteratorInstance.cs
Jint/Native/Map/MapInstance.cs
Jint/Native/Set/SetInstance.cs

* cleanup map and set method names and prototypes

Add iterator prototype tests

---

Jint.Tests.Test262/Test262Test.cs
Jint.Tests/Runtime/RegExpTests.cs
Jint/Native/RegExp/RegExpConstructor.cs

Sometimes Esprima will return null Regex. That means parsing did not fail, but the Regex is incompatible with C#.
With this PR, Jint will not fail during the parsing when such a Regex is received. It will only fail when that Regex is actually used. This way the user can handle the error, and also error can be avoided if that Regex is not used at all. 
See also: sebastienros/esprima-dotnet#173
Keeping this as draft until Esprima PR is merged and released. (Test will fail without the new Esprima)

Do not throw error immediately when receiving null Regex from Esprima 

---

Jint.Tests/Jint.Tests.csproj
Jint.Tests/Runtime/InteropTests.cs
Jint/Collections/ObjectTraverseStack.cs
Jint/Native/Iterator/IteratorInstance.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Native/Object/ObjectInstance.cs

Check cyclic references when evaluating ToObject

---

Jint.Tests/Runtime/OperatorOverloadingTests.cs
Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUnaryExpression.cs

When you have operator overloading enabled the operands of almost all binary and unary expression are evaluated multiple times. This PR should fix it but it's marked as draft because it was suggested to add some tests to test against it.
The problem is easily verifiable like this:
```
var engine = new Engine(cfg => { cfg.AllowOperatorOverloading(); });
engine.SetValue("Log", (Action<string>) (s => Console.Out.WriteLine(s)));
engine.Execute("const test = () => { Log('Example'); return 1; }; test() + 1; ");
```
This should only print a single `Example` line, but instead prints two.

Fix double evaluation when Operator Overloading is enabled

---

Jint.Tests/Jint.Tests.csproj
Jint.Tests/Runtime/Domain/HiddenMembers.cs
Jint.Tests/Runtime/InteropTests.MemberAccess.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Engine.cs
Jint/Options.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/Reflection/IndexerAccessor.cs
Jint/Runtime/Interop/TypeReference.cs
Jint/Runtime/Interop/TypeResolver.cs

Setting a filter allows to reuse all resolution logic and wrapping and on top of that just filter with `MemberInfo`.  Now also caching resolution per engine as options are per engine.
Also adding custom property name comparer.
fixes #275
fixes #342

Introduce TypeResolver with member filter and name comparer

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Function/EvalFunctionInstance.cs
Jint/Native/Function/FunctionConstructor.cs

Related to #598
Fixes weren't applied to Eval and Function Ctor before. 
Edit after tests: `Tolerant = true` breaks other tests. Do you know what may be a better solution?

Fix eval and function constructor failing for object literals with __proto__ prop

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Options.cs
Jint/Runtime/Interop/Reflection/MethodAccessor.cs

Gitter discussion here: https://gitter.im/sebastienros/jint?at=6143e1ecfd7409696e1612ad
Additionally, I run into a case where if you use a class method once, it registers as a enumerable property onto that object. Included fix for that as well.

Fix extension and class methods being enumerated

---

Jint/Engine.cs
Jint/EsprimaExtensions.cs
Jint/Native/Function/FunctionConstructor.cs
Jint/Native/Function/FunctionInstance.cs
Jint/Runtime/Interpreter/Expressions/JintFunctionExpression.cs
Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs
Jint/Runtime/Interpreter/Expressions/JintSequenceExpression.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs
Jint/Runtime/Interpreter/JintStatementList.cs
Jint/Runtime/Interpreter/Statements/JintBlockStatement.cs
Jint/Runtime/Interpreter/Statements/JintSwitchBlock.cs

Cleanup and ensure that we use `JintFunctionDefinition` whenever possible, it caches and learns about the functions so it should be the one to use.

Ensure to use same JintFunctionDefinition instance when possible

---

Jint.Tests/Runtime/ErrorTests.cs
Jint.Tests/Runtime/TestClasses/HelloWorld.cs
Jint/Runtime/ExceptionHelper.cs

Use ExceptionDispatchInfo to capture the original stacktrace in ThrowMeaningfulException
fixes #963

Capture original exception stacktrace in ThrowMeaningfulException

---

Jint.Tests/Runtime/Domain/Company.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Native/Array/ArrayIteratorPrototype.cs
Jint/Native/JsValue.cs
Jint/Native/Map/MapIteratorPrototype.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/TypeDescriptor.cs
Jint/Runtime/Interpreter/Statements/JintForInForOfStatement.cs

* array-like when list or array should iterate values (like Set)
* dictionary-likes should iterate keys and values (like Map)
* IEnumerable behaves like custom Iterable added to regular JS object (enumerates values as-is)
* any other object type is unsupported like in normal JS (like basic objects { "A": 1 })

Fix iteration in interop

---

Jint.Tests/Runtime/InteropTests.cs
Jint.Tests/Runtime/TypedArrayInteropTests.cs
Jint/JsValueExtensions.cs
Jint/Native/ArrayBuffer/ArrayBufferInstance.cs
Jint/Native/JsValue.cs
Jint/Native/TypedArray/TypedArrayInstance.cs

* moved `Is` and `As` helpers to extensions methods
* added `Is` and `As` helpers for each supported typed array type

Add typed array helpers for IsArray and AsArray

---

Jint.Tests/Runtime/Domain/CustomNamed.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/TypeReference.cs
Jint/Runtime/Interop/TypeResolver.cs

While investigating AngleSharp integration, found out they want to expose members with custom names, like `IsSelected` should be exposed as `selected`. Created configuration point to return all the names for given member.

Allow controlling exposed names for interop members

---

Jint.Tests/Runtime/Domain/HiddenMembers.cs
Jint.Tests/Runtime/InteropTests.MemberAccess.cs
Jint/Options.Extensions.cs
Jint/Options.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs
Jint/Runtime/Interop/Reflection/IndexerAccessor.cs
Jint/Runtime/Interop/TypeReference.cs
Jint/Runtime/Interop/TypeResolver.cs
Jint/Runtime/Interpreter/EvaluationContext.cs

Seems that this trips people often enough that we shouldn't allow `GetType` by default. Created separate property to control so that overwritten member filter won't cause us trouble, GetType will always by filtered based on configuration.
fixes #993

Prevent GetType and System.Reflection namespace under interop by default

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/TypeDescriptor.cs

Fix ExpandoObject serialization

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/TypeDescriptor.cs

Generic string-keyed dictionary indexing under interop

---

Jint.Tests/Runtime/InteropTests.Dynamic.cs
Jint.Tests/Runtime/InteropTests.NewtonsoftJson.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Native/JsString.cs
Jint/Native/Json/JsonSerializer.cs

This fixes `JSON.stringify` for wrapped concrete lists, but not for enumerables as it's not that straightforward to enumerate anything passed in.
* split InteropTests a bit
* cleanup JsonSerializer a bit
fixes #1005

Fix JSON.stringify for Lists

---

Jint.Tests/Runtime/Domain/ArrayConverterTestClass.cs
Jint.Tests/Runtime/InteropTests.NewtonsoftJson.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/TypeDescriptor.cs

* https://github.com/sebastienros/jint/issues/1005#issuecomment-968517060
* improves property traversal of JObject fixing serialization
* still requires custom JTokenConverter in order to map Newtonsoft primitives to correct JS primitives, we just don't know how to handle them otherwise

Improve stringify for JObject

---

Jint.Tests/Runtime/InteropTests.NewtonsoftJson.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs

Realized I missed couple cases, added test coverage and cleaned code a bit. Will merge on green build.
Funnily this also improved earlier test case no longer to need to have ObjectWrapper against NSJON date instance.

Add IConvertible handling for DateTime and empty/dbnull

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/Reflection/ReflectionAccessor.cs

We let them bubble as-is in other parts of reflection so let's do the same by default in `ReflectionAccessor`, until there's an counter example where it should't. Doesn't break any known test case at least.
fixes #903

Let exceptions bubble from ReflectionAccessor

---

Jint.Tests/Runtime/Domain/OverLoading.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/TypeConverter.cs

#1035 
First time contributing here. It felt appropriate to follow and reuse the existing Enum resolution/overloading code and tests.
Also, I added an extra check in the existing Enum resolution code `paramType.GetEnumUnderlyingType() == typeof(int)` because `Enum.IsDefined` would throw if `paramType.GetEnumUnderlyingType()` is not an int (as in the case of an overloaded function with an uint enum param).

added int vs float diff for function overloads

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Native/Proxy/ProxyInstance.cs

Issues:
* function-valued properties should be excluded entirely from JSON, not serialized as objects
* proxies incorrectly treated as callable
Changes:
* Remove extraneous early exit case (JsonSerializer line 175) which diverges from the algorithm in the spec (https://tc39.es/ecma262/#sec-serializejsonproperty). This appears to correct the serialization of function-valued properties, but unmasks another issue where ProxyInstance is mistakenly treated as callable even when target is not
* Change "value is ICallbable" test to "value.IsCallable" so that serialization of ProxyInstance is handled correctly (according to the spec proxies are callable only if the target is callable - https://tc39.es/ecma262/#sec-proxycreate)
* Add test to verify serialization of function-valued properties

Fix JSON-serialization issues (function-valued properties)

---

Jint.Tests/Runtime/EngineTests.cs
Jint.Tests/Runtime/JsonTests.cs
Jint/Native/Json/JsonParser.cs

Issues:
* JsonParser sometimes throws JavaScriptException (SyntaxError) and sometimes throws ParserException; should be consistent and always throw one or the other.
* A script that calls JSON.parse(input) should always see a SyntaxError in the case of syntactically invalid input.
* SyntaxError messages should clearly indicate that the error is in JSON data, and indicate the position within the input string.
* SyntaxError messages should not include the entire input string in the message, as it may be arbitrarily long.
Changes:
* Route all exceptions through a common ThrowError(...) method that always throws a SyntaxError
* Clean-up content of error messages and include position of the error. Unfortunately the parser does not track line number accurately, so position is rendered as a …

Fix JsonParser error behavior

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Engine.cs
Jint/Runtime/Interpreter/Expressions/JintUnaryExpression.cs

Normal tests didn't show this problem because engine was set manually to strict or non-strict mode, not based on script value.

Fix script-level strict mode handling

---

Jint/Native/Function/BindFunctionInstance.cs
Jint/Native/Function/FunctionInstance.cs
Jint/Native/Function/FunctionPrototype.cs
Jint/Native/Object/ObjectInstance.cs

From [spec](https://tc39.es/ecma262/#sec-bound-function-exotic-objects):
> Bound function exotic objects do not have the internal slots of ECMAScript function objects listed in Table 34. Instead they have the internal slots listed in Table 35, in addition to [[Prototype]] and [[Extensible]].

Bound function should not inherit from FunctionInstance

---

Jint/Engine.cs
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/BigInt/BigIntPrototype.cs
Jint/Native/JsValue.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Native/Math/MathInstance.cs
Jint/Native/Proxy/ProxyInstance.cs
Jint/Native/RegExp/RegExpPrototype.cs
Jint/Runtime/TypeConverter.cs

Fixes from test262 harness branch, now conforming better to spec.

Fix issues related to JSON, Math, RegExp and Proxy

---

Jint.Tests/Runtime/NullPropagation.cs
Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs

In `EvaluateCall`, we shouldn't short circuit if we detected that the value is null and the nullable reference returned true, we still need to call to the callable

Allowing to use nullable propagation on callables again. Fixed #1041

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Native/Function/ClassDefinition.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/TypeReference.cs

I'm probably opening a can of worms here.
fixes #1048

Allow JS class to extend CLR type

---

Jint.Tests/Runtime/ArrayTests.cs
Jint.Tests/Runtime/ConstTests.cs
Jint.Tests/Runtime/FunctionTests.cs
Jint.Tests/Runtime/InteropTests.MemberAccess.cs
Jint.Tests/Runtime/MethodAmbiguityTests.cs
Jint.Tests/Runtime/StringTests.cs
Jint/Engine.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Runtime/Descriptors/Specialized/ReflectionDescriptor.cs
Jint/Runtime/Interop/Reflection/IndexerAccessor.cs
Jint/Runtime/Interop/Reflection/ReflectionAccessor.cs
Jint/Runtime/Interop/TypeDescriptor.cs
Jint/Runtime/Interpreter/Expressions/BindingPatternAssignmentExpression.cs
README.md

I am not sure about the Dictionary accessor. It now uses `TryGetValue` instead of using `Item` and expecting it to throw error when a key is missing. That makes more sense to me logically. But there is this case:
https://github.com/sebastienros/jint/compare/main...KurtGokhan:interop-fixes?expand=1#diff-6f0fbc1958b9b5e571672e8b8c8795a77ac611e89ee8bf7fbe31d2d1eb476942R145
I am not sure if the result should be `undefined` or `0` here.

Various Interop fixes

---

Jint.Tests/Runtime/FunctionTests.cs
Jint/Native/Function/FunctionInstance.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Native/Object/ObjectInstance.cs

The last fixes I did were not ideal. Same function would resolve to different reference, and bound functions would not work. Also `Call` utility is a more proper way to solve this now I think.

Improve function interop

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Date/DateConstructor.cs

Moved the following formats from DefaultFormats to SecondaryFormats:
"yyyy-MM-ddTHH:mm:ss.FFF",
"yyyy-MM-ddTHH:mm:ss",
"yyyy-MM-ddTHH:mm",
Test updates:
ShouldParseAsUtc:
[InlineData("1970-01-01T00:00Z")]
[InlineData("1970-01-01T00:00:00Z")]
[InlineData("1970-01-01T00:00:00.000Z")]
ShouldParseAsLocalTime:
[InlineData("1970-01-01T00:00")]
[InlineData("1970-01-01T00:00:00")]
[InlineData("1970-01-01T00:00:00.000")]
fixes #1077

Date.parse should default to local time

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs
Jint/Runtime/TypeConverter.cs

After fixing #1094 I felt that we should actually always allow implicit/explicit operators for conversion. I've adapted code to prefer `ChangeType` and if it doesn't succeed we can still always try operator overloading, which has semantically the same goal as supporting `IConvertible`. So removing checks whether operator overloading is allowed when doing interop, it's already behind allow interop flag anyway.
Thoughts @sebastienros @KurtGokhan ?

Always allow operator overloaded conversion

---

Jint.Tests.Test262/Language/Expressions/TypeOfTests.cs
Jint.Tests/Runtime/EngineTests.cs
Jint.Tests/Runtime/ModuleTests.cs
Jint/Engine.cs
Jint/EsprimaExtensions.cs
Jint/HoistingScope.cs
Jint/Runtime/Environments/JintEnvironment.cs
Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintIdentifierExpression.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUpdateExpression.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs
Jint/Runtime/Interpreter/Statements/JintClassDeclarationStatement.cs
Jint/Runtime/Modules/JsModule.cs

* fix class declaration hoisting (to actually make it hoist)
* fix `typeof` evaluating value (getter) when only reference should be retrieved, has perf benefit too
* marking now failing module tests as skipped, need to be addressed in #1102
/cc @christianrondeau

Fix class declaration hoisting and typeof double-evaluation

---

Jint.Tests/Runtime/GenericMethodTests.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs
Jint/Runtime/TypeConverter.cs

add support for generic methods

Add support for generic methods under interop

---

Jint.Tests.Test262/State.cs
Jint.Tests.Test262/Test262Harness.settings.json
Jint.Tests.Test262/Test262Test.cs
Jint.Tests.Test262/TestHarness.cs
Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Date/DateConstructor.cs
Jint/Native/Date/DateInstance.cs
Jint/Native/Date/DatePrototype.cs

Already reviewed in test branch, bringing as only containing date-related fixes.

Date related fixes and improvements

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/Reflection/ConstantValueAccessor.cs
Jint/Runtime/Interop/Reflection/IndexerAccessor.cs
Jint/Runtime/Interop/Reflection/MethodAccessor.cs
Jint/Runtime/Interop/Reflection/ReflectionAccessor.cs
Jint/Runtime/Interop/TypeReference.cs

Improve dictionary based CLR interop

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs
Jint/Runtime/TypeConverter.cs

Improve method scoring logic between double and float

---

Jint/Native/Array/ArrayOperations.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/Object/ObjectInstance.cs

This was introduced by #1053 where `ArrayOperations` started to call slower `Set` which was not directly accessing indexes. Returned old behavior and tweaked two call sites where it's not safe to do fast access. Added TODO comment for future for trying to improve things by tracking whether given array instance is truly simple (only data descriptors and array prototype chain unmodified).

Fix array performance regression

---

Jint.Tests.Test262/Test262Harness.settings.json
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayOperations.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/ArrayBuffer/ArrayBufferInstance.cs
Jint/Native/Object/ObjectChangeFlags.cs
Jint/Native/Object/ObjectConstructor.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/Object/ObjectPrototype.cs
Jint/Native/String/StringPrototype.cs
Jint/Native/TypedArray/IntrinsicTypedArrayPrototype.cs
Jint/Native/TypedArray/TypedArrayConstructor.cs
Jint/Native/TypedArray/TypedArrayInstance.cs
Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs

Adding support for `__proto__` as they introduced test cases which depend on it. Not endorsed feature but basically every runtime supports its.
Implemented checks when producing array operations handler that checks if array instance chain is uncontaminated and can successfully use the fast path, otherwise choose slower object property based. There are examples where JS gets injected with something like `Object.defineProperty(Object.prototype, "0", some_descriptor_which_has_setter_that_mutates_length)`, so basically catching those rare occasions and switching to slow mode (full property setters instead of fast array index set inside array).
Some other minor tweaks.

Update test262 to latest and fix issues

---

Jint.Tests.Test262/Test262Harness.settings.json
Jint/JsValueExtensions.cs
Jint/Native/RegExp/RegExpPrototype.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/TypeConverter.cs
README.md

Quite straightforward, had to ignore one test case because has partly named groups usage on regex.

Implement String.prototype.replaceAll

---

Jint/Engine.cs
Jint/Native/Function/FunctionInstance.cs
Jint/Runtime/ScriptRecord.cs

Small prep work as this is needed for example for `import.meta`.

Add ScriptOrModule to FunctionInstance

---

Jint.Tests/Runtime/JsonTests.cs
Jint/Native/Json/JsonSerializer.cs

* fix indentation bug in JsonSerializer
* add regression test

Fix JSON indentation

---

Jint.Tests/Runtime/JsonTests.cs
Jint/Native/Json/JsonParser.cs

Currently `JSON.parse` does not handle `\u0000` correctly:
```cs
var engine = new Engine();
engine.SetValue("log", new Action<object>(Console.WriteLine));
engine.Execute(@"js code below");
```
```js
const null_text = '{"a":"\\u0000"}';
const null_obj = JSON.parse(null_text);
log(null_text);
log(null_obj.a.length);
log(null_obj.a);
const a_text = '{"a":"\\u0061"}';
const a_obj = JSON.parse(a_text);
log(a_text);
log(a_obj.a.length);
log(a_obj.a);
```
Expected output:
```
{"a":"\u0000"}
1
{"a":"\u0061"}
1
a
```
Current output:
```
{"a":"\u0000"}
5
u0000
{"a":"\u0061"}
1
a
```
This PR removed unneeded check for escaped characters, and added tests to verify escaped characters are correctly parsed.

Fix JsonParser not able to parse "\u0000"

---

Jint.Tests/Runtime/JsonTests.cs
Jint/Native/Json/JsonParser.cs

This is a continuation of #1160 
This PR removes support for non-standard `\v`, `\x00`, `\0123` and `\(any char here)`, and will throw an error instead.
This behavior is matching other common JSON parser like `JSON.parse` found in nodejs.
```js
// node v16.13.0
JSON.parse('{"\\v":1}')
// Uncaught SyntaxError: Unexpected token v in JSON at position 3
```
```cs
// Newtonsoft.Json 13.0.1
const string json = @"{""\v"":1}";
var obj1 = Newtonsoft.Json.JsonConvert.DeserializeObject(json);
// Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \v. Path '', line 1, position 4.
```

Make JsonParser escape character parsing more strict

---

Jint.Tests/Runtime/ModuleTests.cs
Jint/Engine.Modules.cs

Fixes https://github.com/sebastienros/jint/issues/1162

Fix TimeoutInterval crashing ImportModule

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/FunctionEnvironmentRecord.cs
Jint/Runtime/Environments/GlobalEnvironmentRecord.cs
Jint/Runtime/Environments/ObjectEnvironmentRecord.cs
Jint/Runtime/ExceptionHelper.cs
Jint/Runtime/Modules/ModuleNamespace.cs

Improve class constructor error reporting

---

Jint/Native/Array/ArrayInstance.cs
Jint/Native/Iterator/IteratorInstance.cs
Jint/Native/Json/JsonInstance.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Native/Math/MathInstance.cs
Jint/Native/Object/ObjectClass.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/Promise/PromiseInstance.cs
Jint/Native/Reflect/ReflectInstance.cs
Jint/Native/Symbol/SymbolInstance.cs
Jint/Runtime/Interop/NamespaceReference.cs
Jint/Runtime/Interop/TypeReference.cs

There are types that are not needed per spec and also cause invalid `toString` behavior as value is used as string presentation.

Remove unnecessary ObjectClass types

---

Jint.Tests/Runtime/Domain/Dimensional.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs

In my work project, I need catch exception from wrong arithmetic operation with my types. See [Issue#1866](https://github.com/sebastienros/jint/issues/1186)

Added the ability to catch the CLR exception from an overridden arithmetic operator.

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj
Jint.Tests.Test262/Jint.Tests.Test262.csproj
Jint.Tests/Jint.Tests.csproj

Porting automatic test case generation if missing from Esprima side, adding GitHubActions logger.
relates to #1196

Generate test262 test cases on build if missing

---

Jint.Tests.Test262/Test262Harness.settings.json
Jint/Native/Object/ObjectPrototype.cs

Not endorsed by spec, but easy addition and allows legacy to work.
/cc @AudriusButkevicius

Implement __defineGetter__ and __defineSetter__

---

Jint.Tests/Runtime/ModuleTests.cs
Jint.Tests/Runtime/Scripts/dir with spaces/format name.js
Jint/Runtime/Modules/DefaultModuleLoader.cs

This fixes imports from paths that contains spaces (and other characters that are escaped in URIs).

Decode import URI before using it as a file name

---

Jint/Native/Function/ScriptFunctionInstance.cs

I had fixed this in #1074 before but it was overwritten by some other changes. Unfortunately my code fails without this change. I can't reproduce it in isolation though.

Fix missing evaluation context in constructor

---

Jint.Tests/Runtime/ErrorTests.cs
Jint/Engine.cs
Jint/Runtime/Interpreter/Statements/JintTryStatement.cs
Jint/Runtime/JavaScriptException.cs
Jint/Runtime/TypeConverter.cs

* remove quick patch from JintTryStatement introduced in #853
* implement "ideal" solution described in #853 (try/finally in Engine.Call and Engine.Construct)
* change behaviour of JavaScriptException.SetJavaScriptCallstack() so that it will not overwrite the existing stack trace unless explicitly told to
* add test
fixes #1202

Fix interop stack trace unwind (#1202)

---

Jint.Tests/Runtime/ErrorTests.cs
Jint/Native/Error/ErrorConstructor.cs
Jint/Runtime/CallStack/JintCallStack.cs
Jint/Runtime/Interpreter/Expressions/JintNewExpression.cs
Jint/Runtime/Interpreter/Statements/JintThrowStatement.cs
Jint/Runtime/Interpreter/Statements/JintTryStatement.cs

When an error is explicitly thrown from a script, it does make sense to include the Error constructor itself in the captured stack trace. The trace should begin at the point where the Error object is constructed.
Changes:
* If the current function on the call stack is the Error constructor function, exclude it from the captured stack trace.
* Fix issues with reported location so that JavaScriptException.Location is consistent with the location recorded in the stack trace.
* Add new test, adjust existing tests

Exclude Error constructor from stack trace

---

Jint.Tests/Runtime/InteropTests.Json.cs
Jint.Tests/Runtime/InteropTests.cs
Jint.Tests/Runtime/WeakSetMapTests.cs
Jint/Engine.cs
Jint/Native/WeakMap/WeakMapInstance.cs
Jint/Native/WeakSet/WeakSetInstance.cs
Jint/Options.cs

Add engine-level `ConditionalWeakTable` to track object wrappers to ensure old ones for same object are being reused, this solves identity problems when accessing same object instance multiple times from interop object's properties for example.
fixes #1192

Maintain ObjectWrapper identity

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/ClrFunctionInstance.cs
Jint/Runtime/Intrinsics.cs

As discussed with @lahma on [gitter](https://gitter.im/sebastienros/jint?at=62de95cbb408e830dc50fdc5). This allows using the `CatchClrExceptions` handler on ClrFunctionInstance. Works for modules and scripts.

Rethrow CLR function exceptions as JS errors

---

Jint.Tests/Runtime/FunctionTests.cs
Jint.Tests/Runtime/ProxyTests.cs
Jint/Native/Proxy/ProxyInstance.cs

This reverts a change in ProxyInstance.ToString from #736. All the proxy string conversions match V8 10.4.132.20. I added some tests, not sure if you want to test to that level.
fixes #1249

Removed ProxyInstance ToString override so calls the property 'toString'

---

Jint.Tests/Runtime/RegExpTests.cs
Jint/Native/Iterator/IteratorInstance.cs

Fix Regex Iterator

---

Jint.Tests/Runtime/Debugger/EvaluateTests.cs
Jint/Engine.cs
Jint/Native/JsBigInt.cs
Jint/Runtime/CallStack/CallStackElement.cs
Jint/Runtime/CallStack/JintCallStack.cs
Jint/Runtime/Debugger/CallFrame.cs
Jint/Runtime/Debugger/DebugCallStack.cs
Jint/Runtime/ExceptionHelper.cs

Both `Call` and `Construct` instantiated `new CallStackElement(functionInstance, expression, ExecutionContext);` which effectively became part of the call's stack frame and for deeply nested function invocations (recursion) it really adds up. This PR slims down required constructs and moves instantiation to call stack `Push` side. Now the construct now longer takes stack space during the two types of invocations and also the Jint's storage is smaller.
Relates to #1159
/cc @KurtGokhan @Jither 
```
Type layout for 'CallStackElement'
Size: 64 bytes. Paddings: 0 bytes (%0 of empty space)
|==================================================================|
|   0-7: FunctionInstance Function (8 bytes)                       |
|------------------------------------------------------------------|
| …
```

Reduce stack frame size during Call and Construct

---

Jint.Tests/Runtime/EngineLimitTests.cs
Jint/Engine.cs
Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs
Jint/Runtime/Interpreter/Statements/JintBlockStatement.cs
Jint/Runtime/Interpreter/Statements/JintDoWhileStatement.cs
Jint/Runtime/Interpreter/Statements/JintForInForOfStatement.cs
Jint/Runtime/Interpreter/Statements/JintForStatement.cs
Jint/Runtime/Interpreter/Statements/JintIfStatement.cs
Jint/Runtime/Interpreter/Statements/JintTryStatement.cs
Jint/Runtime/Interpreter/Statements/JintWhileStatement.cs
Jint/Runtime/Interpreter/Statements/JintWithStatement.cs
Jint/Runtime/Interpreter/Statements/ProbablyBlockStatement.cs

Just shuffling code around a bit, making sure less allocations and methods inline better.
releates to #1159
| **Diff**|Method|FileName|Mean|Error|Gen 0|Gen 1|Gen 2|Allocated|
|------- |-------|-------|-------:|-------|-------:|-------:|-------:|-------:|
| Old |Run|3d-cube|238.03 ms|0.346 ms|3000.0000|333.3333|-|51,129 KB|
| **New** |	|	| **246.55 ms (+4%)** | **0.586 ms** | **3000.0000 (0%)** | **333.3333 (0%)** | **-** | **51,129 KB (0%)** |
| Old |Run|3d-morph|187.54 ms|2.607 ms|3000.0000|1000.0000|333.3333|49,744 KB|
| **New** |	|	| **195.80 ms (+4%)** | **0.391 ms** | **3000.0000 (0%)** | **1000.0000 (0%)** | **333.3333 (0%)** | **49,744 KB (0%)** |
| Old |Run|3d-raytrace|199.38 ms|0.295 ms|5000.0000|1000.0000|-|93,394 KB|
| **New** |	|	| **199.12 ms (0%)** | **0.411 ms** | …

Improve recursion performance v1

---

Jint.Tests/Runtime/MethodAmbiguityTests.cs
Jint/Runtime/TypeConverter.cs

Fix array method scoring under interop

---

Jint.Tests/Runtime/EngineLimitTests.cs
Jint/Engine.cs
Jint/Native/Function/FunctionInstance.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Runtime/Interpreter/EvaluationContext.cs
Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs
Jint/Runtime/Interpreter/Expressions/JintExpression.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs
Jint/Runtime/Interpreter/JintStatementList.cs
Jint/Runtime/Interpreter/Statements/JintExpressionStatement.cs
Jint/Runtime/Interpreter/Statements/JintStatement.cs

Checking some hot paths and ensuring that the stack doesn't contain unnecessary items. The `string-validate-input` is pretty insane, though the tests still pass 🤷🏻‍♂️ 
/cc @KurtGokhan @CreepGin 
| **Diff**|Method|FileName|Mean|Error|Gen 0|Gen 1|Gen 2|Allocated|
|------- |-------|-------|-------:|-------|-------:|-------:|-------:|-------:|
| Old |Run|3d-cube|217.72 ms|0.453 ms|3000.0000|333.3333|-|51,125 KB|
| **New** |	|	| **206.21 ms (-5%)** | **0.372 ms** | **3000.0000 (0%)** | **333.3333 (0%)** | **-** | **51,125 KB (0%)** |
| Old |Run|3d-morph|160.62 ms|0.226 ms|2000.0000|1000.0000|-|49,744 KB|
| **New** |	|	| **158.71 ms (-1%)** | **0.510 ms** | **3000.0000 (+50%)** | **1250.0000 (+25%)** | **500.0000** | **49,745 KB (0%)** |
| Old |Run|3d-raytrace|173.30 ms|1.197 …

More tweaks to reduce call stack size

---

Jint/Collections/HybridDictionary.cs
Jint/Collections/ListDictionary.cs
Jint/Collections/StringDictionarySlim.cs
Jint/Native/Global/GlobalObject.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Runtime/Completion.cs
Jint/Runtime/Debugger/DebugScopes.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/EnvironmentRecord.cs
Jint/Runtime/Environments/GlobalEnvironmentRecord.cs
Jint/Runtime/Environments/JintEnvironment.cs
Jint/Runtime/Environments/ModuleEnvironmentRecord.cs
Jint/Runtime/Environments/ObjectEnvironmentRecord.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs
Jint/Runtime/Interpreter/EvaluationContext.cs
Jint/Runtime/Interpreter/Expressions/JintConstantExpression.cs
Jint/Runtime/Interpreter/Expressions/JintFunctionExpression.cs
Jint/Runtime/Interpreter/Expressions/JintIdentifierExpression.cs
Jint/Runtime/Interpreter/Expressions/JintLiteralExpression.cs
Jint/Runtime/Interpreter/Expressions/JintSpreadExpression.cs
Jint/Runtime/Interpreter/Expressions/JintThisExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUnaryExpression.cs
Jint/Runtime/Interpreter/Expressions/NullishCoalescingExpression.cs
Jint/Runtime/Interpreter/Statements/JintDoWhileStatement.cs
Jint/Runtime/Interpreter/Statements/JintExportNamedDeclaration.cs
Jint/Runtime/Interpreter/Statements/JintForStatement.cs
Jint/Runtime/Interpreter/Statements/JintFunctionDeclarationStatement.cs
Jint/Runtime/Interpreter/Statements/JintStatement.cs
Jint/Runtime/Interpreter/Statements/JintSwitchStatement.cs

Going through `GlobalEnvironmentRecord` and optimizing it a bit. Biggest change is to remove `ObjectEnvironmentRecord` as intermediary abstraction for global access and replace with faster patterns.

Improve global object setup and access performance

---

Jint/Engine.cs
Jint/HoistingScope.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/FunctionEnvironmentRecord.cs
Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs
Jint/Runtime/Interpreter/Expressions/JintFunctionExpression.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs
Jint/Runtime/Interpreter/Statements/JintStatement.cs
Jint/Runtime/Interpreter/Statements/JintSwitchStatement.cs

* make DeclarativeEnvironmentRecord properties lazy
* check AST if there's a real need to have arguments object passed in

Reduce memory allocations in function calls

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/ObjectWrapper.cs

See discussion #1285 : call dispose on enumerator (or execute finally clause on enumerator methods/properties)
- Added a call to (_enumerator as IDisposable)?.Dispose() in EnumerableIterator.Close
- Added 3 test cases : normal termination, on break, on exception

Call Dispose on enumerator (#1285)

---

Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj
Jint.Tests.PublicInterface/PublicInterfaceTests.cs
Jint.sln
Jint/Native/Function/BindFunctionInstance.cs

Make the BindFunctionInstance class public.  Includes a new unit-test project that contains a valid use case for the bind() function.  Note that a new test project was required since the Jint internals are visible to the existing Jint.Tests project.
fixes #1287

Make BindFunctionInstance public

---

Jint.Tests/Runtime/EngineLimitTests.cs
Jint/Engine.Modules.cs
Jint/Runtime/Completion.cs
Jint/Runtime/Environments/ExecutionContext.cs
Jint/Runtime/Interpreter/EvaluationContext.cs
Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintExpression.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs
Jint/Runtime/Interpreter/JintStatementList.cs
Jint/Runtime/Interpreter/Statements/JintBreakStatement.cs
Jint/Runtime/Interpreter/Statements/JintClassDeclarationStatement.cs
Jint/Runtime/Interpreter/Statements/JintContinueStatement.cs
Jint/Runtime/Interpreter/Statements/JintDebuggerStatement.cs
Jint/Runtime/Interpreter/Statements/JintDoWhileStatement.cs
Jint/Runtime/Interpreter/Statements/JintEmptyStatement.cs
Jint/Runtime/Interpreter/Statements/JintForInForOfStatement.cs
Jint/Runtime/Interpreter/Statements/JintForStatement.cs
Jint/Runtime/Interpreter/Statements/JintIfStatement.cs
Jint/Runtime/Interpreter/Statements/JintLabeledStatement.cs
Jint/Runtime/Interpreter/Statements/JintReturnStatement.cs
Jint/Runtime/Interpreter/Statements/JintStatement.cs
Jint/Runtime/Interpreter/Statements/JintSwitchBlock.cs
Jint/Runtime/Interpreter/Statements/JintSwitchStatement.cs
Jint/Runtime/Interpreter/Statements/JintThrowStatement.cs
Jint/Runtime/Interpreter/Statements/JintWhileStatement.cs
Jint/Runtime/Interpreter/Statements/ProbablyBlockStatement.cs
Jint/Runtime/Modules/CyclicModuleRecord.cs
Jint/StrictModeScope.cs

Small steps towards returning data using context instead of structs. `Target` is a prime example of returning possible jump instruction via completion which is not needed in 99% of the cases.
Tests seem to have quite the jitter, but show that we are moving to the right direction.
| Old |Run|dromaeo-3d-cube|27.893 ms|0.0420 ms|7166.38 KB|
| **New** |	|	| **26.489 ms (-5%)** | **0.0326 ms** | **7164.43 KB (0%)** |
| Old |Run|dromaeo-core-eval|7.049 ms|0.0172 ms|320.64 KB|
| **New** |	|	| **7.304 ms (+4%)** | **0.0526 ms** | **319.54 KB (0%)** |
| Old |Run|dromaeo-object-array|81.914 ms|0.3203 ms|106133.43 KB|
| **New** |	|	| **84.156 ms (+3%)** | **0.1687 ms** | **106134.6 KB (0%)** |
| Old …

Move data from Completion and ExpressionResult to context

---

Jint.Tests.Test262/Test262Harness.settings.json
Jint/Native/Promise/PromiseConstructor.cs
README.md

This implements `Promise.any`
Spec: https://tc39.es/ecma262/#sec-promise.any
I am planning to implement `Promise.allSettled` too and I will try to reduce duplicated codes when implementing that.

Implement Promise.any

---

Jint.Tests.PublicInterface/RavenApiUsageTests.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayOperations.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs

This PR changes internal `ArrayInstance` logic to prefer having just plain `JsValue` instances as array elements. `PropertyDescriptor` instances are only created when needed and they replace the original `JsValue` in given index. `PropertyDescriptor`s are usually needed only in very specific scenarios, like get/set property definition for array index.
| **Diff**|Method|N|Mean|Error|Allocated|
| Old |Slice|100|231.0 μs|0.46 μs|516.41 KB|
| **New** |	|	| **216.2 μs (-6%)** | **0.78 μs** | **263.28 KB (-49%)** |
| Old |Concat|100|300.6 μs|1.31 μs|593.75 KB|
| **New** |	|	| **297.5 μs (-1%)** | **0.92 μs** | **357.81 KB (-40%)** |
| Old |Unshift|100|8,936.7 μs|30.50 μs|4256.26 KB|
| **New** |	|	| **7,357.2 μs (-18%)** | **64.31 μs** | …

Reduce memory allocations in array handling

---

Jint.Tests.Test262/Test262Harness.settings.json
Jint/Native/Promise/PromiseConstructor.cs
README.md

Implements Promise.allSettled
Spec: https://tc39.es/ecma262/#sec-promise.allsettled
Also reduces code duplication in Promise static methods like `all`, `any`, `allSettled` and `race` since the first 6 steps of those are same in the spec.

Implement Promise.allSettled

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Native/Object/ObjectConstructor.cs

[As seen in specs](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-object.isextensible), these methods should return a boolean. Somehow this is not covered by test262.
Also added test for #206 so it can be closed.

Fix some Object static methods returning wrong value

---

Jint.Tests/Runtime/TypeConverterTests.cs
Jint/Native/Object/ObjectConstructor.cs
Jint/Native/Object/ObjectInstance.cs

Found another bug. This should fix it.
> @lahma: That was your 3rd hactoberfest-accepted label in this repo
Let's make it 4 😆

Fix toPrimitive evaluating multiple times during "in" expression

---

Jint/Options.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs

As discussed with @libaowei on Gitter related to #1321 and #1326, turns out they has some script that rely on some non-standard behavior of a older version of Jint. Because they want to maintain compatibility for those scripts they decided to use a custom object wrapper.
This pull request make the object wrapper cache available to `WrapObjectHandler` through argument, which was their original intention if I understand correctly.

Cache wrapped object returned by WrapObjectHandler

---

Jint.Tests/Runtime/ArrayTests.cs
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/Array/ArrayOperations.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/Object/ObjectInstance.cs

* Get and HasProperty usage against proxies

Fix some array issues uncovered by compat-table tests

---

Jint.Tests.PublicInterface/ConstraintUsageTests.cs
README.md

Adds a PublicInterface test that fetches a `CancellationConstraint` with the `FindConstraint<>` method and calls its overloaded `Reset()` method in order to pass in a new `CancellationToken`.
---
The example usage of CancellationConstraint demonstrated in the README doesn't work anymore because the constructor was made internal.
A dummy CancellationToken must be provided when creating the constraint if one intends to pass the actual one via Reset(). `default` doesn't work though, as the constraint won't be created then.
see #1345

PublicInterface test for CancellationConstraint.Reset

---

Jint.Tests.PublicInterface/ConstraintUsageTests.cs
Jint.Tests.PublicInterface/RavenApiUsageTests.cs
Jint.Tests/Runtime/ArrayTests.cs
Jint.Tests/Runtime/Domain/UuidConstructor.cs
Jint.Tests/Runtime/Domain/UuidPrototype.cs
Jint.Tests/Runtime/InteropTests.cs
Jint.Tests/Runtime/ObjectInstanceTests.cs
Jint.Tests/Runtime/PromiseTests.cs
Jint/Engine.cs
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/Date/DateConstructor.cs
Jint/Native/Date/DateInstance.cs
Jint/Native/Json/JsonParser.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Native/Object/ObjectInstance.Fast.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/Promise/PromiseConstructor.cs
Jint/Native/RegExp/RegExpPrototype.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs
Jint/Runtime/JavaScriptException.cs

This tweaks some APIs easier for interop use based on RavenDB usage:
* `Date`, `ArrayInstance`  and `Object` can be constructed correctly by using constructor for the default case
* Optimize and harmonize `FastSet*` scenario when object instance is owned
* Change `Engine.SetValue` to take string as property, one cannot set `Symbol`s via the API anyway
* Expose `ArrayInstance.Push` to public API
* Add `ArrayInstance.GetEntries` which allows to enumerate array key-value-pairs

Add easier APIs for interop usage

---

Jint.Benchmark/ObjectAccessBenchmark.cs
Jint.Tests.PublicInterface/RavenApiUsageTests.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/ArrayBuffer/ArrayBufferConstructor.cs
Jint/Native/ArrayBuffer/ArrayBufferPrototype.cs
Jint/Native/BigInt/BigIntConstructor.cs
Jint/Native/BigInt/BigIntPrototype.cs
Jint/Native/DataView/DataViewConstructor.cs
Jint/Native/DataView/DataViewPrototype.cs
Jint/Native/Date/DateConstructor.cs
Jint/Native/Date/DatePrototype.cs
Jint/Native/DateInstance.cs
Jint/Native/Global/GlobalObject.cs
Jint/Native/JsObject.cs
Jint/Native/Number/NumberInstance.cs
Jint/Native/Number/NumberPrototype.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/Prototype.cs
Jint/Native/TypedArray/IntrinsicTypedArrayConstructor.cs
Jint/Native/TypedArray/IntrinsicTypedArrayPrototype.cs
Jint/Native/TypedArray/TypedArrayPrototype.cs
Jint/Runtime/TypeConverter.cs

Now with recently added knowledge about object types, we can check if we are accessing plain basic object and skip virtual dispatch and property descriptor renewal when possible.
| **Diff**|Method|Mean|Error|Allocated|
|------- |-------|-------:|-------|-------:|
| Old |UpdateObjectProperty|265.8 ms|1.06 ms|90.95 MB|
| **New** |	| **221.9 ms (-17%)** | **0.61 ms** | **60.42 MB (-34%)** |

Optimize plain object access

---

Jint/Native/Array/ArrayPrototype.cs
Jint/Native/JsString.cs
Jint/Native/String/StringConstructor.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs
Jint/Runtime/Interpreter/Statements/ProbablyBlockStatement.cs

* no need to call `PutValue` when target is not an object and value was mutated in-place
* fast path for `FromCharCode`
* improve `ProbablyBlockStatement`
| Old |Run|dromaeo-3d-cube|25.803 ms|0.0178 ms|6247.69 KB|
| **New** |	|	| **25.639 ms (-1%)** | **0.0151 ms** | **6248.21 KB (0%)** |
| Old |Run|dromaeo-core-eval|6.258 ms|0.0199 ms|321.58 KB|
| **New** |	|	| **5.597 ms (-11%)** | **0.0244 ms** | **321.84 KB (0%)** |
| Old |Run|dromaeo-object-array|72.128 ms|0.1724 ms|101492.07 KB|
| **New** |	|	| **69.330 ms (-4%)** | **0.2562 ms** | **101492.03 KB (0%)** |
| Old |Run|droma(...)egexp [21]|231.533 ms|1.5412 ms|172628.85 KB|
| **New** |	|	| **222.238 ms (-4%)** | **1.9947 ms** | …

Small performance optimization to string handling

---

Jint.Tests/Runtime/Debugger/ScopeTests.cs
Jint.Tests/Runtime/Debugger/StepFlowTests.cs
Jint.Tests/Runtime/Debugger/TestHelpers.cs
Jint/Native/Function/ClassDefinition.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Runtime/Debugger/DebugScope.cs
Jint/Runtime/Debugger/DebugScopeType.cs
Jint/Runtime/Debugger/DebugScopes.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/EnvironmentRecord.cs
Jint/Runtime/Environments/GlobalEnvironmentRecord.cs
Jint/Runtime/Environments/ObjectEnvironmentRecord.cs

Fixed undefined binding values in module scope
Implemented DebugScopeType.Module - that's one more alignment with Chromium dev-tools.
Not too happy about creating BindingName instances to call `TryGetBinding` - but of course, in terms of performance, this only happens when inspecting - and the change gets rid of the (I think) now redundant `TryGetBindingValue`: `DeclarativeEnvironmentRecord.TryGetBinding` has identical semantics; `ObjectEnvironmentRecord.TryGetBinding` is more up-to-date development-wise (handles `with` and other edge cases); I *think* the same goes for `GlobalEnvironmentRecord`, but that one is harder for me to wrap my head around. Of course, this also circumvents the need for writing a `TryGetBindingValue` for `ModuleEnvironmentRecord`. 😁
The pull request is draft for …

Module-related debugger improvements

---

Jint.Tests/Runtime/Debugger/BreakPointTests.cs
Jint.Tests/Runtime/Debugger/DebugHandlerTests.cs
Jint.Tests/Runtime/Debugger/ScopeTests.cs
Jint.Tests/Runtime/Debugger/StepModeTests.cs
Jint.Tests/Runtime/EngineTests.cs
Jint.Tests/Runtime/Modules/DefaultModuleLoaderTests.cs
Jint/Engine.Modules.cs
Jint/Engine.cs
Jint/Runtime/Debugger/BreakLocation.cs
Jint/Runtime/Debugger/DebugHandler.cs
Jint/Runtime/Debugger/DebugInformation.cs
Jint/Runtime/Debugger/DebugScope.cs
Jint/Runtime/Debugger/DebugScopes.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Environments/EnvironmentRecord.cs
Jint/Runtime/Environments/GlobalEnvironmentRecord.cs
Jint/Runtime/Environments/ObjectEnvironmentRecord.cs
Jint/Runtime/Interpreter/Statements/JintDebuggerStatement.cs
Jint/Runtime/Modules/DefaultModuleLoader.cs
Jint/Runtime/Modules/SourceTextModuleRecord.cs

* Added `Skip` event to `DebugHandler` (see https://github.com/Jither/Jint.DebuggerExample/blob/main/NOTES.md#Events for rationale)
* Added `Parsed` event to `Engine` for giving e.g. debuggers access to the AST as parsed by the engine, when passing code rather than AST to `Execute`/`Evaluate`.
* `BindingNames` on scopes are now lazily evaluated. Because we still want to leave out scopes without any bindings from scope chains (for now), a `HasBindings()` method has been added to environment records.
* `Global` and `Local` properties on `CallFrame` have been removed. Because Jint's scope system is now more complex (and mostly aligned with other Javascript debuggers), `Global` and `Local` are very arbitrary scopes to make special cases for. Either can, of course, still be retrieved through …

Debugger API improvements

---

Jint.Tests/Runtime/SwitchTests.cs
Jint/Runtime/Environments/DeclarativeEnvironmentRecord.cs
Jint/Runtime/Interpreter/Statements/JintSwitchBlock.cs

Fix switch's case block lexical scope handling

---

Jint.Tests/Runtime/NumberTests.cs
Jint/Native/Global/GlobalObject.cs

Improve parseFloat performance and number range

---

Jint/Engine.cs

Fix nullable annotation of Engine.Invoke arguments

---

Jint.Tests.PublicInterface/RavenApiUsageTests.cs
Jint/Engine.cs
Jint/Native/JsBigInt.cs
Jint/Native/JsBoolean.cs
Jint/Native/JsNull.cs
Jint/Native/JsNumber.cs
Jint/Native/JsString.cs
Jint/Native/JsSymbol.cs
Jint/Native/JsUndefined.cs
Jint/Native/JsValue.cs
Jint/Native/String/StringPrototype.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/TypeConverter.cs

* move ToBoolean as virtual method to JsValue
This PR opens possibility for uses cases like in RavenDB where they have a custom string type that can be expensive to materialize from encoded format. Now logic checks length before trying to do operations like equality, indexof or implicit logical boolean operators. Test case covers new features and materialization avoidance.

Improved support for defining custom JsString deriving type

---

Jint.Tests.PublicInterface/RavenApiUsageTests.cs
Jint/Native/JsNull.cs
Jint/Native/JsUndefined.cs
Jint/Native/JsValue.cs

When there was custom JsUndefined or JsNull implementation, new `ToBoolean` didn't account for that.

Ensure support for custom null and undefined

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Options.cs
Jint/Runtime/Host.cs

Noticed that for example [EventStore](https://github.com/EventStore/EventStore) wants to forbid `eval` usage, which makes sense: https://github.com/EventStore/EventStore/blob/2a774bb0213f2588ad9760f5529d5c21dc6c12f0/src/EventStore.Projections.Core/Services/Interpreted/JintProjectionStateHandler.cs#L52

Support configuring whether dynamic (eval) JavaScript code is allowed

---

CREDITS.txt
Jint.Tests/Runtime/DateTests.cs
Jint/Native/Date/DateConstructor.cs
Jint/Native/Date/MimeKit.cs

Utilizing extracted code from MimeKit, removed all things not needed. No dependency on library, but attribution given in both source and CREDITS.txt.
A fast turnaround for soon three year old issue.
fixes #766

Improve date parsing by utilizing MimeKit logic

---

Jint.Tests.PublicInterface/ConstraintUsageTests.cs
Jint.Tests.PublicInterface/PublicInterfaceTests.cs
Jint.Tests/Runtime/PromiseTests.cs
Jint/Engine.cs
Jint/Runtime/Interpreter/EvaluationContext.cs

Also trying to stabilize some tests.
fixes #1432

Return storage of last syntax node to engine instance

---

Jint.Tests.PublicInterface/ConstraintUsageTests.cs
Jint.Tests.PublicInterface/PublicInterfaceTests.cs
Jint/Constraints/ConstraintsOptionsExtensions.cs
Jint/Engine.cs

Add support for checking constraints from engine

---

Jint.Tests.PublicInterface/ConstructorTests.cs
Jint/Native/Constructor.cs

Nobody wants to bother about thinking about realms so let's make the basic constructor a bit simpler. We can open Realm-taking one if needed.

Don't require Realm in Constructor public constructor

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Native/Date/DateConstructor.cs

Unfortunately `DateTime.MaxValue` is not that easy as it requires tick precision, would require refactoring the internal date presentation (which might not be a bad idea in the long rung).
fixes #778

Ensure DateTime.MinValue can be passed via interop

---

Jint/Engine.cs

When Jint was modified to use nullable reference types, it lost the ability to pass a null value into Engine.SetValue(string, object).  This pull request restores that functionality.

Engine.SetValue accepts a nullable object.

---

Jint/Runtime/Interop/DefaultTypeConverter.cs
Jint/Runtime/Interop/ITypeConverter.cs

* proper Try pattern without exception catching
* remove unstable caching

Improve DefaultTypeConverter

---

Jint.Tests.CommonScripts/ConcurrencyTest.cs
Jint.Tests.CommonScripts/SunSpiderTests.cs
Jint/Engine.cs
Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs
Jint/Runtime/Interpreter/Expressions/JintExpression.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs

Because `JintFunctionDefinition` has initialization phase, it can cause race condition because it was shared as part of AST. Now using more static `FunctionDeclaration` and test to cover.
fixes #1457

Fix race condition in sharing of function state

---

Jint.Tests/Runtime/WeakSetMapTests.cs
Jint/Options.cs

This feature can cause delayed GC and worry amongst users. Let's disable this feature by default so people don't report Jint leaking memory when GC is just delayed due to conditional weak table.

Disable object identity tracking by default under interop

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/Reflection/IndexerAccessor.cs

Handle Symbol.toPrimitive and valueOf calls better under interop

---

Jint.Tests.Test262/Test262Harness.settings.json
Jint.Tests/Jint.Tests.csproj
Jint.Tests/Runtime/DateTests.cs
Jint.Tests/Runtime/EngineTests.cs
Jint.Tests/Runtime/InteropTests.cs
Jint.Tests/Runtime/Scripts/moment.js
Jint/Native/Date/DateConstructor.cs
Jint/Native/Date/DateExtensions.cs
Jint/Native/Date/DatePrototype.cs
Jint/Native/DatePresentation.cs
Jint/Native/JsDate.cs
Jint/Options.cs
Jint/Runtime/TypeConverter.cs

Change JsDate to be based on long and helper flags. This follows JS semantics better and milliseconds maps to integral number. Tracking invalid dates with flag info about being NaN or Infinity. Also allows to stamp value as .NET DateTime `MinValue`/`MaxValue`.
`MakeDate`/`MakeDay`/`MakeTime` still play with doubles as it's required by the spec and can be arithmetic with very large numbers.
Added new hook in options `GetUtcOffset` which allows to plugin a strategy for getting better time zone database than available for example in Windows by default.
fixes #787

Improve date handling and time zone support

---

Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj
Jint.Tests.PublicInterface/TimeSystemTests.cs
Jint.Tests.Test262/Test262Harness.settings.json
Jint.Tests/Jint.Tests.csproj
Jint.Tests/Runtime/DateTests.cs
Jint/Native/Date/DateConstructor.cs
Jint/Native/Date/DatePrototype.cs
Jint/Native/DatePresentation.cs
Jint/Native/JsDate.cs
Jint/Options.cs
Jint/Runtime/DefaultTimeSystem.cs
Jint/Runtime/ITimeSystem.cs

* allow plugging proper IANA data provider, like NodaTimeSystem
* add support for JS negative/large years

Create ITimeSystem abstraction for date parsing/time zone logic

---

Jint.Tests/Runtime/EngineTests.cs
Jint/Engine.cs

Fix Engine.SetValue(string, string) to check for null value

---

Jint/Collections/HybridDictionary.cs
Jint/Collections/StringDictionarySlim.cs
Jint/Extensions/ReflectionExtensions.cs
Jint/Jint.csproj
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/Global/GlobalObject.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/String/StringPrototype.cs
Jint/Native/TypedArray/IntrinsicTypedArrayPrototype.cs
Jint/Options.Extensions.cs
Jint/Options.cs
Jint/Runtime/CallStack/JintCallStack.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs
Jint/Runtime/Interop/Reflection/ExtensionMethodCache.cs
Jint/Runtime/Interpreter/Expressions/JintArrayExpression.cs
Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs
Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs

Easier to track possible accidental introduction and other usage.

Remove implicit using for System.Linq

---

Jint.Tests/Runtime/JsonTests.cs
Jint/Native/Array/ArrayConstructor.cs
Jint/Native/Json/JsonParser.cs
Jint/Options.Extensions.cs
Jint/Options.cs

Hi there,
first PR for this project, hopefully got everything right 😃.
I tried to not modify too much to not destroy previous knowledge of the parser code. 
* JSON.parse now takes about half the time to complete
* JSON.parse now only allocates about 20% of the previously required memory
* JSON.parse more aligned to the JSON specification
* Added recursion limit to JsonParser to prevent StackOverflow-Exception
The old parser did parse the following strings, but they are not valid according to the JSON specification:
* `"[1,]"`: return value was `JsArray([1, null])`
* `".1"`: return value was `JsNumber(0.1)`
These will now throw a JavaScriptException. These cases are baked by tests.
Previously the parser did not have a recursion limit. A specially crafted JSON string could lead to a …

JSON.parse optimizations, refactoring, DoS-attack prevention

---

Jint.Tests/Runtime/JsonSerializerTests.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Runtime/TypeConverter.cs

* JSON.stringify now completes in about 60-50% of the time to complete the serialization. These numbers do apply when serializing plain objects without complex replacer or with custom `toJSON` methods. If you specify a spacer to beautify your generated JSONs, the serializer will take a little bit more time (see the table below), but still be faster compared to the previous revision.
* JSON.stringify now only allocates about 20% of the previously required memory during that process
So long story short, the JSON serializer now uses a two `StringBuilder` for the complete operation instead of getting new ones quite often during the execution. One is used to build the JSON string itself and a second small one gets used when numbers get serialized. 
The behavior of the serializer hasn't …

JSON serialization refactoring and optimization

---

Jint.Tests/Runtime/InstanceOfTests.cs
Jint/Native/JsValue.cs
Jint/Runtime/Interop/TypeReference.cs

Hi! I implemented the functionality to make instanceof operator behave following the ineritance chain of CLR objects. But, because this not should be the default behavior, I suggest an explicit activation via Options.Runtime or a class Attribute. I made a test for net 6.0 too.
Regards.

Support inheritance chain of CLR objects with instanceof operator

---

Jint/Native/Function/FunctionInstance.cs
Jint/Native/Json/JsonParser.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/String/StringInstance.cs
Jint/Pooling/StringBuilderPool.cs
Jint/Runtime/Interop/Reflection/IndexerAccessor.cs
Jint/Runtime/Interpreter/Statements/JintExportDefaultDeclaration.cs

* optimize ObjectInstance.GetOwnPropertyKeys for non-sorting case
* increase StringBuilderPool max capacity check
* smarter checks for integer numbers in JsonParser
| Old |Parse|bestbuy_dataset.json|297.742 ms|5.7835 ms|115.01 MB|
| **New** |	|	| **299.811 ms (+1%)** | **4.3964 ms** | **114.15 MB (-1%)** |
| Old |Stringify|bestbuy_dataset.json|142.319 ms|2.2880 ms|104.63 MB|
| **New** |	|	| **127.802 ms (-10%)** | **1.9511 ms** | **90.18 MB (-14%)** |
| Old |Parse|twitter.json|3.023 ms|0.0057 ms|3.64 MB|
| **New** |	|	| **2.995 ms (-1%)** | **0.0111 ms** | **3.61 MB (-1%)** |
| Old |Stringify|twitter.json|2.926 ms|0.0241 ms|2.74 MB|
| **New** |	|	| **2.434 ms (-17%)** | **0.0118 ms** | …

Optimize JSON serialization

---

Jint.Tests/Runtime/JsonSerializerTests.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Native/Number/NumberPrototype.cs
Jint/Runtime/TypeConverter.cs

Now with .NET Core added as a build target, a small performance improvement can be made for JSON serialization.
This change reduces the time needed for serialization. Depending on the content to serialize, the change leads to a 10-20% time reduction. For some JSON files, it reduced the time to serialize even more, for a few of them, the improvement is almost negatable or even a little bit slower (see `citm_catalog` which takes 4% longer). The improvement works best for all ASCII-only strings (which are probably 99% of all keys for JSON objects) and for long string values (see `doj-blog.json` result for that).
I've changed the signature of the internal method `NumberPrototype.NumberToString`. It doesn't return a string anymore and instead will always fill the provided StringBuilder. That …

JSON serialization performance improvement

---

README.md

Seems that we have everything from 2023 covered: https://github.com/tc39/proposals/blob/main/finished-proposals.md , https://github.com/tc39/ecma262/releases/tag/es2023-candidate-2023-04

Update README.md to reflect ES2023

---

Jint/Engine.cs

It is valid to pass a nullable string to SetValue.  Might as well adjust the annotations to indicate that.
```
string? name = null;
engine.SetValue("name", name);
```

Adjust Engine.SetValue(string, string?) to accept null value.

---

Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintIdentifierExpression.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs

ArrayStressBenchmark:
``` ini
BenchmarkDotNet=v0.13.5, OS=Windows 10 (10.0.19045.3086/22H2/2022Update)
Intel Core i7-4720HQ CPU 2.60GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.302
[Host]     : .NET 6.0.16 (6.0.1623.17311), X64 RyuJIT AVX2
DefaultJob : .NET 6.0.16 (6.0.1623.17311), X64 RyuJIT AVX2
```
main:
|               Method |     Mean |    Error |   StdDev |      Gen0 |     Gen1 | Allocated |
|--------------------- |---------:|---------:|---------:|----------:|---------:|----------:|
|              Execute | 24.45 ms | 0.132 ms | 0.123 ms | 2250.0000 | 187.5000 |   7.18 MB |
| Execute_ParsedScript | 22.74 ms | 0.106 ms | 0.094 ms | 2312.5000 |  93.7500 |   7.15 MB |
PR:
|               Method |     Mean |    Error |   StdDev |      Gen0 |     Gen1 | Allocated | …

Store identifier in local

---

Jint/Runtime/Interop/TypeReference.cs

Changed `AsSpan` usage in `TypeReference.Construct` to plain iteration.
#1543 (beta-2050) has a `ParameterInfo[].AsSpan` usage which will throw `ArrayTypeMismatchException` in Mono (I think only when the target method is static). 
It was reported to mono years ago (https://github.com/mono/mono/issues/17993), but like many other mono bugs, I don't think they will get fixed anytime soon or ever. 
This is breaking things like `new Color(1, 1, 1, 1)` with Unity, or anything similar to this:
```cs
// C#
public struct Foo {
public Foo(float a, float b) {
}
public Foo(float a) {
}
}
```
```js
// JS
new Foo(1, 1) // throws ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
```

Avoiding Mono's ParameterInfo[].AsSpan() bug

---

Jint.Tests/Runtime/EngineLimitTests.cs
Jint.Tests/Runtime/EngineTests.cs
Jint/Engine.cs
Jint/Options.cs
Jint/Runtime/CallStack/StackGuard.cs
Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs
Jint/Runtime/Interpreter/Statements/JintStatement.cs

Extend Stack overflow #1159 
| Old |Run|3d-cube|507.0 ms|0.50 ms|45002.7 KB|
| **New** |	|	| **514.5 ms (+1%)** | **1.41 ms** | **45002.7 KB (0%)** |
| Old |Run|3d-morph|369.2 ms|0.89 ms|46270.99 KB|
| **New** |	|	| **369.6 ms (0%)** | **6.06 ms** | **46270.99 KB (0%)** |
| Old |Run|3d-raytrace|393.1 ms|1.18 ms|86663.02 KB|
| **New** |	|	| **416.6 ms (+6%)** | **1.55 ms** | **86663.95 KB (0%)** |
| Old |Run|access-binary-trees|184.1 ms|0.47 ms|62246.95 KB|
| **New** |	|	| **185.2 ms (+1%)** | **0.85 ms** | **62246.95 KB (0%)** |
| Old |Run|access-fannkuch|1,143.4 ms|2.64 ms|140.84 KB|
| **New** |	|	| **1,155.2 ms (+1%)** | **3.39 ms** | **140.84 KB (0%)** |
| Old |Run|access-nbody|451.6 …

Experimental Stackguard

---

README.md

Changed from CreateModule to AddModule as it probably got renamed without changing readme. Also added a semi-colon which was missing.

Readme Module section update

---

Jint.Tests.Test262/Test262Harness.settings.json
Jint.Tests/Runtime/RegExpTests.cs
Jint/Native/RegExp/RegExpPrototype.cs
Jint/Shims.cs

Implements workarounds for [regex parsing known issues](https://github.com/sebastienros/esprima-dotnet/pull/364#issuecomment-1606045259).
Also, fixes [a bug in unicode mode regex handling](https://github.com/sebastienros/jint/pull/1603/files#diff-c07eb2081a7c5a8fa331c39b2e1d3dec9afa1c9807f1e131ec83629c115df5b2R945-R949) (code point -> code unit index translation is not needed as .NET regexes return code unit indices).

Implement workarounds for regex parsing known issues

---

Jint.Tests/Runtime/InteropExplicitTypeTests.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Native/JsValue.cs
Jint/Options.cs
Jint/Runtime/Descriptors/Specialized/ReflectionDescriptor.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/Reflection/ReflectionAccessor.cs

Close #1611 Support explicit interface and hidden member of super class
Add field `_clrType` to `ObjectWrapper`
Add `unwrapClr` helper method

Support explicit interface and hidden member of super class

---

Jint.Tests.Test262/Test262Harness.settings.json
Jint/Jint.csproj
Jint/Native/RegExp/JsRegExp.cs
Jint/Native/RegExp/RegExpConstructor.cs
Jint/Native/RegExp/RegExpPrototype.cs
Jint/Runtime/Interpreter/Expressions/JintLiteralExpression.cs

Counterpart of https://github.com/sebastienros/esprima-dotnet/pull/392
Besides the issues mentioned in the linked PR, this one also fixes the fast path implementation of `RegExpPrototype.Split`, which is a bit broken.
Unfortunately, the remaining 2 test cases excluded [here](https://github.com/sebastienros/jint/compare/main...adams85:regexp-fixes?expand=1#diff-524efe3f200cee8c6ad344ec2f94e7f14b789909f63be3c1f6b6a9441ee7a5fe) cannot be fixed with our current regex handling approach due to the differences/limitations of the .NET regex engine.
Oh, and one more thing. I'm not sure about this: "https://github.com/adams85/jint/blob/95029c6cbbfc09e81749e39916841296a2e52f4d/Jint/Runtime/Interop/DefaultObjectConverter.cs#L31-L34" I'm afraid that passing a non-adapted, external `Regex` instance to …

Fix capturing group numbering bug and a few more regex-related issues

---

Jint.Repl/Program.cs
Jint.Tests/Runtime/InteropExplicitTypeTests.cs
Jint.Tests/Runtime/InteropTests.TypeReference.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Options.cs
Jint/Runtime/Interop/ClrFunctionInstance.cs
Jint/Runtime/Interop/ClrHelper.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs
Jint/Runtime/Interop/MethodInfoFunctionInstance.cs
Jint/Runtime/Interop/NamespaceReference.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/Reflection/MethodAccessor.cs
Jint/Runtime/Interop/Reflection/NestedTypeAccessor.cs
Jint/Runtime/Interop/Reflection/ReflectionAccessor.cs
Jint/Runtime/Interop/TypeReference.cs
Jint/Runtime/Interop/TypeResolver.cs

- Simplize nested CLR Type, can be got directly from parent type
- Add more CLR helper functions: clrUnwrap, clrWrap, clrToString, clrType, clrTypeToObject, clrObjectToType. The last 3 need Options.Interop.AllowGetType == true.
- Make CLR objects ToString meaningful: NamespaceReference, TypeReference, ClrFunctionInstance, MethodInfoFunctionInstance
- Make Jint.Repl call ToString when Serialize failed

More improvements for CLR Interop

---

Jint.Benchmark/EngineConstructionBenchmark.cs
Jint/Collections/HybridDictionary.cs
Jint/Collections/PropertyDictionary.cs
Jint/Collections/StringDictionarySlim.cs
Jint/Engine.cs
Jint/Native/Global/GlobalObject.Properties.cs
Jint/Native/Global/GlobalObject.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Options.cs
Jint/Runtime/Descriptors/PropertyDescriptor.cs
Jint/Runtime/Descriptors/Specialized/LazyPropertyDescriptor.cs

* reuse default options instance if no configure defined
* resolve default time zone and culture only once for options
* pre-calculate global keys (hash codes), use faster path for dictionary init
| **Diff**|Method|Mean|Error|Allocated|
|------- |-------|-------:|-------|-------:|
| Old |BuildEngine|2.033 μs|0.0198 μs|11.33 KB|
| **New** |	| **1.310 μs (-36%)** | **0.0105 μs** | **10.62 KB (-6%)** |
| Old |EvaluateSimple|2.382 μs|0.0287 μs|12.27 KB|
| **New** |	| **1.632 μs (-31%)** | **0.0154 μs** | **11.55 KB (-6%)** |

Optimize engine construction

---

Jint.Tests.PublicInterface/RavenApiUsageTests.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayOperations.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/JsArray.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Runtime/Interpreter/Expressions/JintArrayExpression.cs
Jint/Runtime/TypeConverter.cs

* always have `JsValue` in array and use sparse as helper to remove type checks
* faster paths for `HasProperty` against `JsArray`
* remove `JsArray` constructor taking `PropertyDescriptor[]`
``` 
BenchmarkDotNet=v0.13.5, OS=Windows 11 (10.0.23531.1001)
AMD Ryzen 9 5950X, 1 CPU, 32 logical and 16 physical cores
.NET SDK=8.0.100-preview.7.23376.3
[Host]     : .NET 6.0.21 (6.0.2123.36311), X64 RyuJIT AVX2
DefaultJob : .NET 6.0.21 (6.0.2123.36311), X64 RyuJIT AVX2
```
| **Diff**|Method|Toolchain|N|Mean|Error|Allocated|
|------- |-------|-------|-------|-------:|-------|-------:|
| Old |Slice|Default|100|254.7 μs|1.14 μs|253.13 KB|
| **New** |	| **Default** |	| **248.8 μs (-2%)** | **0.89 μs** | **253.13 KB (0%)** |
| Old |Concat|Default|100|370.6 μs|0.83 μs|345.31 KB|
| **New** |	| …

Improve array access performance

---

Jint.Tests/Runtime/InteropExplicitTypeTests.cs
Jint/Runtime/Interop/TypeResolver.cs

Interface type wrapper can call object methods.
Fix #1626

Interface type wrapper can call object methods.

---

Jint.Tests/Runtime/DestructuringTests.cs
Jint/Runtime/Environments/FunctionEnvironmentRecord.cs

Fixed the NullReferenceException for the following code:
```js
function test({ ...props }) { }
test({})
```

Fixed rest/spread bug with empty object

---

Jint.Tests/Runtime/AwaitTests.cs
Jint/Runtime/Interop/DelegateWrapper.cs

Experimental - Task to Promise conversion

---

Jint.Tests/Runtime/ProxyTests.cs
Jint/Native/JsValue.cs
Jint/Native/Proxy/JsProxy.cs

fix #1643 
provide detailed message for exceptions in JsProxy
donot use ReferenceEquals on data property value comparing

Proxy on clr

---

Jint.Tests/Runtime/EngineTests.cs
Jint.Tests/Runtime/TypedArrayInteropTests.cs
Jint/JsValueExtensions.cs
Jint/Native/Object/ObjectInstance.cs

Also some utility extensions for float typed arrays and added tests for the changes.
Now when using custom type converters or the DefaultTypeConverter JsTypedArrays should be converted correctly to CLR arrays.
Tried to avoid boxing so it uses _arrayElementType to directly convert to the proper array type using the ToNativeArray generic method.
Should close issue #1641.

Added support to convert JsTypedArray when converting objects.

---

Jint.Tests.CommonScripts/SunSpiderTests.cs
Jint/Engine.cs
Jint/Native/Global/GlobalObject.cs
Jint/Runtime/ExceptionHelper.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs
Jint/Runtime/Interpreter/JintStatementList.cs
Jint/Runtime/Interpreter/Statements/JintReturnStatement.cs

This slows down test suite running a lot as suite goes trough each invalid character causing exceptions handling the program flow.
* dispatch via custom error signaling to remove costly throws
* minimize allocations

Optimize URI decode and encode

---

Jint.Tests/Runtime/PropertyDescriptorTests.cs
Jint.Tests/Runtime/ProxyTests.cs
Jint.Tests/Runtime/TestClasses/IndexerProperty.cs
Jint/Native/Argument/ArgumentsInstance.cs
Jint/Native/Function/FunctionPrototype.cs
Jint/Native/Function/ScriptFunctionInstance.cs
Jint/Runtime/Descriptors/GetSetPropertyDescriptor.cs
Jint/Runtime/Descriptors/PropertyDescriptor.cs
Jint/Runtime/Descriptors/PropertyFlag.cs
Jint/Runtime/Descriptors/Specialized/ClrAccessDescriptor.cs
Jint/Runtime/Descriptors/Specialized/LazyPropertyDescriptor.cs
Jint/Runtime/Descriptors/Specialized/ReflectionDescriptor.cs
Jint/Runtime/Interop/Reflection/FieldAccessor.cs
Jint/Runtime/Interop/Reflection/IndexerAccessor.cs
Jint/Runtime/Interop/Reflection/MethodAccessor.cs
Jint/Runtime/Interop/Reflection/NestedTypeAccessor.cs
Jint/Runtime/Interop/Reflection/PropertyAccessor.cs
Jint/Runtime/Interop/Reflection/ReflectionAccessor.cs

PropertyDescriptor improvements    
add `PropertyFlag.NonData`  
now `PropertyDescriptor`s for CLR Field, Property and Indexer are accessor property descriptors.
By treating CLR  Property as accessor property, it will reduce the time of call to Property Getter.

PropertyDescriptor improvements

---

Jint.Benchmark/ShadowRealmBenchmark.cs
Jint.Tests.PublicInterface/ShadowRealmTests.cs
Jint/Native/ShadowRealm/ShadowRealm.cs

**Please do not merge - test fails!**

#1573 - added convenience API

---

Jint.Tests.PublicInterface/ShadowRealmTests.cs
Jint.Tests.Test262/Test262Harness.settings.json
Jint/Native/Promise/PromiseConstructor.cs
Jint/Native/Proxy/JsProxy.cs
Jint/Native/RegExp/JsRegExp.cs
Jint/Native/RegExp/RegExpExtensions.cs
Jint/Native/RegExp/RegExpPrototype.cs
README.md

* optimize RegExpExec for common case

Implement Promise.withResolvers and update test suite

---

Jint.Tests/Runtime/InteropExplicitTypeTests.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Native/JsValue.cs
Jint/Runtime/Interop/ObjectWrapper.cs

I can't wrap my head around why we would need to have `Equals` to check object wrapper's exposed type as current `ReferenceEquals` is already a strong guarantee. There might be cases to only expose member of exposed type but we shouldn't state that pointer to same object isn't the same object based on what was exposed.
This should return the behavior expected with @CreepGin 's Unity integration.
/cc @CreepGin @viruscamp

Remove exposed CLR type equality requirement from ObjectWrapper.Equals

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/TypeResolver.cs

Include interface's extended interfaces in interop property search

---

Jint.Tests/Runtime/InteropTests.TypeReference.cs
Jint/Engine.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs
Jint/Runtime/Interop/TypeReference.cs

Now after type reference has been created against engine, it will be used as prototype when wrapping injected CLR objects.
https://github.com/sebastienros/jint/discussions/1649#discussioncomment-7399571

Track TypeReference registrations and use as prototype

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/Reflection/IndexerAccessor.cs

Account for possible integer indexers when searching for IndexerAccessor

---

Jint.Tests/Runtime/DateTests.cs
Jint/Runtime/DefaultTimeSystem.cs

Fix parsing of empty date string

---

Jint/Collections/HybridDictionary.cs
Jint/Collections/ListDictionary.cs
Jint/Collections/StringDictionarySlim.cs
Jint/Engine.Ast.cs
Jint/Engine.cs
Jint/HoistingScope.cs
Jint/Runtime/Environments/EnvironmentRecord.cs
Jint/Runtime/Environments/GlobalEnvironmentRecord.cs
Jint/Runtime/Environments/JintEnvironment.cs
Jint/Runtime/Interpreter/Expressions/JintIdentifierExpression.cs
Jint/Runtime/Interpreter/Statements/JintExpressionStatement.cs

```
BenchmarkDotNet v0.13.10, Windows 11 (10.0.23580.1000)
AMD Ryzen 9 5950X, 1 CPU, 32 logical and 16 physical cores
.NET SDK 8.0.100-rc.2.23502.2
[Host]     : .NET 6.0.24 (6.0.2423.51814), X64 RyuJIT AVX2
DefaultJob : .NET 6.0.24 (6.0.2423.51814), X64 RyuJIT AVX2
```
| Method            | FileName             | Mean              | StdDev          | Rank | Allocated      |
|------------------ |--------------------- |------------------:|----------------:|-----:|---------------:|
| NilJS             | array-stress         |      7,563.941 μs |      26.9265 μs |    1 |     4533.76 KB |
| Jint_ParsedScript | array-stress         |     11,295.237 μs |      12.1198 μs |    2 |     7085.95 KB |
| Jint              | array-stress         |     11,531.269 μs |      79.8651 μs |    3 |     7112.01 …

Cache more script-global information when preparing AST

---

Jint.Tests.PublicInterface/ShadowRealmTests.cs
Jint.Tests/Runtime/ModuleTests.cs
Jint/Runtime/ExceptionHelper.cs
Jint/Runtime/Modules/DefaultModuleLoader.cs
Jint/Runtime/Modules/ModuleResolutionException.cs

* expose failed file path in module loading exception

Fix test script resolution to work with NET 8 artifacts output

---

Jint.Tests/Runtime/NumberTests.cs
Jint/Native/Number/NumberIntlHelper.cs
Jint/Native/Number/NumberPrototype.cs

Shortcut for https://github.com/sebastienros/jint/issues/729.
I guess it would be better if the cultures string array could be cached in the engine.

Use arguments in Number.toLocaleString

---

Jint.Tests/Runtime/EngineLimitTests.cs
Jint/Runtime/Interpreter/Expressions/JintExpression.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs
Jint/Runtime/Interpreter/JintStatementList.cs
Jint/Runtime/Interpreter/Statements/JintStatement.cs

We can now actually do better than the old limit `960` which was before NET 8

Return old recursion limit capabilities

---

Directory.Packages.props
Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj
Jint.Tests.PublicInterface/TimeSystemTests.cs
Jint/Native/Date/DateConstructor.cs
Jint/Runtime/DefaultTimeSystem.cs
Jint/Runtime/ITimeSystem.cs

Add GetUtcNow to ITimeSystem

---

Jint.Tests/Runtime/StringTests.cs
Jint.Tests/Runtime/StringTetsLithuaniaData.cs
Jint/Native/String/StringInlHelper.cs
Jint/Native/String/StringPrototype.cs

Adding some easy win test fixes. 
Before:
With fix:
Comments:
- Lithuanian case is quite tricky. Only fixed the tests. Maybe there is some more work to do to check larger texts are upper-case-ed correctly.
- Maybe some very specific functionality in internationalization (such as `LithuanianStringProcessor`) needs its place in the project, kind of some utils folder or similar. Please advice if that needs to be moved somewhere else. 
- I only wanted to fix "ToLocaleUpperCase" tests because it seemed an easy win. Apparently, more tests get fixed. Don't know why and I did not dig into that.

Adding cultural check to the "ToUpperCase" string prototype.

---

Jint.Tests/Runtime/ExecutionConstraintTests.cs
Jint/Engine.cs

Unify recursion constraints between invoke and call

---

Jint.Tests/Runtime/Debugger/StepFlowTests.cs
Jint/Engine.cs
Jint/Runtime/Interpreter/EvaluationContext.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs

When using `StepMode.Into`, the debugger callback `DebugHandler.Step` did not get fired before the execution of a single expression arrow function.
For example, having this statement
```js
[1, 2, 3].map(v => v * 2)
```
The debugger would not stop before the `v * 2` expression - only after.
In contrast, having this statement
```js
[1, 2, 3].map(function(v) { return v * 2; })
```
The debugger would stop before and after the `return v * 2` expression.
Two tests were added, one for the `function` type and one for the `arrow` type.

Debug StepInto stops at beginning of arrow function

---

Jint.Tests.PublicInterface/RavenApiUsageTests.cs
Jint.Tests/Runtime/Debugger/DebugHandlerTests.cs
Jint.Tests/Runtime/EngineTests.cs
Jint.Tests/Runtime/FunctionTests.cs
Jint.Tests/Runtime/InteropTests.cs
Jint.Tests/Runtime/RegExpTests.cs
Jint/JsValueExtensions.cs
Jint/Native/Array/ArrayInstance.cs
Jint/Native/Array/ArrayIteratorPrototype.cs
Jint/Native/Array/ArrayOperations.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Native/JsArray.cs
Jint/Native/JsBigInt.cs
Jint/Native/JsBoolean.cs
Jint/Native/JsNull.cs
Jint/Native/JsNumber.cs
Jint/Native/JsString.cs
Jint/Native/JsUndefined.cs
Jint/Native/JsValue.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Native/Proxy/JsProxy.cs
Jint/Native/RegExp/RegExpPrototype.cs
Jint/Native/TypedArray/IntrinsicTypedArrayConstructor.cs
Jint/Native/TypedArray/IntrinsicTypedArrayPrototype.cs
Jint/Native/TypedArray/JsTypedArray.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interpreter/Expressions/JintImportExpression.cs
Jint/Runtime/Modules/ModuleNamespace.cs

* Hide `CanPut()`
* Hide `DefinePropertyOrThrow()`
* Hide `DeletePropertyOrThrow()`
* Hide `IsArray()` from ObjectInstance and add `JsValueExtensions.IsArray()`
* Hide `SetPrototypeOf()` and allow set via Prototype property
* Make `IsLooselyEqual()` protected
* Hide `IsArrayLike`
* Only expose `Length` property for `JsArray` and `JsTypedArray`
* Remove `Invoke`

Cleanup ObjectInstance public API

---

Jint.Tests.PublicInterface/ModuleLoaderTests.cs
Jint/Runtime/Modules/ModuleFactory.cs
Jint/Runtime/Modules/ModuleLoader.cs
Jint/Runtime/Modules/ModuleRequestExtensions.cs

To support fully custom `IModuleLoader` implementations, some code from the abstract `ModuleLoader` class has been moved into the public static `ModuleFactory` class.
With these public methods, custom `IModuleLoader` implementations can be created and used without deriving from the abstract class `ModuleLoader`. This allows custom code to implement certain features like a cache for parsed `Esprima.Ast.Module` instances which can be shared across multiple engine instances. The additional methods allow to use a different source specifier for modules instead of the default `Uri.LocalPath` variant used by the default implementation.
The behavior of the existing `DefaultModuleLoader` has not been changed.
The static class allows to create `Jint.Runtime.Modules.Module` instances without …

Refactoring for custom module loader support

---

Jint.Tests.PublicInterface/PublicInterfaceTests.cs
Jint/Native/Argument/JsArguments.cs

Debugger implementations would like to see what arguments have been supplied and detect that object is special `arguments` object.

Make JsArguments public

---

Jint.Tests.PublicInterface/RavenApiUsageTests.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Engine.Advanced.cs
Jint/Engine.Ast.cs
Jint/Engine.cs
Jint/Key.cs
Jint/Native/Argument/JsArguments.cs
Jint/Native/Function/Function.cs
Jint/Native/Function/ScriptFunction.cs
Jint/Native/Global/GlobalObject.cs
Jint/Native/Promise/JsPromise.cs
Jint/Native/ShadowRealm/ShadowRealm.cs
Jint/Runtime/Descriptors/Specialized/ClrAccessDescriptor.cs
Jint/Runtime/Environments/DeclarativeEnvironment.cs
Jint/Runtime/Environments/Environment.cs
Jint/Runtime/Environments/FunctionEnvironment.cs
Jint/Runtime/Environments/GlobalEnvironment.cs
Jint/Runtime/Environments/ModuleEnvironment.cs
Jint/Runtime/Environments/ObjectEnvironment.cs
Jint/Runtime/Host.cs
Jint/Runtime/KnownKeys.cs
Jint/Runtime/Modules/SyntheticModule.cs
Jint/Runtime/Realm.cs

Checked the usual suspects seems that `Environment` and related APIs can be hidden, allows using `Key` and only one to suffer a small hit is `ObjectEnvironment` which is used by `with` and its usage is discouraged.

Internalize Environment services and use Key as name

---

Jint.Benchmark/HashBenchmark.cs
Jint/Extensions/Hash.cs
Jint/Key.cs

* https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function

Use FNV hash for Key

---

Jint.Tests/Runtime/NullPropagation.cs
Jint/Engine.Advanced.cs
Jint/Engine.Constraints.cs
Jint/Engine.Modules.cs
Jint/Engine.cs
Jint/Native/Json/JsonParser.cs
Jint/Options.Extensions.cs
Jint/Options.cs
Jint/Pooling/ArgumentsInstancePool.cs
Jint/Pooling/ReferencePool.cs
Jint/Runtime/DefaultReferenceResolver.cs
Jint/Runtime/Environments/Binding.cs
Jint/Runtime/ExceptionHelper.cs
Jint/Runtime/Interop/ClrFunction.cs
Jint/Runtime/Interop/ClrHelper.cs
Jint/Runtime/Interop/IReferenceResolver.cs
Jint/Runtime/Interop/TypeResolver.cs
Jint/Runtime/Interpreter/Expressions/BindingPatternAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs
Jint/Runtime/Interpreter/Expressions/JintExpression.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs
Jint/Runtime/Interpreter/Expressions/JintTaggedTemplateExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUnaryExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUpdateExpression.cs
Jint/Runtime/Interpreter/Statements/JintForInForOfStatement.cs
Jint/Runtime/Interpreter/Statements/JintVariableDeclaration.cs
Jint/Runtime/Modules/ModuleBuilder.cs
Jint/Runtime/Reference.cs
Jint/StrictModeScope.cs

* Move `Reference` to `Jint.Runtime` namespace
* Internalize `Binding`
* Internalize Advanced operations constructors
* Make Advanced operations inner classes
* Make Options sub-options inner classes
* Move delegate definitions under options
* Make `StrictModeScope` internal
* Move `ModuleBuilder` under `Runtime.Modules` namespace

Restructure and internalize

---

Jint.Tests/Runtime/ModuleTests.cs
Jint/Engine.Modules.cs
Jint/Engine.cs
Jint/Runtime/IScriptOrModule.cs
Jint/Runtime/ScriptRecord.cs

Non-module scripts can still import modules using the `import()` function. However, `Engine.Execute` and `Engine.Evaluate` always passed `string.Empty` as the source of the current script even if one was specified. 
With the change, `ScriptRecord` will get the value of `Script.Location.Source` as the source. Tests for `Engine.Execute` and `Engine.Evalute` with a custom `IModuleLoader` checking for a filled `referencingModuleLocation` were added.
The behavior for `Engine.Execute` without passing a `source` has not been changed (source is set to be `<anonymous>`)

Engine execute module resolving

---

Jint.Tests.Test262/Test262Harness.settings.json
Jint/Native/Set/JsSet.cs
Jint/Native/Set/SetPrototype.cs
Jint/Runtime/OrderedSet.cs
README.md

https://github.com/tc39/proposal-set-methods

Implement Set Methods for JavaScript

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/MethodInfoFunction.cs

Fix generic method return type handling under interop

---

Jint.Tests/Runtime/AwaitTests.cs
Jint/Runtime/Interop/DelegateWrapper.cs

This PR extends the work done in #1567 to add support for converting `ValueTask` and `ValueTask<T>` to promises.
This support is only available for .NET Standard 2.1 and .NET (non-Framework) targets. Support for .NET Framework and .NET Standard 2.0 targets could be enabled by adding a reference to [System.Threading.Tasks.Extensions](https://www.nuget.org/packages/System.Threading.Tasks.Extensions).

Add ValueTask and ValueTask<T> to Promise conversion

---

README.md

* Update README.md
As generators and tweaks seem to be a forever project, might be easier to finally release the v3. I've gone through API from consuming viewpoint and I think it's quite near of not exposing too much and allows wiggle room in development - and there's always v4...
A week or so to ensure latest release doesn't break too much, or a year.. maybe.

Updates for v3 RTM

---

Jint.Tests.PublicInterface/ModuleLoaderTests.cs
Jint.Tests/Runtime/ModuleTests.cs
Jint/Engine.Modules.cs
Jint/Runtime/Modules/DefaultModuleLoader.cs

Fixes #1747
* The internal dictionary of all available `ModuleBuilder` was used with the unresolved resolution key
* Modules created with the ModuleBuilder did not have any location, which prevented relative module location resolving.
* Public interface test for CustomModuleLoader adjusted to show the expected API usage of the `ResolvedSpecifier.Key` property.

Fix module builder loader interaction

---

Jint.Tests.PublicInterface/InteropTests.Dynamic.cs
Jint.Tests.PublicInterface/InteropTests.Json.cs
Jint.Tests.PublicInterface/InteropTests.NewtonsoftJson.cs
Jint.Tests.PublicInterface/InteropTests.SystemTextJson.cs
Jint.Tests.PublicInterface/InteropTests.cs
Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj

Most of those interop tests illustrate how Jint can interact with objects from popular libraries such as `Newtonsoft.Json`, `System.Text.Json` and dynamic objects such as `ExpandoObject`.
Because this can be a valuable reference for Jint users, they should not depend on any internals (which would be off limits for callers.) See #1766 for my endeavor on (successfully) integrating STJ.
This pretty much only moves the files over to the other project and updates the one location where internal code was used. Other tests like Newtonsoft and Dynamic didn't really use any internals, so it was just the namespace update there.
Initially, I moved over all tests that began with `InteropTests` and quickly realized how most of them don't _really_ mean interop in the sense of someone external trying to …

Move interop tests to the public interface test project

---

.github/workflows/pr.yml

Trying out the the new M1 offering.

Change GH Actions for PR to run on macos-14 instead of macos-latest

---

Jint.Benchmark/Directory.Build.props

Shared settings like `<UseArtifactsOutput>` can confuse benchmarks.

Reset Jint.Benchmark project build properties

---

Jint.Tests/Runtime/Domain/TextDecoder.cs
Jint.Tests/Runtime/JsValueConversionTests.cs
Jint.Tests/Runtime/TextTests.cs
Jint/JsValueExtensions.cs
Jint/Native/Object/ObjectInstance.cs

- resolves #1785
- implicit convert `DataView` and `ArrayBuffer` to `byte[]` when calling `ToObject` for interop
- add `JsValue` extensions to handle and convert those types when return from engine

feat: implicit convert DataView and ArrayBuffer to byte array

---

Jint.Tests/Runtime/AsyncTests.cs
Jint.Tests/Runtime/TestClasses/AsyncTestClass.cs
Jint/Native/JsValue.cs
Jint/Native/Object/ObjectInstance.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs
Jint/Runtime/Interop/DelegateWrapper.cs

With this PR it's possible to call object methods that return tasks.
For example:
```c#
var engine = new Engine();
engine.SetValue("log", new Action<object>(Console.WriteLine))
.SetValue("getTest", new Func<TestClass>(() => new()))
.SetValue("__result", 0);
engine.Execute("""
(async () => {
__result = "Before call";
let testClass = getTest();
__result = await testClass.GetDelayedStringAsync();
})();
""");
Console.WriteLine(engine.GetValue("__result"));
public class TestClass
{
public async Task<string> GetDelayedStringAsync()
{
await Task.Delay(5000).ConfigureAwait(false);
return "This is a delayed string";
}
}
```
Before PR:
After PR:

Add tasks to defaultobjectconverter

---

Jint.Benchmark/ListInteropBenchmark.cs
Jint/Native/Array/ArrayOperations.cs
Jint/Runtime/Descriptors/Specialized/ReflectionDescriptor.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/Reflection/ConstantValueAccessor.cs
Jint/Runtime/Interop/Reflection/DynamicObjectAccessor.cs
Jint/Runtime/Interop/Reflection/ExtensionMethodCache.cs
Jint/Runtime/Interop/Reflection/FieldAccessor.cs
Jint/Runtime/Interop/Reflection/IndexerAccessor.cs
Jint/Runtime/Interop/Reflection/MethodAccessor.cs
Jint/Runtime/Interop/Reflection/NestedTypeAccessor.cs
Jint/Runtime/Interop/Reflection/PropertyAccessor.cs
Jint/Runtime/Interop/Reflection/ReflectionAccessor.cs
Jint/Runtime/Interop/TypeReference.cs
Jint/Runtime/Interop/TypeResolver.cs

fixes #1772 
| **Diff**|Method|Toolchain|Mean|Error|Allocated|
| Old |Filter|Default|967.84 μs|12.909 μs|1935.49 KB|
| **New** |	| **Default** | **704.80 μs (-27%)** | **13.149 μs** | **973936 B (-51%)** |
| Old |Indexing|Default|305.84 μs|4.030 μs|113.96 KB|
| **New** |	| **Default** | **263.17 μs (-14%)** | **3.922 μs** | **92667 B (-21%)** |
| Old |HasProperty|Default|18.40 μs|0.246 μs|30.97 KB|
| **New** |	| **Default** | **11.17 μs (-39%)** | **0.090 μs** | **32 B (-100%)** |

Improve interop performance against CLR list types

---

Jint.Tests.PublicInterface/InteropTests.SystemTextJson.cs
Jint/Native/Array/ArrayPrototype.cs

Add test code to validate boolean vlue in the if condition.

---

Jint.Tests.PublicInterface/InteropTests.SystemTextJson.cs
Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj
Jint/Options.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs
Jint/Runtime/Interop/MethodInfoFunction.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/Reflection/IndexerAccessor.cs

On NET 8+ we can support reading and accessing STJ types without complex and hard to figure out configuration.

Support interop against System.Text.Json types on NET8+

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Native/Array/ArrayOperations.cs
Jint/Runtime/Interop/ObjectWrapper.cs

Test that is showing that trying to push to an interop list does not work. Should this work? Is there some rule that I'm not aware of that is trying to keep interop to read only operations?

Add support for wrapped lists to push and pop items

---

Jint.Tests/Runtime/ModuleTests.cs
Jint/Engine.Modules.cs
Jint/Runtime/Host.cs
Jint/Runtime/Modules/SyntheticModule.cs

While doing the parser migration, I spotted a bug: dynamically importing JSON modules (e.g. `await import("package.json", { with: { type: "json" } })`) results in an error ("default is not defined").
This PR attempts to fix the issue.

Fix dynamic importing of JSON modules

---

.github/workflows/build.yml
.github/workflows/pr.yml
Jint.Tests.Test262/Test262Harness.settings.json
Jint/Engine.cs
Jint/Native/Array/ArrayIteratorPrototype.cs
Jint/Native/TypedArray/IntrinsicTypedArrayPrototype.cs
Jint/Runtime/Environments/GlobalEnvironment.cs
Jint/Runtime/Interpreter/Expressions/DestructuringPatternAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUnaryExpression.cs
Jint/Runtime/Reference.cs

As spec requirements were loosened, makes sense to backport to 3.x. There's performance improvements from now needing to keep track of var global scope names. As Jint takes conformance over performance I believe this is one of the thing that has caused some perf difference compared to more relaxed interpreters.
| **Diff**|Method|Prepared|Toolchain|FileName|Mean|Error|Allocated|
|------- |-------|-------|-------|-------|-------:|-------|-------:|
| Old |Run|False|Default|dromaeo-3d-cube|23.065 ms|0.4453 ms|6315.24 KB|
| **New** |	| **False** | **Default** |	| **23.154 ms (0%)** | **0.1150 ms** | **6315.24 KB (0%)** |
| Old |Run|False|Default|dromaeo-core-eval|3.974 ms|0.0414 ms|327.5 KB|
| **New** |	| **False** | **Default** |	| **4.470 ms (+12%)** | **0.0272 ms** | **327.5 KB (0%)** |
| …

Backport var declaration and reference resolving performance improvements

---

Jint/Runtime/Debugger/DebugScope.cs
Jint/Runtime/Descriptors/Specialized/ClrAccessDescriptor.cs
Jint/Runtime/Environments/DeclarativeEnvironment.cs
Jint/Runtime/Environments/Environment.cs
Jint/Runtime/Environments/GlobalEnvironment.cs
Jint/Runtime/Environments/JintEnvironment.cs
Jint/Runtime/Environments/ModuleEnvironment.cs
Jint/Runtime/Environments/ObjectEnvironment.cs
Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintIdentifierExpression.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUpdateExpression.cs
Jint/Runtime/Interpreter/Statements/JintForStatement.cs

Backport improve environment handling performance and cleanup API

---

Jint/Native/Array/ArrayOperations.cs
Jint/Native/Array/ArrayPrototype.cs
Jint/Runtime/Descriptors/PropertyDescriptor.cs
Jint/Runtime/Interop/ObjectWrapper.Specialized.cs
Jint/Runtime/Interop/Reflection/FieldAccessor.cs
Jint/Runtime/Interpreter/Expressions/JintYieldExpression.cs

* cleanup Array capacity usage
| **Diff**|Method|N|Mean|Error|Allocated|
| Old |Slice|100|130.0 μs|2.40 μs|261.72 KB|
| **New** |	|	| **130.0 μs (0%)** | **1.26 μs** | **261.72 KB (0%)** |
| Old |Concat|100|158.7 μs|2.51 μs|301.56 KB|
| **New** |	|	| **162.6 μs (+2%)** | **2.05 μs** | **301.56 KB (0%)** |
| Old |Unshift|100|3,974.6 μs|52.74 μs|3521.1 KB|
| **New** |	|	| **3,599.1 μs (-9%)** | **23.64 μs** | **950.78 KB (-73%)** |
| Old |Push|100|2,544.4 μs|47.43 μs|857.81 KB|
| **New** |	|	| **2,456.0 μs (-3%)** | **28.59 μs** | **857.81 KB (0%)** |
| Old |Index|100|2,091.3 μs|30.77 μs|797.66 KB|
| **New** |	|	| **2,036.7 μs (-3%)** | **13.99 μs** | **797.66 KB (0%)** |
| Old |Map|100|1,321.4 μs|9.44 μs|3105.47 KB|
| **New** |	|	| …

Remove Enum.HasFlag usage

---

Jint.Tests/Runtime/StringTests.cs
Jint/Native/String/StringPrototype.cs

Attempt at fixing #1852. It's not complete as all arguments from the spec are not handled but it handles the common `locale` argument.
fixes #1852

Improve localeCompare implementation

---

Jint.Tests.PublicInterface/RavenApiUsageTests.cs
Jint/Engine.cs

Fix string-indexing optimizations against custom strings

---

.github/dependabot.yml

Prevents several PRs to be created. This can be improved to group dependencies (test libs, dev libs ...) in case a lib might block others.

Enable grouped version updates

---

Directory.Packages.props
Jint.Tests.PublicInterface/RavenApiUsageTests.cs
Jint/Engine.Ast.cs
Jint/Native/Function/ClassDefinition.cs
Jint/Runtime/Interpreter/Expressions/JintArrayExpression.cs
Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs
Jint/Runtime/Modules/ModuleBuilder.cs

Release notes: https://github.com/adams85/acornima/releases/tag/v1.1.0

Upgrade to Acornima v1.1.0

---

Jint.Tests/Runtime/InteropTests.MemberAccess.cs
Jint/Options.cs
Jint/Runtime/Interop/TypeResolver.cs

Add interop option ThrowOnUnresolvedMember

---

Directory.Packages.props
Jint.Tests.Test262/Test262Harness.settings.json
Jint/Extensions/WebEncoders.cs
Jint/Native/ArrayBuffer/ArrayBufferConstructor.cs
Jint/Native/Global/GlobalObject.cs
Jint/Native/JsArrayBuffer.cs
Jint/Native/JsString.cs
Jint/Native/TypedArray/TypedArrayConstructor.Types.cs
Jint/Native/TypedArray/TypedArrayConstructor.Uint8Array.cs
Jint/Native/TypedArray/TypedArrayConstructor.cs
Jint/Native/TypedArray/TypedArrayPrototype.cs
Jint/Native/TypedArray/Uint8ArrayPrototype.cs
Jint/Runtime/ExceptionHelper.cs
README.md

https://tc39.es/proposal-arraybuffer-base64/

Implement Uint8Array to/from base64

---

Directory.Packages.props
Jint.Tests.Test262/Test262Harness.settings.json
Jint/Native/Array/ArrayOperations.cs
Jint/Native/JsTypedArray.cs
Jint/Runtime/Interpreter/Expressions/JintArrowFunctionExpression.cs

* resizable array buffer length checks should obey bounds checks
* fix async function expression prototype
* upgrade System.Text.Json to version 8.0.4

Backport typed array related fixes

---

Jint.Tests/Runtime/ArrayTests.cs
Jint/Native/Array/ArrayPrototype.cs

Avoid Array.sort infinite loops on full framework

---

Jint.Tests.PublicInterface/InteropTests.Dynamic.cs
Jint/Runtime/Descriptors/Specialized/ReflectionDescriptor.cs
Jint/Runtime/Interop/Reflection/DynamicObjectAccessor.cs
Jint/Runtime/Interop/Reflection/ReflectionAccessor.cs
Jint/Runtime/Interop/TypeResolver.cs

Fix dynamic object member access logic

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Options.cs
Jint/Runtime/Interop/ObjectWrapper.cs

Implements the feature discussed in https://github.com/sebastienros/jint/issues/1945.

Add ObjectWrapperReportedMemberTypes to Options

---

Jint/Runtime/Interop/ObjectWrapper.cs

In the scenario described in https://github.com/sebastienros/jint/issues/1945 I need to get the CLR type of `ObjectWrapper`. This PR makes the corresponding property public.

Make ObjectWrapper ClrType public

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Engine.cs
Jint/Native/Function/Function.cs
Jint/Native/Function/ScriptFunction.cs

I'm open to finding a better solution to the problem described below, as the current fix has weird ergonomics.
Accessing `FunctionDeclaration` of a `MethodInfoFunction` (CLR functions) currently throws - the test* included describes the scenario. I believe accessing the property should never throw (I hate linking to MSDN, alas: https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/property?redirectedfrom=MSDN). 
This forces a sprinkle of `!` in the codebase in places where we know the function is not a CLR function (this is the part I don't like).
_*I've included two tests now, one for the delegate, and one for the method info function._
Unrelated to this, for the debugger I'm working on, I'd need to make at least some information of `MethodInfoFunction` and …

Fix throwing on accessing CLR FunctionDeclaration

---

Jint.Tests/Runtime/ModuleTests.cs
Jint/Runtime/Interpreter/Statements/JintExportDefaultDeclaration.cs

Before this `JintExportDefaultDeclaration.ExecuteInternal` always overwrites the probably existing binding from `SourceTextModule.InitializeEnvironment`.
- Fixes #1951

Don't overwrite default export from `SourceTextModule`

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Native/Atomics/AtomicsInstance.cs
Jint/Options.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/Reflection/DynamicObjectAccessor.cs

* to have parity, we shouldn't limit to declared members only as generic search will try to find from all levels
* obey member filter while reporting
* cleanup

Tweak object wrapper reported members logic

---

Jint.Tests.Test262/Test262Harness.settings.json
Jint/Native/Array/ArrayOperations.cs
Jint/Native/JsTypedArray.cs
Jint/Runtime/Debugger/DebugScope.cs
Jint/Runtime/Descriptors/Specialized/ClrAccessDescriptor.cs
Jint/Runtime/Environments/DeclarativeEnvironment.cs
Jint/Runtime/Environments/Environment.cs
Jint/Runtime/Environments/GlobalEnvironment.cs
Jint/Runtime/Environments/JintEnvironment.cs
Jint/Runtime/Environments/ModuleEnvironment.cs
Jint/Runtime/Environments/ObjectEnvironment.cs
Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintIdentifierExpression.cs
Jint/Runtime/Interpreter/Expressions/JintMemberExpression.cs
Jint/Runtime/Interpreter/Expressions/JintUpdateExpression.cs

There's no limit to [JS evilness](https://github.com/tc39/test262/blob/d62fa93c8f9ce5e687c0bbaa5d2b59670ab2ff60/test/language/statements/with/get-mutable-binding-binding-deleted-in-get-unscopables-strict-mode.js).

Update test262 test suite and fix issues

---

Jint.Tests/Runtime/InteropTests.MemberAccess.cs
Jint/Runtime/Interop/TypeResolver.cs

resolves sebastienros/jint#1962
When `TypeResolver:TryFindMemberAccessor` resolves a property, it might find one that was hidden where the non-hidden one would normally be found by C++ member access.
For example, when you access the `A` member from JavaScript, you may get the hidden one (I say "may" because `Type:GetProperties` does not specify an order in a number of versions of .NET supported by jint).
```
class Foo
{
public int A {get;set;}
public string B {get;set;}
}
class Bar :  Foo
{
public new float A { get; set; }
}
```
([This dotnet fiddle](http://dotnetfiddle.net/NQRXIJ) shows that both `A` elements are iterated by `GetProperties` even though if `b` is a `Bar`, `b.A` unambiguously refers to `Bar:A`)
This change ensures that in the case where a property in a derived class hides …

Don't find hidden property instead of the hiding property

---

Jint.Tests/Runtime/ArrayTests.cs
Jint/Collections/ObjectTraverseStack.cs
Jint/Native/Array/ArrayPrototype.cs

Fix Array.prototype.toString() stackoverflow

---

Jint.Tests/Runtime/PromiseTests.cs
Jint/Native/Promise/PromiseConstructor.cs

When using `Promise.withResolvers()`, the returned object had `resolve` and `reject` swapped. Meaning that
```js
const p = Promise.withResolvers();
p.resolve();
return p.promise;
```
did return a _rejected_ promise.
and
```js
const p = Promise.withResolvers();
p.reject();
return p.promise;
```
dir return a _resolved_ promise.
---
The fix: The record `PromiseCapability` had the following property order
```cs
internal sealed record PromiseCapability(
JsValue PromiseInstance,
ICallable Resolve,   // <-- Resolve first, Reject last
ICallable Reject,
JsValue RejectObj,   // <-- Reject first, Resolve first
JsValue ResolveObj
);
```
The method `PromiseConstructor.NewPromiseCapability()` however flipped the two last properties when calling the PromiseCapability constructor.
---
Refactoring: In …

Promise.withResolvers() returned object had resolve and reject functions swapped

---

Jint.Tests/Runtime/ExecutionConstraintTests.cs

Found a flaky test in #1983 . This PR makes this one test more robust (fixes a race condition). 
The test will now be green, no matter when the provided `ThreadPool.QueueUserWorkItem` will get executed. This has been simulated by adding `Thread.Sleep(10000)` everywhere within the `threadPoolAction` locally. Without the adjustments, the sleep additions would break the tests.

Made test of cancellation of engine execution more robust

---

Jint/Pooling/ObjectPool.cs

This is a micro optimization which caught my eye when profiling my own application. I haven't tested the impact on overall execution performance. But given that the pool is used at basically every function invocation, I assume that it won't hurt to change it. Given that the change doesn't make the code much harder to understand or maintain, I just did it.
---
The object pool is only used internally and a few of them are allocated per `Engine` instance. The pool has basically "best effort" guarantees. Given that `Engine` itself is not declared as thread safe, no synchronization was used for the change.
The performance problem was mainly with empty or almost empty pools. In those cases, the pool always looped over its internal array to find a possible match. Given that the pool can easily …

Early out in ObjectPool to avoid loop execution

---

Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj
Jint.Tests.PublicInterface/SetTests.cs
Jint/Native/JsSet.cs
Jint/Native/Set/SetConstructor.cs
Jint/Native/Set/SetPrototype.cs
Jint/Runtime/Intrinsics.cs
Jint/Runtime/OrderedSet.cs

Allow use of the `Jint.Native.JsSet` class outside of expressions, allowing consumers to cast to this type and call its members.
For example, you might want to convert it to a `HashSet<T>` to use it elsewhere without being tied to using Jint types.
The `OrderedSet` class also had to be made `public` due to its use in the `JsSet` constructor.

Make JsSet public

---

Jint.Tests.PublicInterface/MapTests.cs
Jint.Tests.PublicInterface/SetTests.cs
Jint/Native/JsMap.cs
Jint/Native/JsSet.cs
Jint/Native/Map/MapConstructor.cs
Jint/Native/Map/MapPrototype.cs
Jint/Native/Set/SetPrototype.cs
Jint/Runtime/Intrinsics.cs

* make JsSet and JsMap members new as they indicate a specific usage scenario

Make JsMap public

---

Jint/Native/JsSet.cs

Might not be easily available if backing storage changes.

Make JsSet int indexer internal

---

Jint.Tests.PublicInterface/InteropTests.Json.cs
Jint.Tests/Runtime/InteropTests.TypeReference.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Options.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs
Jint/Runtime/Interop/ObjectWrapper.cs
Jint/Runtime/Interop/TypeReference.cs
Jint/Runtime/Interop/TypeReferencePrototype.cs
Jint/Runtime/Interop/TypeResolver.cs

Exclude static fields and properties from ObjectWrapper by default

---

Directory.Packages.props
Jint.Tests.PublicInterface/CallStackTests.cs
Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj
Jint/Engine.Advanced.cs
Jint/Native/Error/ErrorConstructor.cs
Jint/Options.Extensions.cs
Jint/Options.cs
Jint/Runtime/CallStack/JintCallStack.cs
Jint/Runtime/JavaScriptException.cs

A preliminary idea, this would allow one to modify the stack string generation, such as using a map of the source map.

Add Options.InteropOptions.BuildCallStackHandler

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/InteropHelper.cs

Improve interop conversion logic between numeric types

---

Jint.Tests/Runtime/NumberTests.cs
Jint/Runtime/TypeConverter.cs

Improve infinity detection when parsing numbers on full framework

---

Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj
Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj

Mono is no longer present so build fails for full framework.

Fix building on GH Actions Ubuntu 24.04

---

Jint.Tests.CommonScripts/Jint.Tests.CommonScripts.csproj
Jint.Tests.PublicInterface/Jint.Tests.PublicInterface.csproj
Jint.Tests/Jint.Tests.csproj

Seems that Unity supports it already and now testing frameworks are dropping support for net462.

Use net472 to run full framework tests

---

Jint.Tests/Runtime/ExecutionConstraintTests.cs
Jint/Constraints/MaxStatementsConstraint.cs

Current implementation of MaxStatementsConstraint allows one more statement to be executed. The increment must be in prefix form so value is updated before being used.

Fix statement counting code in MaxStatementsConstraint

---

Jint/Runtime/Interpreter/Expressions/ExpressionCache.cs
Jint/Runtime/Interpreter/Expressions/JintArrayExpression.cs
Jint/Runtime/Interpreter/Expressions/JintCallExpression.cs
Jint/Runtime/Interpreter/Expressions/JintExpression.cs
Jint/Runtime/Interpreter/Expressions/JintNewExpression.cs
Jint/Runtime/Interpreter/Expressions/JintObjectExpression.cs

Puts common logic and duplicated code to one place.

Create ExpressionCache to unify constant lookups

---

Jint/Runtime/Interpreter/JintFunctionDefinition.cs

| Old |Run|dromaeo-3d-cube|15.385 ms|0.2515 ms|6305.56 KB|
| **New** |	|	| **15.568 ms (+1%)** | **0.1567 ms** | **6215.83 KB (-1%)** |
| Old |Run|dromaeo-core-eval|3.041 ms|0.0381 ms|327.41 KB|
| **New** |	|	| **3.122 ms (+3%)** | **0.0254 ms** | **327.06 KB (0%)** |
| Old |Run|dromaeo-object-array|31.828 ms|0.2936 ms|96259.1 KB|
| **New** |	|	| **31.940 ms (0%)** | **0.1914 ms** | **96258.38 KB (0%)** |
| Old |Run|droma(...)egexp [21]|123.952 ms|2.4561 ms|149449.74 KB|
| **New** |	|	| **124.259 ms (0%)** | **2.4668 ms** | **151579.51 KB (+1%)** |
| Old |Run|droma(...)tring [21]|238.855 ms|5.2330 ms|1315958.49 KB|
| **New** |	|	| **244.141 ms (+2%)** | **6.9506 ms** | **1315860.24 KB …

Remove closure allocations from JintFunctionDefinition

---

Jint/Collections/HybridDictionary.cs
Jint/Engine.cs
Jint/Native/Function/Function.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs

| Old |Run|dromaeo-3d-cube|15.819 ms|0.2254 ms|6215.84 KB|
| **New** |	|	| **15.554 ms (-2%)** | **0.1525 ms** | **6216.3 KB (0%)** |
| Old |Run|dromaeo-core-eval|3.104 ms|0.0271 ms|327.06 KB|
| **New** |	|	| **3.079 ms (-1%)** | **0.0210 ms** | **327.19 KB (0%)** |
| Old |Run|dromaeo-object-array|32.001 ms|0.3956 ms|96258.39 KB|
| **New** |	|	| **31.902 ms (0%)** | **0.3696 ms** | **96258.62 KB (0%)** |
| Old |Run|droma(...)egexp [21]|125.062 ms|2.4842 ms|153003.42 KB|
| **New** |	|	| **120.858 ms (-3%)** | **2.4037 ms** | **149368.27 KB (-2%)** |
| Old |Run|droma(...)tring [21]|236.668 ms|5.6226 ms|1315871.9 KB|
| **New** |	|	| **241.047 ms (+2%)** | **5.4212 ms** | **1315886.06 KB …

Flatten declarative record instance creation lookups

---

Jint.Benchmark/DromaeoBenchmark.cs
Jint.Benchmark/EngineComparisonBenchmark.cs
Jint.Benchmark/EvaluationBenchmark.cs
Jint.Benchmark/Scripts/dromaeo-3d-cube-modern.js
Jint.Benchmark/Scripts/dromaeo-core-eval-modern.js
Jint.Benchmark/Scripts/dromaeo-object-array-modern.js
Jint.Benchmark/Scripts/dromaeo-object-regexp-modern.js
Jint.Benchmark/Scripts/dromaeo-object-string-modern.js
Jint.Benchmark/Scripts/dromaeo-string-base64-modern.js
Jint.Benchmark/Scripts/evaluation-modern.js
Jint.Benchmark/Scripts/stopwatch-modern.js
Jint.Benchmark/StopwatchBenchmark.cs

Modern syntax with let and const etc will create extra stress due to lexical scope building requirements.

Support running DromaeoBenchmark with modern JS syntax

---

Jint/Engine.Ast.cs
Jint/Engine.cs
Jint/HoistingScope.cs
Jint/Runtime/Environments/DeclarativeEnvironment.cs
Jint/Runtime/Environments/FunctionEnvironment.cs
Jint/Runtime/Interpreter/DeclarationCache.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs
Jint/Runtime/Interpreter/JintStatementList.cs
Jint/Runtime/Interpreter/Statements/JintBlockStatement.cs
Jint/Runtime/Interpreter/Statements/JintSwitchBlock.cs
Jint/Runtime/Modules/SourceTextModule.cs

Instead of just caching the declarations, cache the actual bound name determination. This helps especially with modern syntax utilizing let and const which have specific lexical scope.

Improve environment initialization performance

---

Jint.Benchmark/ClassBenchmark.cs
Jint/Native/Object/ObjectInstance.cs

| **Diff**|Method|Mean|Error|Allocated|
|------- |-------|-------:|-------|-------:|
| Old |ConstructSimple|139.6 ms|2.40 ms|369.26 MB|
| **New** |	| **134.8 ms (-3%)** | **2.11 ms** | **369.26 MB (0%)** |
| Old |ConstructDeepInheritance|157.5 ms|3.15 ms|330.2 MB|
| **New** |	| **152.1 ms (-3%)** | **3.00 ms** | **330.2 MB (0%)** |
| Old |GetSet|120.1 ms|2.00 ms|343.33 MB|
| **New** |	| **117.8 ms (-2%)** | **1.20 ms** | **343.33 MB (0%)** |

Add fast paths for object Get/Set for simple objects

---

Jint.Tests/Runtime/DateTests.cs
Jint/Native/JsDate.cs

Added tests for `DateFlags.DateTime{Min,Max}Value` ref. https://github.com/sebastienros/jint/issues/2057#issuecomment-2666563547
Tests did not fail, indicating this code may be redundant.  
The `JsDate` constructor calls `engine.Realm.Intrinsics.Date.FromDateTime` i.e. this bit which already sets the flags correctly:
https://github.com/sebastienros/jint/blob/f012c8398fbfd0dddd377114169d4d67be210817/Jint/Native/Date/DateConstructor.cs#L197-L207
No other tests failed locally with this change. I hope I haven't overlooked anything else and this resolves https://github.com/sebastienros/jint/issues/2057

Remove apparently-redundant `DateFlags` calculation in `JsDate` constructor

---

Jint/Engine.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs

| **Diff**|Method|Prepared|Modern|Toolchain|Mean|Error|Allocated|
|------- |-------|-------|-------|-------|-------:|-------|-------:|
| Old |CoreEval|False|False|Default|4.326 ms|0.0523 ms|335.29 KB|
| **New** |	| **False** | **False** | **Default** | **4.055 ms (-6%)** | **0.0576 ms** | **335.07 KB (0%)** |
| Old |CoreEval|True|False|Default|4.195 ms|0.0805 ms|320.4 KB|
| **New** |	| **True** | **False** | **Default** | **3.250 ms (-23%)** | **0.1556 ms** | **319.9 KB (0%)** |
| Old |CoreEval|False|True|Default|5.791 ms|0.0592 ms|334.67 KB|
| **New** |	| **False** | **True** | **Default** | **5.713 ms (-1%)** | **0.0736 ms** | **334.11 KB (0%)** |
| Old |CoreEval|True|True|Default|4.207 ms|0.1266 ms|320.24 KB|
| **New** |	| **True** | **True** | **Default** | **3.107 ms (-26%)** | …

Avoid creating context for eval if eval is not present

---

Jint.Benchmark/FunctionBenchmark.cs
Jint.Tests/Runtime/Interpreter/JintFunctionDefinitionTest.cs
Jint/Runtime/Interpreter/JintFunctionDefinition.cs

Currently we don't detect expressions properly which causes extra environment to be created even though it isn't necessary. Requires more AST analysis.

Improve function arguments parameter expression detection

---

Jint/Constraints/ConstraintsOptionsExtensions.cs
Jint/Constraints/MemoryLimitConstraint.cs

Check against long.MaxValue in memory limit configuration

---

Jint.Benchmark/InteropLambdaBenchmark.cs
Jint/Extensions/ReflectionExtensions.cs
Jint/Native/Function/Function.cs
Jint/Runtime/Interop/DefaultObjectConverter.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs
Jint/Runtime/Interop/ObjectWrapper.cs

I'm adding the test case and also the option which shows converting to native `JsValue` objects from JSON deserialization. If use case is reading then native types should produce best performance. I might have made mistakes so take it with a grain of salt.
The delegate building is now cached against AST node reference so it should align quite well with the idea of preparing and caching AST when needed.
| **Diff**|Type|Method|Mean|Error|Allocated|
| Old |ClrObject|InlineCSharp|13.958 μs|0.1449 μs|30.08 KB|
| **New** |	|	| **12.110 μs (-13%)** | **0.2307 μs** | **28.2 KB (-6%)** |
| Old |ClrObject|InlineEngineInvoke|14.468 μs|0.1819 μs|30 KB|
| **New** |	|	| **12.620 μs (-13%)** | **0.1171 μs** | **28.13 KB (-6%)** |
| Old …

Improve interop performance against dictionary

---

Jint.Tests/Runtime/TestClasses/AsyncTestClass.cs
Jint/JsValueExtensions.cs

This protects from errors that could hang the engine.

Add default 10 second timeout for promise unwrapping

---

Jint.Tests/Runtime/FunctionTests.cs
Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs

- Effectively revert delegate cache optimization
- Each function instance _requires_ its own .NET representation to handle parameters correctly (-> function environment)
- Use a factory method to reduce `System.Linq.Expression` tree usage and therefore also the need for compiling them.
- Compile an expression tree that allows to retarget a delegate to the actual Function instance (1 per AST, not per function instance).
- Ensure returning the same delegate instance to allow for example unregistering handlers
- Add 2 tests
- Ensure multiple invokations using .NET interop don't cache function environment
- Ensure multiple invokations using JavaScript-only functions don't cache function environment

#2099: Fix erroneous caching by providing each function instance with it own interop variant

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/DefaultTypeConverter.cs

- Remove unnecessary reflection code and instead use type of function target directly
- Add test
Should fix #2114

#2114: Fix NRE in BuildTargetBinderDelegate

---

Jint.Tests.PublicInterface/CallStackTests.cs
Jint.Tests/Runtime/ErrorTests.cs
Jint/Runtime/CallStack/JintCallStack.cs

Currently, there are two main styles of stacktraces emitted by most JS engines:
- `at functionName (filename.js:1:1)` / `at filename.js:1:1`
- V8 (Node.js, Deno, Chrome, Edge, Opera and all other Chromium-based browsers)
- Hermes (React Native and Expo)
- ChakraCore (old Edge and old React Native for Windows)
- Chakra JScript (Internet Explorer 10+)
- LibJS (Ladybird)
- GraalJS
- QuickJS
- Rhino
- Nashorn
- Espruino
- XS
- Duktape
- MuJS
- njs (nginx)
- `functionName@filename.js:1:1` / `@filename.js:1:1`
- SpiderMonkey (Firefox)
- JavaScriptCore (Safari, Bun and all browsers running in iOS)
- V4 (Qt)
And there is the Jint stacktrace format: `at functionName () filename.js:1:1` / `at filename.js:1:1`.
Tools for error handling, logging, and observability often need to parse the stacktrace. …

Implement V8-styled stacktraces

---

Jint.Tests/Runtime/InteropTests.cs
Jint/Runtime/Interop/ObjectWrapper.Specialized.cs

Support writing length to IList under interop

---

Jint.Tests.PublicInterface/InteropTests.Json.cs
Jint/Native/Json/JsonSerializer.cs
Jint/Options.cs

feat #2141 
i have no idea about how to deal with `replacer(key: string, value: any)` properly yet so i just complete a part of feature now :(

Passing `space` arg to `Options.Interop.SerializeToJson`

---

Jint.Tests/Runtime/AsyncTests.cs
Jint/Native/Disposable/DisposeCapability.cs
Jint/Options.cs
Jint/Runtime/Interpreter/Expressions/JintAwaitExpression.cs

-  feat(option): Add options.Constraints.PromiseTimeout for UnwrapIfPromise (DisposeResources & AwaitExpression)
- test(unit): cover custom timeout path for await

 Add `Options.Constraints.PromiseTimeout` To Control timeout for `DisposeHint.Async` and `JintAwaitExpression`

---

Jint.Tests/Runtime/ProxyTests.cs
Jint/Runtime/Interop/ObjectWrapper.cs

When iterating over a JsProxy of a clr list or access its length property, jint fails with `System.InvalidCastException : Unable to cast object of type 'Jint.Native.JsProxy' to type 'Jint.Runtime.Interop.ObjectWrapper'.`
This PR fixes the issue - but I am pretty sure, that there is a "better" more solid solution for it?

Fix iterating a clr list proxy and length property

---

Jint.Tests/Runtime/BigIntTests.cs
Jint/Runtime/Interpreter/Expressions/JintAssignmentExpression.cs
Jint/Runtime/Interpreter/Expressions/JintBinaryExpression.cs
Jint/Runtime/Interpreter/Expressions/JintExpression.cs

Fix BigInt modulo assignment
